### ISSUE TITLE
One disconnect button has ellipsis, other does not

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1009]
<img width="659" alt="Screenshot 2019-05-03 at 11 08 35" src="https://user-images.githubusercontent.com/848085/57131287-d4d72380-6d93-11e9-9f3b-a4168b0203fa.png">

The [Web Session](https://github.com/mozilla/fxa/blob/42c6a84b306710d25cbe9d223d06192de59d5abc/packages/fxa-content-server/app/scripts/templates/settings/clients.mustache#L50) in this image does not have an ellipsis, the [Sync session does](https://github.com/mozilla/fxa/blob/42c6a84b306710d25cbe9d223d06192de59d5abc/packages/fxa-content-server/app/scripts/templates/settings/clients.mustache#L34).

Note, [Revoke for OAuth apps](https://github.com/mozilla/fxa/blob/42c6a84b306710d25cbe9d223d06192de59d5abc/packages/fxa-content-server/app/scripts/templates/settings/clients.mustache#L58) does not use an ellipsis, nor does [Download](https://github.com/mozilla/fxa/blob/42c6a84b306710d25cbe9d223d06192de59d5abc/packages/fxa-content-server/app/scripts/templates/settings/clients.mustache#L67) for the mobile apps.

@ryanfeeley, @johngruen - which version should we be using?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-72)
┆Issue Number: FXA-72

**Comment by ryanfeeley** [comment]
One leads to a dialog, the other does not. This is the difference, and very common for software.

From: https://design.firefox.com/photon/copy/punctuation.html

> **Ellipses**
> Use with Button or Menu items when the action requires additional user input, usually via a Dialog, an Alert or moving the operation to another window or part of the UI.

I believe that since the move to Amplitude, we stopped tracking users responses in this dialog:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/68213/57140051-d9e0a680-6d84-11e9-9ad7-03a088352b83.png">

@irrationalagent or @davismtl can confirm that.

If we are no longer tracking these responses, and don't feel they are important, the dialog can be removed, as can the appended  …

To complicate matters further, because we're not deleting data from the services, it might make sense for GDPR compliance to let users know that we are not deleting data from any devices or services at this point.

**Comment by davismtl** [comment]
We do track the answers:
https://analytics.amplitude.com/mozilla-corp/chart/new/pwt478j

Rather not say is the default for some reason so it has a bias.

>  it might make sense for GDPR compliance to let users know that we are not deleting data from any devices or services at this point.

Granted the UX isn't great but if you read the screenshot just shared we say:

"Your browsing data will remain on Firefox Beta on Ryan's iPad, but it will no longer sync with your account."

It does seem out of context with the survey so maybe it's something we display after? 🤷🏼‍♂️

**Comment by juliastarkov** [comment]
The ellipses button does not scale well on mobile, so there is this bug currently:

![60924738-c5260080-a256-11e9-94ea-35175c7e6c6e](https://user-images.githubusercontent.com/26334275/60995379-40df8600-a307-11e9-9e46-3c74a80a14d1.jpeg)

**Comment by shane-tomlinson** [comment]
@juliastarkov The above has a bug on file at https://github.com/mozilla/fxa/issues/1254

**Comment by clouserw** [comment]
New settings designs will fix this
