### ISSUE TITLE
Avoid Thundering Herd Issue on Customer Updates during Token Requests

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10301]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3925)

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

Benjamin Bangert  I believe you have an idea for this. 🙂

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Dataloader can help with this, but it only helps on a per-tick basis per node process. Depending on how long the Stripe fetch takes, that can still be multiple ticks per app instance, which can hit Stripe pretty hard. We might have to just live with this happening for a little bit until we can switch to storing these records in Firestone and having the Firestone record updated on-webhook from Stripe product/plan webhooks.

**Comment by biancadanforth** [comment]
Sentry issue: [FXA-AUTH-PROD-DN](https://sentry.prod.mozaws.net/operations/fxa-auth-prod/issues/13061602/?referrer=github_plugin)

Ben: (paraphrase)
We cache the stripe plans we fetch in Stripe from Redis; we need that info very frequently from different systems. Different plans etc. That cache expires every day or two. When the cache expires, however many application instances we have running all awnt that info at the same time. Thousands of requests we get. Also plans and products don’t change. We can also hook up webhooks to Firestore to sync up with Stripe. We added TTLs at some point. I don’t think we have webhooks hooked up for plan and product updates. We could also do that to update Redis, otherwise never let it expire.

**Comment by biancadanforth** [comment]
[Relevant Grafana panel](https://earthangel-b40313e5.influxcloud.net/d/J81nRFfWz/auth-server?orgId=1&refresh=1m&viewPanel=73&from=now-7d&to=now)

@bbangert , is it possible this issue has been made worse since the deploy of Train 215 to prod 9/22 (something IAP related perhaps)? It looks higher for the past 24 hours relative to the previous 6 days.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

IAP has been in production since the previous deploy. I’m not familiar with any other changes that made it into this release that would’ve had this effect.
