### ISSUE TITLE
customs-server change v1.136.4-private not in v1.136.5. Correct? Not correct?

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#1058]
Just happened to noticed this anomaly. The change for customs-server from v1.136.4-private, is not in the v1.136.5 tag. Shouldn't it be? 

```
$ (cd fxa; git fetch origin; git checkout v1.136.5 2>/dev/null; \
          grep replace packages/fxa-customs-server/lib/server.js)
<... no output ...>
```
```
$ (cd fxa-private; git fetch origin; git checkout v1.136.4-private 2>/dev/null; \
          grep replace packages/fxa-customs-server/lib/server.js)
      return `${local.replace(/\+.*$/, '').replace(/\./g, '')}@${domain}`
```

**Comment by jrgm** [comment]
Maybe clearer to use `git-grep`:
```
$ (cd fxa; git grep replace v1.136.5 -- packages/fxa-customs-server/lib/server.js)
<... no output ...>

$ (cd fxa-private; git grep replace v1.136.4-private -- packages/fxa-customs-server/lib/server.js)
v1.136.4-private:packages/fxa-customs-server/lib/server.js:      return `${local.replace(/\+.*$/, '').replace(/\./g, '')}@${domain}`
```

**Comment by philbooth** [comment]
It's in the `v1.136.5-private` tag. I didn't bother mentioning that tag in the deploy bug because only the auth server has changed, apologies if that was confusing.

**Comment by jrgm** [comment]
I was asking it more philosophically. Should it be a "contract" that a "higher" tag is always a superset of the changes[*] in a "lower" tag.

([*] - yes, but what if the change was a revert. Yeah, yeah, modulo if a change is reverted.)

**Comment by philbooth** [comment]
Understood. I guess conceptually I was still treating them as separate repos in my head, but that's a poor reflection of the way things are now.

Although, if we wanted to be really honest about making every tag a superset of its predecessors, it would mean we only ever use the private tags because there's changes in the private repo that will never be ported to the public one. I'm not fundamentally opposed to that but it does seem like a funny wrinkle.

**Comment by jrgm** [comment]
Yeah, I'm probably off-base here in expecting cross-repo tags to always line up. The `-private` release tags and when/how they get merged backed are always going to be complicated. Closing.
