### ISSUE TITLE
Document How RPs Could Add Icon Images to the FxA CDN for Subscriptions Products

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#10587]
https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-sub-platform#configuration mentions that the icon urls for a product's metadata need to be at https://accounts-static.cdn.mozilla.net/, but does not say how to get those images onto the CDN.  We should document that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4047)

**Comment by lmorchard** [comment]
Driving by since I saw this issue in my inbox and it rang a bell. FWIW, the docs for releasing icons are over here:

https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/release-process#special-cases

Unless it's changed, this is a manual process for FxA / subplat devs and not a self-service process for RPs - i.e. RPs have to work with the dev team to get the icons hosted.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

Thanks Les for the context here. While we do have docs for uploading an image to our CDN, we don’t have docs for how RPs can give us those images for upload, so I think this ticket stands.

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

The process is probably something like: Open a PR with the images to the right folder or file a ticket to add the images with the images attached.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
