### ISSUE TITLE
Expose (new) email address in profile-change SET data

### ISSUE THREAD

**Issue by eviljeff** [mozilla/fxa#10691]
With the older SQS event notifications the payload for `primaryEmailChangedEvent` contained all the data needed to process the event (i.e. the new email address).  However with `profile-change` SET from the webhook it only contains the uuid, meaning the client has to make an additional call back to FxA to retrieve the profile data to get the new email address.

This generally seems quite wasteful, with added complexity needed to handle quite simple notifications (and in the case of AMO [https://github.com/mozilla/addons-server/issues/14730](https://github.com/mozilla/addons-server/issues/14730) is a problem because we don't store the refresh token for the user right now). Including the new email address would alleviate this.

Using the refresh token also means updates to the email address is only possible until the expiry of the token.  Email is the only way to contact users in the case of security problems so it really needs to stay up to date so they can be contacted, e.g. there is a security bug in their add-on that needs to be addressed.

[filed on the back of a Slack discussion with @bbangert )

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4085)

**Comment by data-sync-user** [comment]
➤ Stuart Colville commented:

Having up to date email addresses for our users is pretty critical for AMO (as noted in the issue description) so reliance on tokens that can expire either due to age, or as a result of a user explicitly logging out of AMO via FXA would be a problem for us.

Is it possible to reconsider bumping up in priority providing the email address change data via the webhook? Though for that to work that would require the webhook to be always called even if the user has signed out via FXA (would that be the case?). 

Failing that is there another API that we could always reliably call to get the latest email address data regardless of a user’s token state?

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

Stuart Colville We added email to the profile-change event. It will be in production with train 222 on Jan 12. https://github.com/mozilla/fxa/blob/main/packages/fxa-event-broker/README.md#profile-change ( https://github.com/mozilla/fxa/blob/main/packages/fxa-event-broker/README.md#profile-change|smart-link )
