### ISSUE TITLE
Update references to `Firefox Accounts` to `Firefox accounts` in content server & settings

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#10693]
This came up in slack, `Firefox Accounts`, `Firefox Account`,`Firefox accounts` should be `Firefox account`.

l10n team says that we can update the existing translations instead of making new ones.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4087)

**Comment by LZoog** [comment]
I'm going to reopen this. #10654 is for the new emails, this task can cover the rest of FxA including login/registration flow and Settings.

If we start this in the next few weeks we should replace old email copy too, but otherwise we can skip the auth server .html files (unless it's easier to just find and replace everything) since the old email templates will be retired.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
