### ISSUE TITLE
Handle Account Deletion for Subscribing Users

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#1071]
* FXA should warn users that they will lose access to any subscriptions they currently use
* FXA should immediately cancel payment as of the current billing cycle for the user
* FXA should tell Stripe to remove all payment information

Account deletion wires can be found here: 

https://mozilla.invisionapp.com/share/K2RBDY3VU9X

**Comment by lmorchard** [comment]
FWIW, I think we have subscription cancellation happening in the backend as part of user deletion. But, the UI for notifying the user of lost access and the new confirmation checkboxes are *not* done yet.

**Comment by lmorchard** [comment]
We discussed this in triage and worked out that literally depending on Relying Parties (#710) could be harder than necessary. (This is what we figured we'd need to do earlier.)

We *do* already track subscription plans for the user. So rather than listing the Relying Parties, we can list just the subscriptions. Those should describe what the user will lose on deletion.

**Comment by lmorchard** [comment]
Ref: https://github.com/mozilla/subhub/issues/61

Need a way to completely delete the customer in subhub while deleting the FxA user

**Comment by philbooth** [comment]
> Need a way to completely delete the customer in subhub while deleting the FxA user

Ref: https://github.com/mozilla/subhub/commit/a675893ea607f08d106b468614c5c44257c70e2d

**Comment by philbooth** [comment]
> Account deletion wires can be found here: 
> 
> https://mozilla.invisionapp.com/share/K2RBDY3VU9X

Maybe I'm holding it wrong, but I don't see anything for account deletion there. I see stuff for cancelling individual subscriptions though. What am I missing?

**Comment by philbooth** [comment]
#1671 is open for a small, backend part of this. Waiting on wireframes for the front-end part though, so taking my face off and adding `needs:ux`.

**Comment by philbooth** [comment]
Correct wireframe link:

https://mozilla.invisionapp.com/share/2MRH9FQHQDT#/screens/358433257_Cover_Page_JC

**Comment by philbooth** [comment]
@LZoog, if you're still hunting for issues to work on, the outstanding portion of this might be an interesting one to take up. A back-end piece landed in #1671, but the UI still needs adding to the settings screen in the content server and there is some API wiring needed to fetch the list of subscriptions too.

Let me know if you're interested and I can walk you through it / answer questions.

**Comment by LZoog** [comment]
Thanks @philbooth, I just scheduled a meeting for us tomorrow to go over this. I'm reassigning this issue to me.

**Comment by philbooth** [comment]
Notes for @LZoog:

* template: `packages/fxa-content-server/app/scripts/templates/settings/delete_account.mustache`
* controller: `packages/fxa-content-server/app/scripts/views/settings/delete_account.js`
* js client: `packages/fxa-content-server/client/FxAccountClient.js`, grep for `getActiveSubscriptions`
* good example view in `app/scripts/views/settings/clients.js`

**Comment by lmorchard** [comment]
Something that occurred to me - the new `getActiveSubscriptions` method probably needs adding [hereabouts in `account.js`](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/models/account.js#L1283).

But, a gotcha is that [the `/oauth/subscriptions/active` auth server resource](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/routes/subscriptions.js#L86) currently only supports an OAuth token for auth - i.e. not a content server `sessionToken`.

So, we probably need to tweak that resource to also accept session tokens. I *think* that was something I had in an earlier draft of those routes, but ironically we removed because there didn't appear to be anything on the content server that needed to access subscriptions data.

**Comment by lmorchard** [comment]
Thought about this some more, and I think getting `getActiveSubscriptions` to work for the account deletion view is going to take a bit of work: https://github.com/mozilla/fxa/issues/1753
