### ISSUE TITLE
Close out the "device registration api" feature description?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#108]
I'd like to start being more deliberate about "closing out" feature development and making sure we reflect on what was or was not achieved. I made a first stab at this over in #105, but let's try it out on a couple more features and see how it feels.

The "device registration api" feature is a good test-case, because as far as waffle and aha are concerned, we shipped it.  So let's take the time to go through the feature description and:

* Check whether there's anything in there that we missed, and need to prioritize
* Add some notes on the outcomes, whether the feature has been successful, etc.
* Move it into "shipped" when we're confident it requires no further attention.

Ideally we could get @philbooth to drive this, but he's about to be PTO for a couple of weeks, so perhaps we can figure it out amongst ourselves @shane-tomlinson and @vladikoff..?

**Comment by philbooth** [comment]
> Add some notes on the outcomes, whether the feature has been successful, etc.

@rfk, I'm struggling with this part a little bit. We know the feature has shipped and, after some early issues were resolved, that users are successfully registering devices. But quantifying success is difficult because I didn't think to log appropriate events that would make the data available in DataDog. In fact I didn't even mention the notion of what a successful outcome might look like in the original feature document. Mea culpa.

So, I think the first step of this should be to log that data in the auth server, then create a device registration dashboard in DataDog. Once that has been running for a while I can put some actual numbers into an `Outcomes` section of the feature doc.

Does that sound like a reasonable plan?

**Comment by rfk** [comment]
> didn't even mention the notion of what a successful outcome might look like in the original feature document

This was one of the first feature docs we ever did, so it's no surprise that we've learned a few things since then :-)

Let's not burn significant resources on post-hoc metrics for this feature. Perhaps we can note the following outcomes from existing data:

* We shipped device-registration in Fx desktop in version X
* We see a ratio of X:Y of logins to device registrations, derived from auth-server HTTP logs in kibana
 
Are there other interesting things we'd like to know about it at this stage?
