### ISSUE TITLE
Implement password check on subscription cancellation

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#1088]
The rough subscription management page merged in PR #961 did not include a password check when cancelling subscription. That will need to be implemented.

https://mozilla.invisionapp.com/share/K2RBDY3VU9X#/screens/361039175

<img width="500" alt="Capture" src="https://user-images.githubusercontent.com/21687/57634195-d1515280-7572-11e9-97b4-e87cb66c369c.PNG">

**Comment by lmorchard** [comment]
Something to think about here: How to implement the actual password check as an API. Would it be secure enough to have an API that checks a password if the API is restricted to the same scope as other subscription management APIs? (i.e. it couldn't be used as a public password scan)

@shane-tomlinson or @bbangert might have some input here?

**Comment by shane-tomlinson** [comment]
It just dawned upon me that asking for the user's password on a subscription service page negates the entire reason we put the subscriptions service on it's own domain - isolating the payment provider from finding out the user's password, sessionToken or Sync key material. A payment provider that goes malicious could slurp up the user's password, which could in turn be used to impersonate the user.

Can we take an alternative approach to asking for the password, perhaps using the delete repository flow from Github as an example. Instead of asking for the user's password, Github asks for the name of the repository being deleted.

<img width="448" alt="Screenshot 2019-05-15 at 08 53 05" src="https://user-images.githubusercontent.com/848085/57758125-e3580000-76ee-11e9-8bff-380b57ba93ad.png">

**Comment by lmorchard** [comment]
Adding the needs:product label, since this looks like we should consider tweaking things product-wise here

**Comment by clouserw** [comment]
@johngruen will review this

**Comment by johngruen** [comment]
Yeah this is fixed in the latest mocks
