### ISSUE TITLE
Volume of activity and flow events from the auth server is down

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#1099]
Starting around May 1st, Redshift datasets from the auth server show reduced event volume. Events from the content server do not. Is there a problem with the import pipeline somewhere?

Some charts showing what I mean:

* https://sql.telemetry.mozilla.org/queries/4794#9733
* https://sql.telemetry.mozilla.org/queries/1215#2252
* https://sql.telemetry.mozilla.org/queries/1133#9901
* https://sql.telemetry.mozilla.org/queries/4775#9694

Amplitude is not affected.

What do we think is going on here?

/cc @jbuck

**Comment by philbooth** [comment]
Fwiw, this situation has got worse. There are now only very tiny numbers of events of each type landing in Redshift:

https://sql.telemetry.mozilla.org/queries/62843#161268

**Comment by jbuck** [comment]
I've asked whd to take a look at the heka aggregator to see if anything fishy is going on there

**Comment by whd** [comment]
I've investigated and this appears to be due to some sort of stall in heka. The logs show nothing, but you can see a dashboard [here](https://app.datadoghq.com/dashboard/kp6-zwr-q95/fxa-heka?from_ts=1555869137431&to_ts=1558461137431&live=true&tile_size=m) which pretty clearly shows network dropping off at the time described. 

After restarting the main heka process things [look like they are working again](https://app.datadoghq.com/dashboard/kp6-zwr-q95/fxa-heka?from_ts=1558447134322&to_ts=1558461534322&live=true&tile_size=m). Unfortunately however, the csv exports are not written to be resilient to this kind of issue and so they are going to drop data from before this week. This system is old enough that I don't have the confidence to attempt to modify it to process the backfilling data live. This means that if you want full and correct exports for this time period we will need to reprocess the data from the log store after the system has caught up. Please file a bug in Data Platform Operations if that's necessary.

**Comment by philbooth** [comment]
> This system is old enough that I don't have the confidence to attempt to modify it to process the backfilling data live. This means that if you want full and correct exports for this time period we will need to reprocess the data from the log store after the system has caught up. Please file a bug in Data Platform Operations if that's necessary.

Thanks @whd, no need for any of that I think, we can tolerate the blip.
