### ISSUE TITLE
Reuse content-server stylesheets in payment server

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#1101]
Right now the payments server has [its own stylesheet](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/index.scss). Ideally it would use the same styles as the content-server, and then as we do brand updates those will be applied consistently across both projects.

Maybe we should copy styles from content-server as part of a payments server build step...?

**Comment by shane-tomlinson** [comment]
> Right now the payments server has its own stylesheet. Ideally it would use the same styles as the content-server.

Copying over seems like a reasonable thing to do.

> then as we do brand updates those will be applied consistently across both projects.

Most brand updates are being applied selectively, only if the user enters FxA with the `?style=trailhead` query parameter. v2 will be to apply it everywhere. 

Entering FxA with `?style=trailhead` will cause the `trailhead` class to be added to the html element and new styles to be used. 

Since subscriptions are by nature trailhead related, perhaps just add the class to the html element and make use of those styles?

Ref https://github.com/mozilla/fxa/pull/1098

**Comment by lmorchard** [comment]
I think I'm going to consider this issue closed - we just merged in code that does in fact reuse the content server styles. Further tweaks can happen as part of follow-ups and implementing specific visuals

https://github.com/mozilla/fxa/pull/1387
