### ISSUE TITLE
"The currency of this subscription is not valid for the country associated with your payment." when trying to subscribe to FxRelay from Germany with a UK card

### ISSUE THREAD

**Issue by harabat** [mozilla/fxa#11055]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

1. Be located in a eurozone country where Firefox Relay is available (tested from Germany and with a VPN that's based in Netherlands)
2. Go to https://relay.firefox.com/ and try to sign up to premium plan
3. Get redirected to https://subscriptions.firefox.com/
4. Try to pay with a UK card (Firefox Relay is available from the UK)
5. Observe error:
```
Error confirming subscription…
The currency of this subscription is not valid for the country associated with your payment.
Try again
```

### Expected result

I should be able to sign up to Firefox Relay from a eurozone country while paying with GBP.

### Actual result

Error: `The currency of this subscription is not valid for the country associated with your payment.`

### Environment

Firefox 94, Linux Manjaro

### Potentially related issues
#10598 #9196

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4213)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

The plans on the Firefox Relay page are determined by geo look-up on that website. IIUC this would fall to that website to fix or have messaging around?

Luke Crouch : Should this bug be moved to the Relay repo (also: what is the Relay repo for future reference?)?

**Comment by biancadanforth** [comment]
Thanks for filing this issue. I am not sure if this is expected behavior or not, but the plans that are displayed and what countries/currencies are eligible for them are determined by the product page currently. If you think you hit an error, can you file this issue in that product's repo? https://github.com/mozilla/fx-private-relay

Arguably, long term it may make sense to move this determination to the subscription platform/fxa, but that's not where it lives now.

**Comment by data-sync-user** [comment]
➤ Valentina Virlics commented:

This is a known issue, at least for the VPN product, and I think has the same root cause. See https://mozilla-hub.atlassian.net/browse/FXA-3375 ( https://mozilla-hub.atlassian.net/browse/FXA-3375|smart-link ) . The VPN issue is tracked on this repo.

Bianca Danforth  ^

Thanks!
