### ISSUE TITLE
The "Firefox accounts" text is missing from the Manage Account page

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla/fxa#1108]
Environment:
Build: Stage [Train 137];
Devices: Android;

Prerequisites:
You are logged in with a Firefox account.

Steps to reproduce:

1. Go to Manage Account;
2. Observe the Firefox logo;

Expected results:
The "Firefox accounts" text should appear, on top of the page, next to the Firefox logo.

Actual results:
The "Firefox accounts" text is missing from the Manage Account page.

Notes:
Stage: 
![stage](https://user-images.githubusercontent.com/48799384/57775998-0ef6dc80-7727-11e9-9cb2-756774e021cb.png)

Production: 
![production](https://user-images.githubusercontent.com/48799384/57776016-21711600-7727-11e9-8f1c-450683f5c798.png)

**Comment by SorinaFlorean** [comment]
This is also reproducible on iOS.

**Comment by shane-tomlinson** [comment]
This is [by design](https://github.com/mozilla/fxa/blob/9ca5c4057cde5da1e2866cb9515e88bb18e5fb2b/packages/fxa-content-server/app/styles/modules/_settings.scss#L92) and was added by @johngruen in https://github.com/mozilla/fxa/commit/5c6d094a143d7892dca7d8dff0f695555bd4d845#diff-378f176a7adb1b8a57ae8ddf5de64d1eR85.
