### ISSUE TITLE
Update Bento Menu tests and alt text in fxa-settings

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11136]
Update `BentoMenu` component in `fxa-settings` to include `alt` text for icons that should also get localized, and increase component's test coverage.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4259)

**Comment by tobirix** [comment]
Hello together,
I would really like to make this change.
Because I am new to Open-Source I am kindly asking if I understand the problem correctly.
The problem just regards the [index.tsx](https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/components/BentoMenu/index.tsx) file right? So I just need to add e.g. in this [line](https://github.com/mozilla/fxa/blob/a36b8b03dc7ee59f2ac48e2f7ed61532947fcf77/packages/fxa-settings/src/components/BentoMenu/index.tsx#L61) `firefoxicon` to the `alt` attribute right?

Thanks in advance :)

**Comment by LZoog** [comment]
Hi @tobirix, sorry it's taken me a few days to get back to you.

That is the correct `index.tsx` file. Regarding your questions, let's see (this explanation is just as much for me as it is for you to help lay it all out!)...

<img width="338" alt="image" src="https://user-images.githubusercontent.com/13018240/144106209-419aba1c-39e6-4b56-9296-9ef7b987c373.png">

A good thing to know with screen readers is that we don't want redundant pieces of information one after the other. Screen readers automatically read "image" when they encounter an image so I don't think we necessarily need the word "icon" here, but actually, the closer I've looked at this, the more I think that any `alt` text we add here will be redundant. If we take the first icon, Firefox Monitor for example, and add `alt="Firefox Monitor"`, screenreaders are going to be read something like "link, Firefox Monitor, image, Firefox Monitor". I double checked [WebAIM](https://webaim.org/techniques/alttext/) and they state alt text can be "within visible body text near the image".

I think instead of `alt` text on each of these (which would need to be wrapped in `<Localized>` tags for localization), we should simply add `aria-hidden="true"` on the images, maybe with a comment above the first one to note we're hiding them from screen readers to prevent redundancy. That way, screen readers will just be read the text.

This ticket also asks for the associated test file to have increased coverage. I think if we just check that existing elements are indeed rendered on the screen (each of the links), heading text, and heading image, that'll be great. We have a lot of examples of how to do this if you search our test files for `.toBeInTheDocument()`. I can assign you if you're still interested in working on this, thank you! 🙂

**Comment by tobirix** [comment]
Hi @LZoog I´m still in!
At least I know what to do, would like to be assigned if that's still fine 🙂
Thank you.

**Comment by LZoog** [comment]
@tobirix sure thing, thanks! 😁

**Comment by tobirix** [comment]
@LZoog thank you for the chance to get into Open-Source 🙂
I will do it like you mentioned with the test coverage, thanks!

**Comment by tobirix** [comment]
@LZoog without doing any changes I already had 100% of covered lines (see screenshot attached), so I guess I can't get it higher 🙈😃. 
<img width="692" alt="Bildschirmfoto 2021-12-05 um 21 48 59" src="https://user-images.githubusercontent.com/33509477/144763705-0a3cbc1c-c39b-4581-a856-8b7a4f174aa9.png">

I'm still adding the test cases for the rendering of

> links, heading text, and heading image

like you mentioned or should I not add them?
I wish you a nice Sunday or a nice start into the week on Monday 🙂

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
