### ISSUE TITLE
Write (very small) ADR for squash & merge pros/cons

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#11721]
We’ve had squash & merge in place for a few months now, which is oftentimes nice, but if we forget to use it when we should then it can cause a less clean commit history/changlog and can make cherry-picking for dot releases more challenging. Let’s document the pros and cons on the decision and make sure we decide as a team what we prefer.

Note: I (Lauren) created this issue and am assigning it to myself. It’s possible once we start listing out the pros/cons and after some discussion I might be for squash and merge, but at the time of writing I’ve seen it cause a couple of problems and I personally prefer a rebase with commit message edit and force push.

I’m estimating this at a 2 since the writing task is small, but it might be a 3 if this generates a lot of discussion.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4476)

**Comment by LZoog** [comment]
Something to note, in case someone else picks this up:

Github shows whatever was used last - squash and merge, or regular merge - and it's easy to accidentally choose one when you mean to choose the other.

We ran into a problem with a merge conflict in the 226.4 `train-226` -> `main` PR because the 226.3 `train-226` -> `main` PR was accidentally squashed & merged.

I've also seen where we _meant_ to squash & merge a PR after approval to modify the commit messages, but it was accidentally merged normally. This makes git blame history hairier when trying to figure out why a change was made since the commit shown won't follow our commit format and the changes are similarly hairy in our changelogs.

I know there was also at least one case where I was release owner and I tried to cherry-pick in a commit that I thought was on `main` but actually, I needed to cherry-pick in the merge commit because the original commit didn't make it into the repo. This was a few months ago though and I'm actually not as sure if that was squash & merge related as my previous two points.
