### ISSUE TITLE
Primary email address missing from database

### ISSUE THREAD

**Issue by ndren** [mozilla/fxa#11894]
When I asked for my GDPR rights to data access be fulfilled by contacting the Mozilla Privacy Team, they have checked multiple times and could not find my _active_ primary email address anywhere on their list of accounts and account data. I strongly suspect this is because the email used to create this account is different to the one that is being used now. I do not have access to the old email to confirm this however. Please take a look into this because this is infringing on legal rights of data subjects.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4586)

**Comment by clouserw** [comment]
Hi.  Do you have a [bugzilla](https://bugzilla.mozilla.org/home) account?  If you file a ticket there we can mark it confidential and you can put in your email addresses so we can look them up.  

If you don't have an account, I can file one for you, but you won't be able to see it since it will be confidential.

Thanks

**Comment by clouserw** [comment]
Hi.  I'm following up here again - I can't look up your account unless you can provide me the email addresses associated with it.  Please file a confidential bugzilla bug or email me at wclouser at mozilla and I can help file one for you.  Thanks.

**Comment by clouserw** [comment]
I haven't heard back so am closing this.
