### ISSUE TITLE
Trailhead: CWTS continue button is below the fold on mobile

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1201]
Look how far down that button is. There is no way that shows on the screen on mobile.

<img width="345" alt="Screenshot 2019-05-22 at 12 04 50" src="https://user-images.githubusercontent.com/848085/58169898-e40e0a80-7c89-11e9-9432-8747348ad0ce.png">

Setting the Fx Dev tools to a Galaxy S9, here's what we see:

<img width="358" alt="Screenshot 2019-05-22 at 12 06 30" src="https://user-images.githubusercontent.com/848085/58169975-191a5d00-7c8a-11e9-9ac2-77aff8362f34.png">

This is going to lead to fewer people clicking "continue" on this screen on mobile.

cc @ryanfeeley, @davismtl

**Comment by davismtl** [comment]
could the continue button float?

**Comment by davismtl** [comment]
@shane-tomlinson This flow should also only be triggered where style=trailhead . 

Mobile is not supposed to use that. We are scheduled to figure mobile out after.

**Comment by shane-tomlinson** [comment]
This may no longer be an issue since those email opt-in checkboxes were moved back to the signup page.

**Comment by shane-tomlinson** [comment]
I do not believe this is a problem anymore since we moved the checkboxes.

![Screenshot 2019-05-29 at 12.24.15.png](https://images.zenhubusercontent.com/5c9e44f8850e6a34fc6eeffc/6d202a33-c432-461f-8f51-8c6b815d5910)

**Comment by davismtl** [comment]
We moved them but there is a good chance that we will need to move them back as we resolve the API issue we had that prevented them from being on this page.

Let's keep this open but change to a P3 just so that we track this issue if we move back to the prior design.

**Comment by clouserw** [comment]
As we fix mobile pages, let's just make sure they look alright at a mobile resolution.  Danny -- once you land the designs, please verify and then close this bug.

**Comment by ryanfeeley** [comment]
@dannycoates I'd love to see this in two columns as well. I think it would fit because here is how it would look on my iPhone SE.
![choose](https://user-images.githubusercontent.com/68213/59053380-5886a300-885f-11e9-9705-a654f0600b21.gif)

The only problem is that text wraps like this:
![image](https://user-images.githubusercontent.com/68213/59053420-69cfaf80-885f-11e9-8000-5af78fc2def3.png)

Ideally it can wrap like this (24px over):
![image](https://user-images.githubusercontent.com/68213/59053484-8d92f580-885f-11e9-8287-c9a0b5c19e81.png)
