### ISSUE TITLE
"Revoke" from Devices&apps section doesn't cause immediate signout from RP

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#1203]
**Environment**
Production server
Android, Win10 x64

**Prerequisites:**
Sign in on https://monitor.firefox.com/ and https://addons.mozilla.org/en-US/firefox/ with a Firefox account.

**Steps to reproduce:**
1. Go to Manage account -> Devices & apps section;
2. Tap on "Revoke" button for Monitor and Add-ons apps listed;
3.  Refresh the pages from prerequisites (https://monitor.firefox.com/ and https://addons.mozilla.org/en-US/firefox/)

**Expected results**:  the user is logged out.

**Actual results**: the user is logged in. 

Notes: not reproducible when we disconnect another device.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-98)
┆Issue Number: FXA-98

**Comment by shane-tomlinson** [comment]
This is due to independent session handling on Monitor and AMO. FxA is not a true SSO solution. What happens when the user signs into FxA for AMO or Monitor is once the user completes the login on FxA, those services create their own local session. They occasionally check whether the credentials they were given from FxA are still valid, through this only occurs periodically.

Fixing this requires either:
1. Notify the RP whenever the token was destroyed
2. The RP needs to check with FxA on every page load whether their OAuth creds are still valid

I prefer the first, and I think there is a bug open about it already. Will check later.

**Comment by shane-tomlinson** [comment]
Udpated the title to better reflect what happens. It "works" in as much as clicking "Revoke" revokes the OAuth credentials, but does not match user expectations that the action does not cause a logout on the RP.

**Comment by MeridelW** [comment]
I am working on copy for the FxA Settings redesign. I just tested 'revoking' Monitor from my list of devices & apps, and it did in fact sign me out of Monitor. I tested it several times. Has this issue thus been fixed?
