### ISSUE TITLE
Add 20px spacing between logo and illustration

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1218]
UX team request to give more space between the new master brand and the illustration.

PROPOSED
<img width="568" alt="image" src="https://user-images.githubusercontent.com/68213/58203914-2c88f080-7ca9-11e9-823e-f4e5e1d3d5ee.png">

**Comment by shane-tomlinson** [comment]
@ryanfeeley Does this apply to all pages without the progress indicator?

**Comment by ryanfeeley** [comment]
@shane-tomlinson yes

**Comment by LZoog** [comment]
@ryanfeeley are you wanting more space between only _images_ and the master logo, or just more space for the logo in general? We currently have the container `padding-top` set to `50px`, here's what that looks like on a few different screens:
<img width="300px" alt="image" src="https://user-images.githubusercontent.com/13018240/66501949-fd252580-ea89-11e9-8725-ecb4ca1ba48b.png">
<img width="300px" alt="image" src="https://user-images.githubusercontent.com/13018240/66502482-ed5a1100-ea8a-11e9-92b5-71d7c7bc3939.png">
<img width="300px" alt="image" src="https://user-images.githubusercontent.com/13018240/66503241-82113e80-ea8c-11e9-9ae8-d5e65e1991b2.png">

And this is what it looks like with `70px`:
<img width="300px" alt="image" src="https://user-images.githubusercontent.com/13018240/66501970-0b734180-ea8a-11e9-9bdd-4b6b453f4444.png">
<img width="300px" alt="image" src="https://user-images.githubusercontent.com/13018240/66502499-f5b24c00-ea8a-11e9-820e-df7e68a50a56.png">
<img width="300px" alt="image" src="https://user-images.githubusercontent.com/13018240/66502673-6194b480-ea8b-11e9-8933-0b3779cf5a04.png">

I personally think increasing that container top padding to `70px` across the board looks better, but can otherwise add 20px above each image individually, but I would need to know which others, if any, you'd like included in the fix.

(BTW, the last one looks like a bigger difference because we have some extra whitespace in the sync SVG - if this should be addressed, we should create a new issue)
<img width="343" alt="image" src="https://user-images.githubusercontent.com/13018240/66502997-ff887f00-ea8b-11e9-920d-70b2019a5793.png">

**Comment by ryanfeeley** [comment]
@LZoog 70px! Though a vertically rhythmic grid system is underway. I'm voting for a 20px baseline but branding side needs their say.

**Comment by LZoog** [comment]
Fixed by #3268
