### ISSUE TITLE
MDN Plus upgrade email sent to me in Hungarian

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12238]
## Description

Bought a $5/mo subscription to MDN this morning on production with my LDAP email and personal credit card (hold for applause)
Shortly after, I upgraded to an annual subscription at $50/yr.
When the email came in, I noticed that Gmail seemingly flagged the email as Hungarian.

### Steps to reproduce

1. Buy a $5/mo subscription to MDN Plus.
2. Upgrade your subscription to $50/yr.

### Expected result

English emails

### Actual result

Hungarian email?

![Screen Shot 2022-03-24 at 3 18 40 PM](https://user-images.githubusercontent.com/557895/160019821-92fbd773-c1d1-4d2e-acd5-2971a2dde628.png)

### Environment

macOS 12.2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4754)

**Comment by pdehaan** [comment]
email subject was:
"Frissített erre: MDN Plus (Updated to MDN Plus)"

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Lisa Chan is this a translation issue or a code issue?

**Comment by LZoog** [comment]
@pdehaan I think this is going to be fixed in #12390. Dan found a bug where we weren't taking `q` into account, which you can see on the "accept-language" header, and I wonder if we grabbed Hungarian from your preferences but didn't respect English being the priority choice (which would have a higher q value). Since you found this in production, I'll ask that QA (maybe you if you've got time!) verifies this is fixed on 4/20 or later, which is when the train that'll land on should be in prod.

**Comment by data-sync-user** [comment]
➤ Lisa Chan commented:

Hi Peter deHaan ! Per Lauren’s comment, we believe the fix for this is currently in staging (https://mozilla-hub.atlassian.net/browse/FXA-4729 ( https://mozilla-hub.atlassian.net/browse/FXA-4729|smart-link ) ). When you have a moment, can you please verify whether we are still seeing this issue, as the Support team reported in Matrix that another user received an email in Korean ( https://support.mozilla.org/en-US/questions/1374274 )? Thank you!

**Comment by pdehaan** [comment]
FWIW, I ran through a bunch of flows the other day and was unable to reproduce this, so I think we're fine.
Although it would be interesting to dig deeper into that Korean thread and see what their accept languages were and which strings are currently translated in Pontoon or fxa-content-server-l10n.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Peter ran through the flows again and saw all English emails, so it appears fixed as we suspected, and we’re going to close this for now. We can file an issue later or re-open this if it comes up again.
