### ISSUE TITLE
Bugzilla 1762654

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#12349]
https://bugzilla.mozilla.org/show_bug.cgi?id=1762654

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-4793)

**Comment by data-sync-user** [comment]
➤ Bianca Danforth commented:

I’m not sure which team should triage this, since it affects packages used by both teams.

Wil Clouser or Anna Sobiepanek , would you have thoughts on the best way to triage this work (and others like it) between the two different teams/triage owners/triage processes?

E.g. perhaps this ticket should go to whichever team has capacity to fix it first?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This should be 3 different issues and we should process it through our normal maintenance triage.  For shared libraries we don’t have a set rule - it’ll likely be splitting them up or looking at capacity, yes.  The first step here should be an analysis of severity.  I’ll coordinate with Anna.
