### ISSUE TITLE
(Trailhead) Move Product List to the right of the registration form

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#1241]
Context:
Yesterday it was determined that the newsletters needed to be moved to the first screen of registration flow due to API limitations (among other things).

Yesterday night, it was proposed to just make a very long layout but there are usability problems there so UX proposed the following layout this morning.

![Screen Shot 2019-05-23 at 10 22 38 AM](https://user-images.githubusercontent.com/19537086/58273159-f0a36900-7d44-11e9-9aca-8f75b88be702.png)

Acknowledgment, the password strength bubble will hide the product list. We believe that this is OK since people will not be reading about products while picking a password.

CC @shane-tomlinson @ryanfeeley

**Comment by pwalm** [comment]
On thing to call out, since these screens are 95% just the same bits just moved around:
The header of the "Get more..." section sits on the same horizontal baseline of certain elements in the form block.
* On the screen on the left, the baseline is the top of the first form field:
<img width="1248" alt="Screen Shot 2019-05-23 at 11 15 51 AM" src="https://user-images.githubusercontent.com/6797635/58276392-2f88ed00-7d4c-11e9-9335-288ae3cf0d3d.png">
* On the screen on the right, the baseline is the pre-populated email address:
<img width="1244" alt="Screen Shot 2019-05-23 at 11 16 05 AM" src="https://user-images.githubusercontent.com/6797635/58276426-462f4400-7d4c-11e9-8193-c6544e68e49b.png">

**Comment by dannycoates** [comment]
oof, this actually moves a lot of stuff around with how our templates are scoped. the problem is being inside the rounded box. something like this would be much easier:

<img width="859" alt="Screen Shot 2019-05-23 at 1 45 38 PM" src="https://user-images.githubusercontent.com/87619/58285297-51d93580-7d61-11e9-81ba-4c23dffa56f4.png">

can you throw me a bone? 🦴

**Comment by pwalm** [comment]
Yep, that works for me @dannycoates
