### ISSUE TITLE
Mismatched ACR unhandled exception

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12625]
Sentry bug:

[https://sentry.io/organizations/mozilla/issues/3188735357/?environment=prod&project=6231056&query=is%3Aunresolved&statsPeriod=90d](https://sentry.io/organizations/mozilla/issues/3188735357/?environment=prod&project=6231056&query=is%3Aunresolved&statsPeriod=90d)

This is likely due to [https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/routes/oauth/authorization.js#L338](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/routes/oauth/authorization.js#L338|smart-link)  which runs the authorization handler in the traceback here, but does not guarantee that the promise will be returned as one of the other functions in there can fail. It should be await’d, or have an error handler attached.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4951)

**Comment by pdehaan** [comment]
I wonder if something like https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md would catch issues like this.
Although probably not in this _exact_ case since this is a .js file and the rule seems typescript-eslint parser specific.
