### ISSUE TITLE
Add a11y linter for React packages/components

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa#12748]
## Description

I was starting to look into a11y and what tools/linters we're currently using and wasn't seeing anything obvious.

### Steps to reproduce

I was trying to see if we were using [eslint-plugin-jsx-a11y](https://www.npmjs.com/package/eslint-plugin-jsx-a11y) package (which might be the easiest starting point for [automatically] linting for accessibility issues; other options include Google Lighthouse or Deque's axe tools/add-ons). 

```sh
git grep "eslint-plugin-jsx-a11y" packages
# no results
```

But, if I grep for packages that use "react", I see the following list:

```sh
git grep '"react"' packages/**/package.json | cat

packages/fxa-admin-panel/package.json:    "react": "^16.13.0",
packages/fxa-content-server/package.json:    "react": "^16.8.6",
packages/fxa-payments-server/package.json:    "react": "^16.12.0",
packages/fxa-react/package.json:    "react": "^16.13.1",
packages/fxa-settings/package.json:    "react": "^16.13.1",
```

(Unrelated, but also interesting is that this is seemingly pointing to several different versions of React. I would have thought Dependabot would have kept these in sync, although maybe thats what the pending https://github.com/mozilla/fxa/pull/12736 is doing)

### Expected result

Make sure we have some a11y linter(s). Not sure if reasonable first steps are add to select packages above, and then see if we can slowly migrate into eslint-plugin-fxa as an optional ruleset/config so ESLint configs can extend "fxa/recommended" and "fxa/react" from https://github.com/mozilla/eslint-plugin-fxa/tree/master/lib/configs).

### Actual result

No results for "eslint-plugin-jsx-a11y" directly, although searching GitHub issues returned these results, which curiously all reported the package under "Missing dependencies" (although there are a few misleading results in there):

- https://github.com/mozilla/fxa/issues/12713
- https://github.com/mozilla/fxa/issues/12720
- https://github.com/mozilla/fxa/issues/12723

Also interesting was https://github.com/mozilla/fxa/issues/3978 which looks like we might have considered adding accessibility checks in the past, but then decided against. 🤷 

### Environment

What browser and operating system are you using?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5031)

**Comment by pdehaan** [comment]
Somebody also pointed me to https://www.deque.com/axe/core-documentation/api-documentation/ which I'm hoping to see if I can get working w/ Storybook.

**Comment by LZoog** [comment]
We had this opened before with #3978 and closed it [with this comment](https://github.com/mozilla/fxa/issues/3978#issuecomment-585421875).

Since we've added new team members and I closed it more than two years ago, I'm open to discussing if we want this. At that time at least, this only outputs warnings in the console if you bother checking for them.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

I don’t have an opinion on tools to use, but in the triage I said I would see about setting up eslint on Github Actions which would be a precursor to this.  You can see that PR @ https://github.com/mozilla/fxa/pull/12811 ( https://github.com/mozilla/fxa/pull/12811|smart-link )  and looking for review/feedback.  If that lands, I’ll probably unassign this from me since I don’t know what good a11y tools are.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
