### ISSUE TITLE
[fxa-event-broker] Notify RPs using Security Event Tokens or signed JWTs

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1288]
After reviewing @bbangert's [event-broker PR](https://github.com/mozilla/fxa/pull/1261) it occurred to me that we should send events to RPs in a way that ensure the messages came from us. 

I can imagine either:

* Using a per RP shared secret to authenticate the request
* Signing the payload to allow the issuer to be verified

The first seems like it could get be a maintenance headache, we'd have to keep a a list of shared secrets, one per RP, and keeping lists of secrets is always a bit worrying.
The second could be done using the signing key we use to sign certificates, or sign the upcoming [JWT access tokens](https://github.com/mozilla/fxa/pull/933). Plus, [there is an IETF spec for Security Event Tokens](https://tools.ietf.org/html/rfc8417) that might fit the bill. One key (well, one key pair in reality), and the RP could verify themselves whether the payload is legit and from us.

cc @bbangert

**Comment by bbangert** [comment]
Google Pub/Sub signs their Push requests with a JWT. Since we can't use that to send to external parties though (they have to be Moz properties for GCP Push Subs), the event-broker is going to proxy the call, and re-sign the request per #1269.

That does bring up the question you cited though, do we have a JWT signing system in FxA?

**Comment by bbangert** [comment]
Duplicate of #1269. We should continue the discussion there on what JWT scheme to use.
