### ISSUE TITLE
Fix "Add-ons" functional test

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12955]
In [https://github.com/mozilla/fxa/pull/12618](https://github.com/mozilla/fxa/pull/12618|smart-link)  I added a URL to the AMO row on our settings page.  It looks like this is [breaking our production smoke tests](https://app.circleci.com/pipelines/github/mozilla/fxa/30409/workflows/ef63f578-bd16-4651-bafd-dd99dc919cd3/jobs/334954):

!image-20220519-212254.png|width=761,height=316!

I looked for something like toContainMatch() but it doesn’t exist and I’m not sure the simplest/best way to match the new string

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5130)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24063">image-20220519-212254.png</a>

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Ankita Shrivastava do you have a recommendation?

**Comment by pdehaan** [comment]
Reminder: @ashrivastava-qa is on PTO.

Per https://github.com/mozilla/fxa/blob/b384492fdcc0d7538dee78e70fecc3b9350e0b54/packages/functional-tests/tests/signin/relyingParties.spec.ts#L69-L71

I'm confused by the error message. It seems like the service `name` isn't "Add-ons" but is instead "Add-ons\nOpens in new window" (with a linebreak?)

```
Expected value: "Add-ons"
Received array: ["Firefox 97, Linux", "Add-ons
Opens in new window", "playwright"]
```

But the only immediately obvious instance of that string I found was https://github.com/mozilla/fxa/blob/d1283314c15d81a85f08dcba5bce329db7c6fd51/packages/fxa-react/components/LinkExternal/index.tsx#L33

Not sure if we perhaps changed from a regular link to `<LinkExternal>` recently, and if so, why that'd be including a screenreader-only string in the label. Where [`.toContainEqual()`](https://jestjs.io/docs/expect#tocontainequalitem) can't match now because it's trying to compare these two values, which won't happen:

```
Add-ons
```

vs

```
Add-ons
Opens in new window
```

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Sounds like this was fixed on a train branch but not merged back so this will probably just be a matter of merging that branch back and this will get fixed for free.  

https://github.com/mozilla/fxa/pull/12766 ( https://github.com/mozilla/fxa/pull/12766|smart-link )
