### ISSUE TITLE
[l10n] [MDN]  PN and ToS not translated in the user language

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13094]
**Affected FxA versions:**

* 1.233.1;

**Prerequisites:**

* Have the system language / browser language set to one of the EU supported languages (e.g. Eesti);
* Be in one of the EU countries where MDN plus is available (e.g. Estonia);
* Be on Set up your subscription page; 

**Steps to reproduce:**

1. Click on the “Terms of Service” link from the Firefox Accounts section, placed on the bottom of the page;
1. Observe the Firefox Terms of Service page;
1. Click on the “Privacy Notice” link from the Firefox Accounts section, placed on the bottom of the page;
1. Observe the Firefox Privacy Notice page;

**Expected result:**

* For step 2: The Firefox Terms of Service page is displayed in the user language;
* For step 4: The Firefox Privacy Notice page is displayed in the user language;

**Actual result:**

* For step 2: The Firefox Terms of Service page is displayed English, regardless of the user language;
* For step 4: The Firefox Privacy Notice page is displayed in English, regardless of the user language;

**Notes:**

* Reproducible for other locales as well (Turkish, Latvian, Lithuanian, Portuguese, Slovak, Slovenian);
* Not reproducible for Greek, French locales;
* Reproducible for Subscription confirmation page as well;

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5220)

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Hermina Condei Florian Dieminger files can be double checked here https://github.com/mozilla/fxa/pull/13104/files#diff-2474ce5236316e56e1c39ae5c3cc3d432ca1701e2f7b08c0b958860a274ea5c2 ( https://github.com/mozilla/fxa/pull/13104/files#diff-2474ce5236316e56e1c39ae5c3cc3d432ca1701e2f7b08c0b958860a274ea5c2|smart-link ) . Are we still doing another round of translations?

**Comment by flodolo** [comment]
As far as I can tell, this is not a valid issue. 

We're now limiting the translation of legal documents to 13 locales (covering the top 15 Firefox locales), because maintaining different sets of locales for different documents doesn't really scale.

If MDN should follow a different strategy is a conversation to have with legal (feldman).

**Comment by flodolo** [comment]
This issue is about Firefox Accounts PN and TOS, i.e.
https://accounts.firefox.com/legal/terms
https://accounts.firefox.com/legal/privacy

The commits in the comment above is for MDN legal docs, which is another issue (#13093), and also uses a different system (PDF import vs conversion to HTML).

Both MDN docs are only available in 7 locales: de, en, es-ES, fr, it, ms, nl.

Firefox Cloud Services TOS is available in 13: de, en, es-ES, fr, id, it, ja, nl, pl, pt-BR, ru, tr, zh-CN
Firefox PN is available in 14: cs, de, en, es-ES, fr, hu, id, it, ja, nl, pl, pt-BR, ru, zh-CN

Firefox Cloud Services hasn't been updated after we decided to localize only a consistent set of locales, that's why it has one extra locale (tr) and two missing (cs, hu).

P.S. at risk of nitpicking, country ≠ locale. I understand countries are probably more relevant for the market conversation, but in terms of localization locale is what matters, so it might create less confusion if we don't mix the two.

**Comment by data-sync-user** [comment]
➤ Anna Sobiepanek commented:

Re-opening so i can run the script again once the new localized files are in.

**Comment by data-sync-user** [comment]
➤ Michael Feldman commented:

I don’t think I’m fully following. We should make sure MDN Plus and FxA docs are localized in the top 13 languages where MDN Plus is available. 

Are we missing any coverage in that overlap? (Where MDN Plus is available and one of the top 13 languages is the main language in that country?)

**Comment by flodolo** [comment]
For MDN we're missing a lot of locales, AFAIK we only localized them once in February ([request here](https://mozilla-hub.atlassian.net/browse/L10NV-16)). Since it wasn't updated after the decision to cover the top 15 FIrefox locales, we haven't changed that.

To fully cover the top 15 locales, we'd need to add:
* Firefox Cloud Services: cs, hu. (that's going to happen anyway, the first time we update the doc)
* MDN PN and TOS: cs, hu, id, ja, pl, pt-BR, ru, zh-CN (and we should drop `ms`)

MDN is not available in a lot of the countries covered by those languages, so technically we're already covering the intersection of "top 15" and "MDN Plus locales".

**Comment by data-sync-user** [comment]
➤ Hermina Condei commented:

Michael Feldman I cannot speak for FxA localisation, I actually don’t know who’s responsible for doing what on the FxA side, but I can confirm that for MDN Plus, the situation is as follows:

After the April 28th launch in Europe, that Francesco Lodolo is referring to when he mentions https://mozilla-hub.atlassian.net/browse/L10NV-16 ( https://mozilla-hub.atlassian.net/browse/L10NV-16|smart-link ) , we are now trying to expand with the paid product in 8 new locales: el, et, lt, lv, pt-PT, sk, sl, tr. This is what we need localization for of ToS and Privacy notice. 

Francesco Lodolo , MDN Plus is offered in EN only, and unless I miss something, I am not sure that the locales we cover for on MDN Web Docs (so the free content) that you mention below matter at all in this context.

**Comment by data-sync-user** [comment]
➤ Michael Feldman commented:

I don’t want to change the locales/langauges we’re localizing the Firefox or Firefox Accounts documents into. We should stay consistent with the top locales. 

If the MDN Plus documentation is missing languages that we’re offering MDN Plus in, then we should fix that, up to the top 15 locales. 

Hermina Condei - could you help clarify? Are you asking for localization of the FxA documentation or the MDN Plus documentation? Would this be easier to get on the same page about in a meeting?

**Comment by data-sync-user** [comment]
➤ Michael Feldman commented:

Hermina Condei and I talked. I filed the following Jira ticket for legal doc localization. 
https://mozilla-hub.atlassian.net/browse/L10NV-46 ( https://mozilla-hub.atlassian.net/browse/L10NV-46|smart-link )

**Comment by data-sync-user** [comment]
➤ Peiying Mo commented:

Hermina Condei Michael Feldman Fx PN  is localized in 13 locales (not 15): https://github.com/mozilla/legal-docs/blob/57696c7e264903893668c30e0832c1080b198026/.github/stats.json#L193 ( https://github.com/mozilla/legal-docs/blob/57696c7e264903893668c30e0832c1080b198026/.github/stats.json#L193|smart-link ).  Should we drop ms and stick to  these 13 locales?

**Comment by flodolo** [comment]
Top 15 locales of Firefox maps to 13 localizations (we translate es-ES, but there are also es-AR and es-MX in the top 15)
https://github.com/mozilla/legal-docs/issues/1733

**Comment by data-sync-user** [comment]
➤ Peiying Mo commented:

Data Sync our  legal doc in es-ES serves all the Spanish locales/markets, so we have  just one Spanish version. Michael Feldman Thank you for  confirming. We will proceed with 13 locales + ms.

**Comment by data-sync-user** [comment]
➤ Peiying Mo commented:

Bianca Hidecuti This is correct. Firefox for desktop and mobile is localized in many more languages, we only localize the legal docs in more than a dozen languages for Firefox.

**Comment by data-sync-user** [comment]
➤ Bianca Hidecuti commented:

Peiying Mo , thank you for confirming. 

Giving the fact that for the ID locale, the Firefox ToS and PN pages are not localised, as mentioned in the previous comment, should we reopen this issue or file a new one? Thank you.
