### ISSUE TITLE
Update our email footers with most recent legal recommendations

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#1327]
Legal would like us to align our footers with marketing's. Here is a document with the footer recommendations they've made for each type of email being sent:

https://docs.google.com/document/d/1Ozh7ZZC0jL8doz3BKT583_8oi7iVmHeAdZ9qLIg_Vg8/edit?ts=5cedc017

**Comment by clouserw** [comment]
@dannycoates started this at https://github.com/mozilla/fxa/pull/1325

**Comment by davismtl** [comment]
Somehow I can't see those commits. Are we doing as directed in that doc? I didn't see where they were getting the recommended changes from.

**Comment by clouserw** [comment]
Yes, it was based off of https://bugzilla.mozilla.org/show_bug.cgi?id=1555063 but this is more comprehensive so I'll close that bug for this one.  Thanks for clarifying this and linking the doc.

Danny's patch is good, but we didn't figure out how to update the text files and there may be other adjustments in your doc.  Since this is a P2 we won't mess with it for trailhead.
