### ISSUE TITLE
iOS Account Management: allow sumo link navigation

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/fxa#1369]
The iOS app can provide back functionality if the page has navigated from the root view. EDIT: just see the demo at the bottom with SUMO links opening a new window.
~~If the SUMO urls are just regular links (non blank target please) they can be navigated and the client can show a back button in the navigation bar.~~ They hrefs need a target set,so they open a new window.

When ready to land, please coordinate with iOS team on the rollout so we can make sure the app version in release has support for this. Thanks.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-115)
┆Issue Number: FXA-115

**Comment by shane-tomlinson** [comment]
> If the SUMO urls are just regular links (non blank target please) they can be navigated and the client can show a back button in the navigation bar.

What happens once the user lands on SUMO, can SUMO link out to another site and the user becomes lost?

**Comment by garvankeeley** [comment]
Not sure what you mean by lost. The native back button can travel all the way up the history stack, so back will always return to the root page.

**Comment by shane-tomlinson** [comment]
> Not sure what you mean by lost. The native back button can travel all the way up the history stack, so back will always return to the root page.

This scheme worries me from a couple perspectives. 

Most importantly, FxA is not guaranteed to handle re-entries in a well-defined manner. This is why we open external links in new tabs in all browsers except Firefox for iOS.

For example, this sequence will act in a manner the user does not expect:

* User attempts to sign in to FxA, their email bounces. They are sent to the email bounced screen.
* User clicks the SUMO link which causes Fx for iOS to unload FxA to open the SUMO page.
* User clicks the back button, FxA does not persist state that allows the email bounced screen to know the previous email that bounced. In fact, it has no idea a signin was in progress, and sends the user back to the /signin page so the user can sign in again.

The next concern is around the functionality of the new Back button. It seems like there is a large potential for confusing UI. Is that button always there? Are there particular conditions that cause the button to appear? Are their conditions that make the button go away? Is there a better way to approach a standalone Back button? For example, opening FxA within a normal tab like the other versions of Firefox would allow users to use the full capabilities of the browser instead of a small subset added via this button. The original reason FxA was opened within a special WebView is because Fx for iOS does not support the [WebChannel API](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/WebChannel.jsm), an abstraction that allows for safe communication between the browser and trusted web content. Instead we have to communicate via postMessage, and there are some difficulties doing so.

cc @st3fan, @ryanfeeley

**Comment by garvankeeley** [comment]
> Most importantly, FxA is not guaranteed to handle re-entries in a well-defined manner. This is why we open external links in new tabs in all browsers except Firefox for iOS.

In that case another consideration is to open a new tab with the sumo links, and the tab will overlay the FxA webview that has the FxA content. Again, this would have an upper nav controller back button that in this case would close the tab. 
That approach would be seamless and allow the user to access help content. 

> Is that button always there?

I have a demo that better illustrates this, but the idea would be that nav controller back would only be there when navigating back to the FxA content.

> Are there particular conditions that cause the button to appear?

(1) Depending on whether we decide to open a new tab, we could make use of target=blank.
(2) Alternatively, the host of the FxA page is knowon, when the host changes the user would get a back button. With the new tab method we only need to do (1).

> Are their conditions that make the button go away?

Return to the FxA host if we are using (2) above. In case (1) above, pressing the button would make it go away, as the user would have returned. 

> Is there a better way to approach a standalone Back button? 

Good question for @ryanfeeley , Ryan did you see my demo of the back behaviour?

> The original reason FxA was opened within a special WebView 

It appears to be standard WKWebView controller so this line confuses me a bit. FxA is used as settings-type controller (being accessible from settings), so most of the considerations I can see in the code are related to that usage.

I think overall we should be ok to follow a new tab approach, as that seems to be the safest method here. I'll look at doing a prototype of that and see what issues it creates.

**Comment by ryanfeeley** [comment]
I receive complaints about our novel handling of links once in a while, and I can't say that I've ever seen this treatment of links from inside any iOS app ever. I've been confused about why it is we do this, but I think as there is more focus on accounts, it's something we should solve.

A quick look at what my 3rd party twitter client does show that they use the same webview UI for both authentication and views of web pages linked from tweets.

Shown below [1] add a twitter account [2] link to page from a tweet and [3] one link deeper (notice back button)
<img width="200" src="https://user-images.githubusercontent.com/68213/58886154-6dbdcf00-86b1-11e9-8468-dafd7d15df9f.PNG"> <img width="200" src="https://user-images.githubusercontent.com/68213/58886195-7b735480-86b1-11e9-8f20-6be6da5c9c96.PNG"> <img width="200" src="https://user-images.githubusercontent.com/68213/58886194-7b735480-86b1-11e9-9f89-39027611388e.PNG"> 

We currently employ two web views [1] for authentication and [2] for management. Neither have a back button, nor do we show the domain.
<img width="200" src="https://user-images.githubusercontent.com/68213/58886711-56cbac80-86b2-11e9-836a-f980a808b7f9.PNG"> <img width="200" src="https://user-images.githubusercontent.com/68213/58886580-28e66800-86b2-11e9-96ee-e65e7e5770db.PNG"> 

What if we have a web container more like what the Facebook app uses that does everything up top?
<img width="200" src="https://user-images.githubusercontent.com/68213/58887166-1d477100-86b3-11e9-8aaa-36b97b613e3a.PNG">

**Comment by garvankeeley** [comment]
The final example is do-able, to meld with our design it could be:
`< Back     the.domain.here      Done`
With the back changing as-needed for the navigation level. 

To avoid the concern raised in the comment https://github.com/mozilla/fxa/issues/1369#issuecomment-498597630 about FxA pages not supporting reloads from a back navigation, we can seamlessly open a new 'tab' (as a 2nd overlaid webview), and use the back nav to simply close the overlaid webview and show the FxA webview again.

**Comment by davismtl** [comment]
> We currently employ two web views [1] for authentication and [2] for management. Neither have a back button, nor do we show the domain.

That's fine with me to a certain extent. We don't normally want people going back and forth in a login flow. Our settings also don't quite need it. It feels a bit more native like this.


> we can seamlessly open a new 'tab' (as a 2nd overlaid webview), and use the back nav to simply close the overlaid webview and show the FxA webview again.

> What if we have a web container more like what the Facebook app uses that does everything up top?

The UX proposed by @ryanfeeley would make a lot of sense for loading external SUMO links. This way, they could really easily and clearly get back to the FxA flow they started.

**Comment by garvankeeley** [comment]
Here is working demo of (most of) what Ryan proposed:
![demo-fxa-account](https://user-images.githubusercontent.com/5495083/59132447-36fee780-8943-11e9-8173-e5826cda25fa.gif)

**Comment by garvankeeley** [comment]
This was fixed some time ago in Firefox iOS in https://github.com/mozilla-mobile/firefox-ios/issues/5066
