### ISSUE TITLE
In FxA registration, make "show password" a permanent toggle as it is secure enough for most users

### ISSUE THREAD

**Issue by dianehuang11** [mozilla/fxa#1395]
STEPS TO REPRODUCE
1. Create Firefox Account on Desktop
2. Enter email address
3. When creating a password, select show password icon 

EXPECTED RESULTS
* Show password toggle permanently reveals user password

ACTUAL RESULTS
* Show password toggle currently requires user to hold button to reveal characters

**Comment by shane-tomlinson** [comment]
The context for why we the permanent toggle was removed. Some browsers save the contents of text fields to disk in case the user's browser crashes or they close their browser. User's passwords were being saved in plaintext on disk for anybody to read. Firefox desktop has since remedied this, though we have not changed the behavior because other browsers may act the same.

Since we know new versions of Fx Desktop behave safely, perhaps there we could enable a "permanent" state there w/o enabling it eslewhere. Really, I wish this were just a browser feature and we could stop doing it all together.

**Comment by clouserw** [comment]
Let's do this without any filtering on platform or version.

No change to the UI here.  Just make it a toggle instead of a temporary press-and-hold.

**Comment by ryanfeeley** [comment]
Diane filed this on my behalf after a sync fest.

**Comment by juliemccracken** [comment]
This is a huge usability feature and is low hanging fruit. @shane-tomlinson will take a look at Barry's pr.

**Comment by mirunacurtean** [comment]
Verified that password toggle in registration flow permanently reveals the password when tapped.  Tested under Windows Pro 10 64-bit and macOS Catalina 10.15 on Stage [Train 1.150.2]
![R70 password toggle](https://user-images.githubusercontent.com/53306802/68845379-fcf4f700-06d3-11ea-8780-4a2ab9f29356.gif)
