### ISSUE TITLE
In Firefox Desktop, device names list should update when PAM is opened (so they are up to date when send to device submenu opens)

### ISSUE THREAD

**Issue by dianehuang11** [mozilla/fxa#1529]
STEPS TO REPRODUCE
1. Connect secondary device(s) to Firefox Account
1. Open Firefox for Desktop
1. Open Page Action Menu >> "Send Tab to Device"

EXPECTED RESULTS
* Device names list should reload when PAM is opened, so names are already updated when submenu opens

ACTUAL RESULTS
* Name of devices on list remain out of date after update
* Refresh/reopening of browser still shows outdated name 

*Default Device Name*
![Screenshot_20190605-152354 (1)](https://user-images.githubusercontent.com/28498717/59061542-c1771680-8871-11e9-863e-c79db1097a63.jpg)

*Updated Device Name*
![Screenshot_20190606-152001](https://user-images.githubusercontent.com/28498717/59061558-cb007e80-8871-11e9-961d-7e3e91d11c3a.jpg)

*Outdated PAM, even after reloading browser*
<img width="405" alt="Screen Shot 2019-06-06 at 3 19 51 PM" src="https://user-images.githubusercontent.com/28498717/59061586-d2c02300-8871-11e9-84de-855c7569e4e9.png">
<img width="1680" alt="Screen Shot 2019-06-06 at 3 21 16 PM" src="https://user-images.githubusercontent.com/28498717/59061591-d489e680-8871-11e9-8c70-f5836996ace0.png">

**Comment by shane-tomlinson** [comment]
Hi @dianehuang11 - There are screen caps on what looks like both mobile and desktop, and I'm not sure where the problem lies. Is this a problem in both browsers? Either way, these look like problems with the Firefox implementations rather than with the FxA servers. If these are browser bugs, can you re-open this in

* Desktop: https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Firefox%20Accounts
* Reference browser: https://github.com/mozilla-mobile/android-components/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+FxA

**Comment by clouserw** [comment]
@dianehuang11 I'm going to close this and assume you reopened in Bugzilla.  Thanks
