### ISSUE TITLE
Can't register for a new account 

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#1530]
STR reported by srich:

1) close Firefox 67. 
2) Open Firefox. v68 first run experience appears and prompted me to create a Fx Account. I used `<email>` and a randomly generated password from 1Password. 

Expected results: Get registered for a new account

Actual results: Wouldn’t let me proceed, blocking on “Must not match this list of common passwords.”  The password is random and wouldn't be on the common password list (see screenshot)

![image](https://user-images.githubusercontent.com/80098/59066494-0e53f080-8864-11e9-9ed1-e584bafd21f6.png)

**Comment by clouserw** [comment]
Changing to another random password and submitting allowed the sign up flow to proceed as expected

**Comment by rfk** [comment]
Sounds like a false-positive on the bloom filter we use for checking common passwords. To avoid this, I think we'd have to download the actual list of bad passwords (rather than the compressed bloom filter) to do a final check for whether the password is actually in the list.

**Comment by shane-tomlinson** [comment]
From me in Slack:

> If a bloomfilter says something is in the set, it *might* be in the set. If the filter says something isn't in the set, then it's definitely not in the set. % of false positives can be tweaked, though reducing false positives increases the size of the data set.

> To  avoid this, I think we'd have to download the actual list of bad  passwords (rather than the compressed bloom filter) to do a final check  for whether the password is actually in the list.

I'm very *meh* on this approach. I'd rather try to twiddle other nobs first.

**Comment by rfk** [comment]
> I think we'd have to download the actual list of bad passwords (rather than the compressed bloom filter)

I suppose we could also fall back to progressively larger-but-with-lower-rate-of-false-positives bloom filters as an alternative.

**Comment by shane-tomlinson** [comment]
> I suppose we could also fall back to progressively larger-but-with-lower-rate-of-false-positives bloom filters as an alternative.

That only works if you know the entire corpus of all possible passwords that are entered, which is neigh on impossible. An alternative is to twiddle the nobs to reduce the false positive rate and accept that there will be *some* false positives. 

Another alternative is to encode the password list using a lossless data structure such as a trie, smaller than a pure list of words, but possibly larger than a bloom filter.

**Comment by philbooth** [comment]
Or just tweak the messaging so that we're less categorical about it definitely being a common password? Picking a new one should be no hardship, so as long as the message makes sense for the occasional false positive it's good enough, right?

**Comment by shane-tomlinson** [comment]
> Or just tweak the messaging so that we're less categorical about it definitely being a common password?

This is both sensible, and from our point of view, very easy. @ryanfeeley - ?

**Comment by clouserw** [comment]
Side note: Let's make sure the passwords that Lockwise generate don't get stuck here.

Next steps:  We're going to try to tweak the bloom filter to be more accurate here.

**Comment by clouserw** [comment]
We got another report of this with a password generated by Firefox.

**Comment by ekr** [comment]
Instead of a Bloom Filter, why not use a hash-prefix type data structure like the one Safe Browsing uses?

**Comment by rfk** [comment]
(Also breach-alerts uses a similar hash-prefix scheme IIUC correctly)

**Comment by shane-tomlinson** [comment]
> To avoid this, I think we'd have to download the actual list of bad passwords (rather than the compressed bloom filter) to do a final check for whether the password is actually in the list.

@rfk - Multiple months later, and this feels like an easy iterative approach. The downside is the top 50k passwords, sorted alphabetically and gzipped comes in @ 156kb.

Hash prefixes would also work - we proposed hashing and checking when first implementing the feature and didn't get a warm response, the key difference here is the prefix. My worry about hash prefixes is that it'll require more work to implement and we have more than enough high priority work to keep us fully occupied. The upside is a smaller JS bundle because we could incrementally fetch hash prefix matches instead of creating a big data structure that must be downloaded.

Another option I considered is to [incrementally encode](https://en.wikipedia.org/wiki/Incremental_encoder) the whole dictionary and download the encoded version. The result of an incrementally encoded dictionary is ~ 50kb whereas the current bloom filter version is ~35kb. The other downside is querying requires reconstructing the dictionary, or at least a portion of it, which could cause some delay on slow devices.

All that said. I think downloading the full gzipped dictionary if there is a bloom filter hit is an easy approach that we could get out the door quickly.

**Comment by shane-tomlinson** [comment]
JUA7MYM8ni3cgU is the password from the image
