### ISSUE TITLE
"Sync Connected" notification should say “Firefox Preview” for Fenix, not "Firefox Sync"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#1531]
Authentication screens should refer to “continue to Firefox Sync” and the device name in device manager should be “Firefox Preview” (with android mobile icon). Currently they are the same.

cc @ryanfeeley

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-172)
┆Priority: Medium
┆Issue Number: FXA-172

**Comment by rfk** [comment]
In the 'device manager', we will soon start using the name provided by the client rather than the default OAuth client name.  I think the trickier case will be the "now syncing with..." notificaiton described in https://github.com/mozilla/fxa/issues/1397

**Comment by ryanfeeley** [comment]
Further evidence that this is needed came to light during Sync Fest.
![IMG_0097](https://user-images.githubusercontent.com/68213/59198009-b61d3700-8b60-11e9-905e-ca0e556fcde9.PNG)

**Comment by vladikoff** [comment]
<img src=https://user-images.githubusercontent.com/128755/59200903-42caf380-8b67-11e9-93c6-fb6dc5553b58.png width=350 />

<img src=https://user-images.githubusercontent.com/128755/59200923-4bbbc500-8b67-11e9-8b6c-fa598c25ec1f.png width=350 />

**Comment by rfk** [comment]
> Authentication screens should refer to “continue to Firefox Sync” and the device name in device
> manager should be “Firefox Preview”

Do we have a plan for how we might achieve this?

One option would be to change the logic on the signup screen, to look at the scopes being requested and say "continue to Firefox Sync" for things that are requesting the "oldsync" scope. Feels hacky, but maybe is a step towards a more OAuth-style "give X permission to access Y on your account?" style experience.

**Comment by vladikoff** [comment]
> One option would be to change the logic on the signup screen, to look at the scopes being requested and say "continue to Firefox Sync" for things that are requesting the "oldsync" scope.

**Comment by philbooth** [comment]
@vladikoff I can do this, is there a specific user agent string I can look for so we special case the device name here?

**Comment by juliemccracken** [comment]
@philbooth, I'm checking with the Fenix team to find out how important this is to them. Their go/no go meeting is today for tomorrow's release.

**Comment by vladikoff** [comment]
> special case the device name here?

I hope we can special case by Client ID maybe.. I don't think we can use the user agent

**Comment by philbooth** [comment]
> I hope we can special case by Client ID maybe.. I don't think we can use the user agent

Ah, my bad sorry, sounds like I misunderstood the issue. Taking my face back off this as I'm not sure what needs to happen in that case.

**Comment by rfk** [comment]
This continues to be noticed by users and continues to be weird.

Just thinking about how to move this issue forward...the reason it's a bit weird right now, is that we wanted to the login page to say "Continue to Firefox Sync" rather than "Continue to NameOfOAuthClient".  If we're going to do some special-casing then I think we should do it in the place where we want the special-case behaviour, which would mean:

* Adding special-case logic on the signin screen to (or perhaps in the OAuth relier model):
    * Check if the app is requesting "oldsync" scope.
    * If so, force it to say "Continue to Firefox Sync" or some variation
* Then changing the OAuth client name back to "Firefox Preview" once that has shipped

This would localize the special-casing to the place where we actually intend it. If we do go this route we'll have to check:

* Whether we're happy for this change to also affect Lockwise.
* Whether we still send the correct email variants during signup, and signin confirmation.

@vladikoff thoughts?

**Comment by vladikoff** [comment]
> Check if the app is requesting "oldsync" scope.

That is sensible. Is filtering by client id the only way that is clean?  (To make sure it's fine in Lockwise)

**Comment by rfk** [comment]
> That is sensible. Is filtering by client id the only way that is clean? (To make sure it's fine in Lockwise)

TBH I think Lockwise should just get the same treatment, meaning we'd only have to look at the scopes being requested and not at the client_id at all.

**Comment by rfk** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1602006
