### ISSUE TITLE
[Train 140]The sync doesn't work between Android Q-Desktop Windows 10

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#1635]
Environment:
Builds: Stage [Train 140];
Devices: 
- Google Pixel (Android Q);
- Nokia 6 (Android 7.1.1);
- LG G7 fit (Android 8.1);

Steps to reproduce:
1. Create an account;
2. Try to connect a second device to the same account;
3. Open settings and tap on Sync;

Actual results:
After the creation of the account and sync between a device and Desktop, the sync doesn't work.

Expected results:
After the creation of the account and sync between a device and Desktop, the sync works propper.

Notes:
- iOS-Desktop Windows 10 not affected;
-  All devices synced appears on the manage account -> Devices & apps but are not synchronize anything (tabs, history, bookmarks);
- If we try to manual sync, it stops right after the tap on sync and the message is 'Last synced: never';
- Those are our stage settings: 
![configs](https://user-images.githubusercontent.com/40264165/60267054-fc5cef00-98f1-11e9-859a-7861300d2934.png)
- a logcat with the problem: 
[logFxA.txt](https://github.com/mozilla/fxa/files/3334744/logFxA.txt)

**Comment by isabelrios** [comment]
We are experiencing similar issues in our sync tests on iOS. After creating bookmarks and logins on iOS, they don't appear on Desktop and vice versa. For History and Tabs we don't have any issues. We are using Nightly, stage server and a new account each time. I keep investigating this, but just in case it is related wanted to leave the comment here.
Thanks!

**Comment by vbudhram** [comment]
@sv-sdeiac This probably won't fix the issue but your desktop config for `identity.fxaccounts.remote.root` should be `https://accounts.stage.mozaws.net/`

I'll try to get an Android device to test syncing.

**Comment by sv-sdeiac** [comment]
Hello, thanks for your information. I tried yesterday with the configuration from the comment https://github.com/mozilla/fxa/issues/1027#issuecomment-505510319 and was not working. I retried today with the same configuration and now, the issue doesn't occur anymore. It is very weird that yesterday with the same config didn't work, and today it works normally.

**Comment by clouserw** [comment]
Hi @sv-sdeiac .  Would you clarify your last comment.  You said this was working normally but also that it's reproducible.  Is this bug still valid?  Thanks

**Comment by clouserw** [comment]
cc @johngruen

**Comment by clouserw** [comment]
@sv-sdeiac also, can this be reproduced in production (train 139)?

**Comment by sv-sdeiac** [comment]
Hello

> Hi @sv-sdeiac . Would you clarify your last comment. You said this was working normally but also that it's reproducible. Is this bug still valid? Thanks

The issue was reproducible on 27th June on all devices specified on the description but after more investigation, it seems that I can not reproduce the bug with all devices on 28th June, only with the Google Pixel (Android Q) it is still reproducible.



> @sv-sdeiac also, can this be reproduced in production (train 139)?

I rehearsed one more time now on the Stage server(Train 140) and it is still reproducible. 
The issue is not reproducible on production(Train 139).

**Comment by abodea** [comment]
Hi all,
## I couldn't reproduce the issue, please note the followings:
#### This was my configuration:
![FxA - configuration](https://user-images.githubusercontent.com/42831109/60576920-03b74900-9d87-11e9-81d5-30c4a7eaa98e.png)
Please note that I tried the following:
 1. Setup the configuration above on both **`Windows 10`** and **` Google Pixel XL(Android Q Beta 4)`**
 2. Created a new FF account on desktop -> made some progress added few bookmarks and made some history.
3. Logged in on **`Google Pixel XL(Android Q Beta 4)`** with the same account.
4. Performed a **`Sync`.**

All the data from **`Windows 10`** was displayed on **`Google Pixel XL(Android Q Beta 4)`.**
Also, note that I tried to make progress on **`Android`** and Sync it to **`Windows 10`** and it worked every time.
#### The sync messaged worked accordingly it was displayed since a `sync` wasn't performed correctly.

#### Also, note that I tried to catch the exact period when I logged in of logcat, maybe it's helpful [log.txt](https://github.com/mozilla/fxa/files/3354086/log.txt).

Thanks,
Andrei

**Comment by sv-sdeiac** [comment]
Hello, I tried the issue with the actual production build and stage server [Train 142] but I can't reproduce anymore the problem.
Build:
- RC 68.0;

Device:
- Google Pixel (Android Q);

Due to my findings, I'll close this issue, thanks.
