### ISSUE TITLE
[Payments] Regression in Subscription Manage button

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#1637]
I believe c4b1af14bf91b09960f7fe0f1c3e595f12cfcb0c (by @shane-tomlinson) caused a regression in the Settings subscription Manage button:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/44390/60301711-b4d96180-98f7-11e9-8666-fc9a7e3b00c1.png">

After the commit the button no longer works, with the error message `Error: Invalid parameter: %(param)s`. After some investigation I believe this is coming from `createOAuthToken()` and is due to an error about a missing parameter `client_secret`.

**Comment by lmorchard** [comment]
This *should* be fixed by PR #1592. The `client_secret` thing is a bit of a red herring - what we really need is for the subscription management client [to become a public client](https://github.com/mozilla/fxa/pull/1592/files#diff-bca803ff6b323df3b3407f94d63c23e7R178). Those don't use client secrets at all.

(Still on PTO, but saw this in my inbox and knew the answer)
