### ISSUE TITLE
Subscription page form visual issues

### ISSUE THREAD

**Issue by juliastarkov** [mozilla/fxa#1666]
@ianb (please also ping anyone else who should be on this issue; not sure who to involve here)

Several visual issues:

- The font for the form fields is much bigger than specified in Zeplin
- Due to that, the alignment of the placeholder text is off (seen most in "Exp. Date")
- Also due to that, the card number exceeds the form field and gets cut off.
- The card type image (available via Stripe) is no where in the field, as was specified in Zeplin. 
- Is it part of our existing styling that there is a hover state on an inactive button? I don't  understand why I have a state on Update while it's un-clickable. 
- "Zip code too short" doesn't feel like the right error state for an empty field. 

<img width="685" alt="Screen Shot 2019-07-02 at 1 39 42 PM" src="https://user-images.githubusercontent.com/26334275/60629653-6a4e5e00-9dab-11e9-8748-048c0279319e.png">

**Comment by juliastarkov** [comment]
As we discussed in our meeting today, I wanted to note that if it's significantly easier to just copy and paste the billing form code out of the onboarding screens and that that will take care of most of the issues listed above, that is fine with me. I'd prefer to follow the mockups but not at the cost of a lot of extra effort.

**Comment by meandavejustice** [comment]
@juliastarkov  Finally getting a chance to address this issue today.

> The card type image (available via Stripe) is no where in the field, as was specified in Zeplin.

We are using the `cardNumberElement` from [react-stripe-elements](https://github.com/stripe/react-stripe-elements) which doesn't actually show the icon in the input. These elements provide a _lot_ of value for us in simplifying the form handling, I'd like to avoid implementing this all from scratch in order to add the icon. How would you feel about creating a _nice to have_ issue for the icon that we can address after our deadline?

Another possible way we could address this is to use the combined card element instead of the 3 separate fields for `cc number`, `exp date` , and `cvc code`.

![card-numbers](https://user-images.githubusercontent.com/1844554/61241854-665afe00-a712-11e9-9dde-1d9c4cf17ca7.png)

Further context for the icon issue, https://github.com/stripe/react-stripe-elements/issues/74

-------------

All other bullet points were addressed in https://github.com/mozilla/fxa/pull/1781, screenshots are in the description.

**Comment by meandavejustice** [comment]
Closing as this was merged in #1781, and I've opened https://github.com/mozilla/fxa/issues/1842 for the remaining cc number icon issue
