### ISSUE TITLE
[payments] Product redirect should complete after signup/confirmation

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#1723]
Note this only applies after #1310 lands:

If you visit a product redirect page, like http://127.0.0.1:3030/subscriptions/products/123doneProProduct and sign up, you end up at the settings page. You should end up at the product page you intended to go to.

**Comment by shane-tomlinson** [comment]
@ianb is the intention here to end up on the RP with OAuth credentials (an OAuth code/token)?

**Comment by lmorchard** [comment]
> @ianb is the intention here to end up on the RP with OAuth credentials (an OAuth code/token)?

No, I think this issue is a part of the payment process for issue #1364. 

If the user enteres FxA via a subscription product marketing page, we want them to eventually end up on the product payment page in fxa-payments-server (ala issue #1682) after they complete whatever needs doing in the signup / signin flow.

At the end of that, we redirect to an RP product page, but without OAuth credentials - i.e. it's just a plain redirect. If the RP requires creds on the web from there, the user will probably have to sign in again - but that's not a problem we're solving yet.

**Comment by lmorchard** [comment]
Adding to Train 142, because this is basically a sub-issue of #1364

**Comment by ianb** [comment]
The redirect URL might be a simple change for the signin case (it doesn't work, but it's a small fix), but for signup with email verification this might be more complicated, as we want to redirect the user after they paste in the confirmation email. Currently the signup redirect uses the OAuth database to figure out where you want to ultimately go, and we need it to simply redirect to this internal URL (`/subscriptions/products/:productId`)

**Comment by lmorchard** [comment]
FWIW, I just attempted visiting this product redirect URL from a signed-out state:

https://latest.dev.lcip.org/subscriptions/products/prod_Ex9Z1q5yVydhyk

I signed in and FxA redirected me to the payments server as desired. So, that part seems to already work here.
