### ISSUE TITLE
[Firefox For Fire TV] Meta Bug

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla/fxa#1734]
This issue tracks usability issues discovered when logging in on Fire TV devices.

**Comment by davismtl** [comment]
Making email first login flow work well on Fire TV. Input with a TV remote is very different from mouse, keyboard and touch device.

**Comment by davismtl** [comment]
@dannycoates from legal:

In regards to this quote from you:
“the TV interface is sort of like tab navigation but with more “stops” since there’s no cursor. With the TOS between the input and button the user must navigate over those links before getting to the button, and they must do that twice when creating an account with email-first. The TV team doesn’t like that (i agree). Moving them below the button would make the common flow more streamlined. In the interim I’ve set the links as tabindex=-1 which skips over them, but now those links are unreachable on TV”

- TOS and PN can be on the 2nd screen only. Not needed on first screen since we don't save that email unless they complete step 2.
- TOS and PN can go IMMEDIATELY after the registration button on screen 2. (anything with a checkbox needs to remain above the button)

**Comment by davismtl** [comment]
Oops, call me a Zenhub n00b. I put the TOS Privacy Notice issue as a blocker. Somehow I'm unable to remove the blocker.

**Comment by davismtl** [comment]
PR to make changes to this will happen today.

There was a request for us to hide registration. How should we approach this?
@ryanfeeley

**Comment by abodea** [comment]
@athomasmoz I just created a new issue **`The back button from Terms of Service doesn't have any functionality and cannot be selected`** see more details here([2221](https://github.com/mozilla/fxa/issues/2221))

**Comment by davismtl** [comment]
- A bit behind right now
- Work done to get to make it work on tv
- Will be circling back to this after the removal of style=trailhead

**Comment by davismtl** [comment]
@dannycoates continuing work on this this week.
@davismtl to update Ashley

**Comment by davismtl** [comment]
Shipped by FireTV yesterday.

Only one small UX bug for us to resolve on our end.
