### ISSUE TITLE
[Train 141 - stage] "Subscription" option displayed in Manage account

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#1747]
Environment:
Stage [Train 141];
Platform: iOS, Android, Windows -x64;

Steps to reproduce:

1. Log in with a Firefox Account;
2. Go to Manage Account page;
3. Go to the "Subscription" section.

Expected results:
"Subscription" section should not be displayed since the functionality is not implemented. 

Actual results:
"Subscription" section is displayed.

*Concerns*
- We don't know if it will be shipped to the users or is under a flag but we could see the button just pointing the server to stage.
- We think that we shouldn't ship to the user options that are not completed yet. Note here also that the "Manage" button is not responsive.

**Comment by lmorchard** [comment]
Two options to fix this, I think:

1. Turn off the subscriptions feature on the content server in stage
2. Implement #1078 so that the button only appears when the user has an active subscription - since that will be basically no one until after release of subscription features, that will effectively hide the button

**Comment by shane-tomlinson** [comment]
Opened https://github.com/mozilla-services/cloudops-deployment/pull/3298 to disable subscriptions in prod but remain enabled in stage for testing.

**Comment by shane-tomlinson** [comment]
Closing this issue, subscriptions being enabled on stage is intended.
