### ISSUE TITLE
[Train 141]The devices are not ordered on 'Devices & apps' list

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/fxa#1767]
### Environment: ###
Builds: Stage [Train 141];
Devices:
- Nokia 6 (Android 7.1.1);
- iOS 12.1.4;
- Sony Xperia Z2 (Android 6.0.1);
- Windows 10 - x64;

### Prerequisites ###
The user should be signed in with a valid account on multiple devices.

Steps to reproduce:
- Go to https://accounts.firefox.com/settings;
- Click the 'Show' button from the Devices & apps area;
- Observe the list;

Expected results:
All devices are ordered and match on all devices.

Actual results:
The devices are not ordered.

Notes:
- The synced Tabs list is differently ordered than the Device & apps list.
- The order of the list doesn't match with the order on a different device.
- Photo:
![device](https://user-images.githubusercontent.com/40264165/61124318-3bbd3b00-a4af-11e9-8299-cbc6b0979598.png)

**Comment by rfk** [comment]
We do sort them, but the order may not be obvious. It's described [here](https://github.com/mozilla/fxa/blob/6eebc81600a57e7a87ca9c31ed9b04fd12191ead/packages/fxa-content-server/app/scripts/models/attached-clients.js#L26) as:

1. the current session (and any associated device record) is first.
2. devices of the same type are grouped together (all sync devices, then all oauth apps, then all web sessions).
3. those with lastAccessTime are sorted in descending order
4. the rest sorted in alphabetical order.                                   

The screenshots seem to be consistent with this logic, showing the various devices in order of most-recently-synced.

I'm open to the suggestion that this ordering is not useful in practice though, and a more consistent order (e.g. always alphabetical) might be easier to understand. @ryanfeeley any thoughts?

> The synced Tabs list is differently ordered than the Device & apps list.

Good point. We could consider doing this sorting on the server rather than in the client, in order to provide a default consistent device order across all clients.

**Comment by ryanfeeley** [comment]
The ordering is not immediately apparent, but it's there. There are 3 major groups. Sync devices are first (current device first) sorted by last sync time. Then services like Monitor sorted by last active time. Then web settings (other logins to fxa settings) sorted by login time. It's working well and preferable to intermixing sync devices with services.

Synced Tabs also have a sort order, which is based on recency (most recently used devices and then by most recently opened tabs).

Here is mine for example: 
![image](https://user-images.githubusercontent.com/68213/61238019-cbf6bc80-a709-11e9-8da6-f2a9be954dae.png)
