### ISSUE TITLE
[auth server] Improve code re-use in email methods

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#1779]
I'm adding some new email-related stuff for #927 and the level of boilerplate copypasta in those modules is pretty annoying. Didn't want to do it in that PR but I think we can replace most of it with a couple of parameterised functions.

**Comment by vbudhram** [comment]
FWIW, I'm 👍 for this. There is a good amount of boilerplate stuff that needs to be done to add a new template. 

Additionally, I think parts of `sender.js` and `email.js` could also be combined so that we can avoid doing nested calls with same function names like https://github.com/mozilla/fxa/blob/b22d8cdeb47cf4dcd52aa90fc8e21f4eedd24725/packages/fxa-auth-server/lib/senders/index.js#L133. We could have `email.js` be responsible for just sending emails.

That refactor could be hairy though...

**Comment by philbooth** [comment]
> ...we can avoid doing nested calls with same function names like...

I intend to go further than that fwiw. Not only do we not need a nested layer of calls, we don't need the outer layer either. It's completely unnecessary copypasta. We just need one function `send` that works the same for every template, with any variations in behaviour handled by arguments and/or config. We can delete about 2,000 lines of production code and a load of test code too.

**Comment by philbooth** [comment]
And the duplication in the templates can all be got rid of too, if we refactor the common bits to partials.

**Comment by philbooth** [comment]
And the weird mixing of both nunjucks and handlebars for templates is unnecessary too, we only need one of them.

**Comment by shane-tomlinson** [comment]
> And the weird mixing of both nunjucks and handlebars for templates is unnecessary too, we only need one of them.

IIRC this was to precompile nunjucks templates into handlebars templates, but I forget why that was necessary. @vladikoff, do you remember?

**Comment by philbooth** [comment]
> IIRC this was to precompile nunjucks templates into handlebars templates, but I forget why that was necessary.

It's used for block substitution, which I've replaced with handlebars partials syntax in #1791.
