### ISSUE TITLE
Speaking of unhandledRejection should an unconfigured rpQueue be a death sentence

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#1804]
I was running the traffix generator (one at a time) and it picked the id I had not configured in <s>Firestore</s> (edit: in Topics). This resulted in an unhandledRejection, which probably should be handled(?).

You can still exit at the point if you choose to, but probably you meant to handle that (and exit explicity(?) if you did).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-208)
┆Issue Number: FXA-208

**Comment by bbangert** [comment]
I don't think we want to handle this in code. Having it in code means that event-broker needs the ability to create queues on-demand and I don't believe it should have the ability to arbitrarily create queues. I have heard that there's a self-service oauth portal that lets ppl create oauth client id's, if any place is going to create a queue, that should be the code doing it.

Otherwise we should require queue creation during setup of oauth client id's as part of our manual setup process for a new RP.

**Comment by bbangert** [comment]
@jrgm was it event-broker that died, or the generation script?

**Comment by clouserw** [comment]
@jrgm We (in triage) think this is fixed now.  Have you run into this again?
