### ISSUE TITLE
Create Fake Subscription RP "Firefox Fortress"

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#1894]
I would like to have a fake RP available that:

1. Demonstrates our subscription platform capabilities for RP and leadership audiences
2. Highlights preferred FxA language and UI patterns for Relying Parties
3. Is flexible enough to change as needed (ie not tied to functional tests) by product and visual design teams to reflect new and emerging UI requirements.

123Done is not brand aligned and already has overloaded dependencies b/c of its role in content server functional tests here making it a poor fit for these requirements.

**Comment by lmorchard** [comment]
A known issue on 123done is that you have to log out and log back in to reflect a change in subscription state. At the least, we should refresh profile info on the initial hit to the page.

Might be a stretch goal, because this would require some server-side support in "Fortress", but: It would be nice if we could hook this up to the event broker to receive changes to profile information. Could maybe do this somehow with Redis?
