### ISSUE TITLE
Add CSP to the payments-server

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#1923]
Seems a little involved, spinning off as a separate sub-issue from #1128.

We might be able to reuse the CSP-related middleware from the fxa-content-server package.

**Comment by 6a68** [comment]
I found some docs on the CSP config required for the Stripe JS to work: https://stripe.com/docs/security#content-security-policy

**Comment by jvehent** [comment]
The CSP is not super useful at the moment because it allows unsafe styles.
`content-security-policy: connect-src 'self' https://api.accounts.firefox.com https://oauth.accounts.firefox.com https://profile.accounts.firefox.com https://api.stripe.com; default-src 'self'; font-src 'self'; frame-src https://js.stripe.com https://hooks.stripe.com; img-src 'self' data: https://secure.gravatar.com https://firefoxusercontent.com; media-src 'none'; object-src 'none'; report-uri https://accounts.firefox.com/_/csp-violation; script-src 'self' https://js.stripe.com; style-src 'self' 'unsafe-inline'`

Could we get that removed?

**Comment by lmorchard** [comment]
> The CSP is not super useful at the moment because it allows unsafe styles.
> Could we get that removed?

If I recall, we need `unsafe-inline` for `style-src` because React injects inline styles. In particular, for the third-party Stripe elements over which we don't have much control otherwise. Might need to dig to verify this, but I *think* that's the reason.

**Comment by clouserw** [comment]
Sorry, I didn't see this Issue reopened before I filed https://github.com/mozilla/fxa/issues/2649 .  I'm going to close this one, since the patch is landed/live already (and Issues are tied to milestones).  Please discuss in #2649
