### ISSUE TITLE
Stop asking for email address if an FxA session exists

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#1949]
I think we should be able to reduce this bump in the road, to provide a more seamless experience when traversing FxA relying-services.

**STEPS TO REPRODUCE**
1. Install Notes extension and **Sign in to Sync** with a new account
1. Verify the account and confirm you have a session by visiting https://accounts.firefox.com
1. In FxA toolbar menu select **Turn on Sync…**

**EXPECTED RESULTS**
* Existing session is shown, user merely has to re-enter password (for services that require keys)
<img width="279" src="https://user-images.githubusercontent.com/68213/61896926-facc1a00-aee3-11e9-8c27-9e8c948fe4cc.png">

**ACTUAL RESULTS**
* User has to re-enter their email address
<img width="600" alt="Screen Shot 2019-07-25 at 1 50 20 PM" src="https://user-images.githubusercontent.com/68213/61897024-2e0ea900-aee4-11e9-9961-01b60bc42b24.png">

**Comment by dianehuang11** [comment]
Confirmed with Firefox Send as well. User signed into Send but have to re-enter email for Sync. 

_After successful log-in via send.firefox.com_
<img width="1659" alt="Screen Shot 2019-07-25 at 4 07 33 PM" src="https://user-images.githubusercontent.com/28498717/61905211-8cdd1e00-aef6-11e9-8f03-b10e3fdaa534.png">

_In FxA toolbar menu select Turn on Sync…_
<img width="577" alt="Screen Shot 2019-07-25 at 4 07 44 PM" src="https://user-images.githubusercontent.com/28498717/61905213-8e0e4b00-aef6-11e9-96e8-dd2559f04a3d.png">

**Comment by shane-tomlinson** [comment]
Any time the encryption keys are needed, the user needs to enter their password, no matter what. This is a technical limitation that we haven't figured out how to engineer around. This means users of Send, Sync, Notes, and Lockbox will *always* need to enter their password.

**Comment by shane-tomlinson** [comment]
> This is a technical limitation that we haven't figured out how to engineer around. 

More on why this is. This is because the password used to encrypt/decrypt data is in part derived from the user's password. Without the user's password, that input to the derivation is missing, and the correct encryption keys can't be generated.

**Comment by rfk** [comment]
> Sync, Notes, and Lockbox will always need to enter their password.

IIUC this bug is about unnecessary prompting for the *email address*, not the password.

**Comment by shane-tomlinson** [comment]
> IIUC this bug is about unnecessary prompting for the email address, not the password.

Oh dear lord.

**Comment by clouserw** [comment]
@shane-tomlinson will investigate this -- we think you are being opted-in to an experiment cohort

**Comment by shane-tomlinson** [comment]
This happens [because of this little chestnut](https://github.com/mozilla/fxa/blob/3729152fc0cf4bcfaf65b94cc05cc86f4d47ea7a/packages/fxa-content-server/app/scripts/lib/app-start.js#L611-L613):

> // The Sync user should *always* come from the browser
> // if FXA_STATUS is supported. Don't even bother
> // with localStorage.

That reminds me that I have always known this was a possibility and ignored it because so many more users start at Sync than at OAuth RPs.

We did this so that the browser would always be the canonical source of truth when it comes to signing into Sync, we should always use it's view of the world... _if a user is signed in_

The problem here is no user is signed into the browser, so even though we have a signed in user in localStorage, the browser reports that nobody is signed in and we show a blank email field.

What we should do is continue to use localStorage, but merge the user as seen by the browser and any accounts stored in localStorage.
