### ISSUE TITLE
Create a Subscription Platform Terms of Service page

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#1986]
This can live on the content server, next to all the other legal pages.  This should follow the same build steps as all our other legal pages -- no special cases.

This can be an empty page until we get legal content.  (It would be nice to have the URL earlier, despite not having content).

**Comment by chenba** [comment]
What should be the URL?

**Comment by clouserw** [comment]
The existing FxA docs are:

- https://accounts.firefox.com/legal/terms
- https://accounts.firefox.com/legal/privacy

So, how about:

- https://accounts.firefox.com/legal/subscription_terms

**Comment by philbooth** [comment]
> So, how about:
>
> * https://accounts.firefox.com/legal/subscription_terms

Just noting, I'm also using this in #1791 now, so let me know if it changes for any reason.

**Comment by chenba** [comment]
@clouserw Do we need to file an issue over at https://github.com/mozilla/legal-docs for the copy?

**Comment by chenba** [comment]
@clouserw Also, because [how the legal pages work](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/server/lib/routes/get-terms-privacy.js#L10), I'm going to show the `/legal/terms` Terms of Service on the new page until we have the actual content.  I need it to serve something instead of throwing missing template errors.

**Comment by clouserw** [comment]
Both ideas are good.  Thanks @chenba

**Comment by chenba** [comment]
Filed #2072 as a follow-up.  Closing.
