### ISSUE TITLE
3.3  Empower AMO to force TOTP on developer accounts.

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2024]
We'd like to simplify the path a user needs to take to enable 2FA from AMO.  The end goal will be to require 2FA for all developer accounts on AMO.

Edit:
Jared's brainstorming:
https://docs.google.com/document/d/15BZAgco_G93bPm2SVGNDVSTI4YDvdTx5_TqgDZv5XME/

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-240)
┆Issue Number: FXA-240

**Comment by davismtl** [comment]
- Jared will be writing out a 1-pager
- Will circulate with Jorge, Stuart and FxA team

**Comment by davismtl** [comment]
- Jared wrote a 1-pager with current flow and made a proposal for better flow
- Ryan would like to avoid designing a custom flow for a single RP

**Comment by davismtl** [comment]
@ryanfeeley to review the proposed flow from @6a68 outlined here:
https://docs.google.com/document/d/15BZAgco_G93bPm2SVGNDVSTI4YDvdTx5_TqgDZv5XME/

**Comment by davismtl** [comment]
@6a68 is going to propose wireframes to @ryanfeeley and we'll walk through them together.

**Comment by davismtl** [comment]
@ryanfeeley is working on the mockups since it now fits in the bigger picture.

**Comment by davismtl** [comment]
Here are the invision mockups/flow:
https://mozilla.invisionapp.com/share/7PUGYZX2TJW#/screens/389634598_Two-Step_Authentication_Wall

**Comment by davismtl** [comment]
From mtg:
@6a68 is this still on track for train-153?
We should keep AMO team up to date on timeline and progress.

**Comment by chelsea-lewis** [comment]
Per today's FxA Weekly meeting, still tentatively Train-153.

**Comment by davismtl** [comment]
Started on the first issue which includes `prompt=none`.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Will start in parallel to metrics.

**Comment by muffinresearch** [comment]
@davismtl do you have an update on where this is at and when you expect to land?

**Comment by clouserw** [comment]
@6a68 said he would be making progress on it this week.  Expecting delivery in Q1

**Comment by muffinresearch** [comment]
@davismtl @clouserw is this still on target for delivery by end of Q1?

**Comment by clouserw** [comment]
Optimistically, yes

**Comment by diox** [comment]
Now that https://bugzilla.mozilla.org/show_bug.cgi?id=1639985 is resolved we have moved addons-dev.allizom.org (AMO dev) to FxA staging env as suggested by @6a68 to get a more stable environment for testing this. The issues we were trying to debug were:
- https://github.com/mozilla/fxa/issues/5206.
- `error=unauthorized_client` error when using `prompt=none` and `id_token=<OpenID token>`

I'm not sure whether #5206 is fixed or not, as I have only seen it happen with old accounts and I don't have any on FxA staging. We are still seeing `error=unauthorized_client` though, and it completely prevents the full flow from working. 

I've pushed the feature on AMO dev so that everyone can test it, but it's behind a per-user flag on our side in order not to mess with QA testing other issues. I can enable the flag for any user if someone from your team wants to see it live.
