### ISSUE TITLE
Add support for multiple products in new subscriber email

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#2026]
In PR #1791, we added support for an email to be sent to new subscribers with a product download link. [The implementation hard-codes text for Secure Proxy](https://github.com/mozilla/fxa/commit/7c84c152541de27fae5a405a973476f73994e6f9#diff-9437bdee47e1fcc021d46b2e851618f3R1763) and there is only [support for a single download URL](https://github.com/mozilla/fxa/commit/7c84c152541de27fae5a405a973476f73994e6f9#diff-9437bdee47e1fcc021d46b2e851618f3R1755) (see also issue #2025).

The text, icon, and URL (once updated in #2025) could be sufficient for the first-and-only product. But, we will need to expand this implementation to support multiple products.

Not sure where we could source the email text & icon changes. L10n will complicate this, also.

For the URL, we could link to the product subscription page - that page should redirect to the download page for the product if it detects that the user is subscribed. (e.g. https://accounts.firefox.com/subscriptions/product/{product ID}`

**Comment by lmorchard** [comment]
Slapping on a high estimate, mainly because I think there are unknowns around content management for products and l10n. We can tweak it down later if this turns out to be easy

**Comment by philbooth** [comment]
The first cut of this, where we're not concerned about l10n, is straightforward. For instance, we could have a mapping from product id to product name, icon and URL in config.

But once translation becomes an issue it gets trickier. Strings for l10n are extracted from the codebase statically, so we'd need the product names to exist on disk somewhere if that's going to work. If ever a product name changes, that would require an auth server change + tag + redeploy to catch up, which seems suboptimal. Alternatively, perhaps we could update our l10n wiring to do something more dynamic than that.

But anyway, until *that's* decided I'm not sure it's worth the trouble of putting stuff in config for the first step. If config isn't going to work long-term, why bother using it in the short term? Maybe continuing to hard-code stuff is fine for now?

Just noting this because I went to pick this issue up today, started thinking about the above, and then changed my mind. But we need to do something soon.

**Comment by lmorchard** [comment]
Just a note probably to self and because I'm working on issue #2882 - product name related strings are currently hardcoded and untranslated here:

https://github.com/mozilla/fxa/blob/5a14f16af887ee227468f9ebb200663a336ad5a6/packages/fxa-auth-server/lib/senders/email.js#L1607

**Comment by johngruen** [comment]
I think we could potentially call this a stretch goal if we provide a single web-based access point for a multiple product subscription. IE rather than relying on the email to link out to all products, we enforce a policy of having bundled products require their own download endpoints so we just have to provide one link.

**Comment by johngruen** [comment]
I am going to move this into the tiered subscriptions epic...since the email doesn't currently include a product icon, I think we can kill that as a requirement in the initial implementation of this bug. So i think we can close this issue when we can do the following:

* Include the correct product name in the download email
* Include the correct subject for each product email
* Include the correct button CTA in each product email
* Include the correct product link in the download email

**Comment by lmorchard** [comment]
I'm going to lower the estimate on this a bit. I think it'll mostly be a matter of figuring out where the per-product content lives and then using it - i.e. in Stripe metadata or in a JS module on the FxA side.
