### ISSUE TITLE
Include Account Settings subheading when signing in to Settings

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2054]
So that users have the clearest sense of their destination, we should include the service name in subheading. For login, registration, force auth and password reset, we should include *Account Settings* when service equals none (I think it's none…?).

**Current**
<img width="300" alt="Screen Shot 2019-08-02 at 11 46 01 AM" src="https://user-images.githubusercontent.com/68213/62391142-0d70cf80-b532-11e9-8b13-6da8eb1c06ca.png">

**Proposed**
<img width="300" alt="Screen Shot 2019-08-02 at 11 46 15 AM" src="https://user-images.githubusercontent.com/68213/62391141-0d70cf80-b532-11e9-95cd-3e1a17d4e380.png">

**Comment by Dharmesh-Poddar** [comment]
@ryanfeeley can I work on it ..

**Comment by ryanfeeley** [comment]
@Dharmesh-Poddar  Sure!

**Comment by Dharmesh-Poddar** [comment]
@ryanfeeley I am not getting the changes that I make in code applied to my local project setup..

**Comment by PrachiSarda** [comment]
@ryanfeeley can I take this up as my first issue?

**Comment by PrachiSarda** [comment]
Any updates? @ryanfeeley

**Comment by ryanfeeley** [comment]
@PrachiSarda Feel free to take it!

**Comment by LZoog** [comment]
Hey @PrachiSarda, have you had a chance to work on this issue? 🙂

**Comment by LZoog** [comment]
Hey @ryanfeeley, since we're only e-mail first now for registration, I wanted to run these by you. How's the spacing look? I set `serviceName` across the board in our `service-mixin.js` to `Account Settings` if one was not provided in the screenshots below, but I'm not sure this is what we want. It'll always display "to continue to Account Settings" this way where we have this option for relying parties. Are there flows in which we would _not_ want to display "to Account Settings" if there is no RP? (I'm not sure if the verification screen is part of "registration".)

Not sure how much this helps, but [here's our template files](https://github.com/mozilla/fxa/search?l=HTML%2BDjango&q=serviceName) that would display "Account Settings" if I made this change across the board.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/13018240/69663553-168b2c80-104c-11ea-98a9-2b30fceae123.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/13018240/69663565-1db23a80-104c-11ea-8374-f1aa2eb17bf1.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/13018240/69663822-b052d980-104c-11ea-85c3-1c906764006e.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/13018240/69664115-53a3ee80-104d-11ea-9b0b-f2cddca0da58.png">

**Comment by ryanfeeley** [comment]
@LZoog Looks good, thanks for checking in!

**Comment by ryanfeeley** [comment]
@LZoog I don't imagine a situation where we should hide the **to Continue to RP** line…
