### ISSUE TITLE
FFTV coppa dead end

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#2100]
What's supposed to happen when the user "fails" coppa on TV? Currently it dead ends at the coppa notice and you can't retry or proceed further. What do other sync clients do?

**Comment by shane-tomlinson** [comment]
> What's supposed to happen when the user "fails" coppa on TV? Currently it dead ends at the coppa notice and you can't retry or proceed further. What do other sync clients do?

This might be one of our most common filed bugs, and I'm having troubling finding references to any of them. This is exactly what other clients do, and is intentional under the direction of the Legal team so we comply with COPPA. The intent is to keep users that are too young from using FxA and any related services. 

We store whether the user entered an age that is too young in a session cookie. If FxA loads and the cookie is there, then send the user to the "you are too young" page. The cookie is a session cookie and is supposed to clear when the browser restarts.

Ref https://github.com/mozilla/fxa-content-server/issues/259
https://github.com/mozilla/fxa-content-server/issues/4228

@ryanfeeley do you have a link to the [referenced legal bug in this issue](https://github.com/mozilla/fxa-content-server/issues/4228)?

**Comment by shane-tomlinson** [comment]
All that said, I can't help but thinking there should be something better we can do. Maybe explicitly time the cookie out after 10 minutes to handle browsers where the cookie is not automatically deleted on restart. Any changes to this will need to be approved by Legal.

**Comment by clouserw** [comment]
This discussion will happen between legal and privacy/security about whether we need to set that cookie or not.  More details next week.

**Comment by clouserw** [comment]
In our legal meeting a couple weeks ago the conclusion was that we are all satisfied with the way the session cookies work today.

**Comment by clouserw** [comment]
Closing based on above comments
