### ISSUE TITLE
Accept an `id_token_hint` during the `prompt=none` flow

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2132]
`prompt=none` is meant primarily as a [wait to to confirm a user's login state](https://github.com/mozilla/fxa/issues/590) and is supposed to be used by RPs where the user has already authorized access.

[The prompt=none flow](https://github.com/mozilla/fxa/pull/1150) currently accepts a `login_hint` or `email` query parameter to ensure the user was at least asked for their email address first, implying user authorization on the RP. `login_hint` was used to get the feature out the door quickly, but it's not as secure as it could be since emails are public. We limit use of `prompt=none` to RPs we have first audited to ensure they aren't doing anything suspect.

The [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) recommends accepting an `id_token_hint` instead. `id_token_hint` is an [ID token](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) that is given out to RPs that request the `openid` scope. Barring the current `prompt=none` flow, the only way to get an ID token is for the user to authorize access to an RP.

If an rp provides an `id_token_hint`, we would verify the ID token is valid, and is meant for the RP. If the token is valid, and the user is still authenticated to FxA, then silently generate new OAuth tokens/codes.

prompt=none could be opened up to more RPs, sure in the knowledge that they are doing the right thing, if we accepted an `id_token_hint`.

Ref https://github.com/mozilla/fxa/issues/590 of which this issue is one possible approach.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-261)
┆Issue Number: FXA-261

**Comment by 6a68** [comment]
Not totally sure this is required for #2024, but it's definitely related

**Comment by lmorchard** [comment]
@6a68 Reviving a thread from last year: Does this issue prompt a re-think of PR #3723 / issue #1695 for reworking payment-server as an OAuth RP?

We wanted auth UX there that doesn't prompt for permission - just pass the user through since payments-server is basically another part of FxA. We'd planned to use `?prompt=none` for this, but it sounds like that's not what `?prompt=none` will ultimately provide.

**Comment by 6a68** [comment]
@lmorchard Ah right! Yeah, I've thought about this a little bit. I'm not sure where the right place is to gather all the threads together (#1695, maybe?), but I now think that `prompt=none` should work, provided we add SSO support. I now understand that OIDC is intended to provide an identity layer on top of OAuth, with SSO support as one of the key use cases.

The FxA OAuth docs show that we do support the `openid` scope, meaning RPs can request the OIDC id token at login time. We also have PKCE support, which defends against the auth token being intercepted by an attacker. And, we have support for JWT access tokens (#935), though that PR refers to an OAuth draft spec, not an OIDC spec, so I'm not totally clear on its value for SSO. Beyond those pieces, I'm not sure what additional work would be necessary to enable SSO, or whether we decided against implementing SSO for non-technical reasons. (Oddly, I can't find any bugs discussing SSO.)

@rfk, do you happen to have any context around FxA support for SSO between Mozilla RPs? This would be in context of allowing a logged-in user to bypass the auth flow when traveling from a freemium RP to the payments page.

**Comment by rfk** [comment]
> do you happen to have any context around FxA support for SSO between Mozilla RPs?

Not really, as I don't think we've pursued it very deliberately. There's some context in the old issue about allowing IAM to login without re-entering a password (https://github.com/mozilla/fxa/issues/640) and a bit more in the issue about RP-initiated logout (https://github.com/mozilla/fxa/issues/1979). Historically, that second one has been the thing that hasn't been entirely clear - after the user has successfully single-signed-in, how do they single-sign-out?

Given the work on "bento box" menus for our various web properties, I think we're going to have to figure out a good SSO story sometime this year, as our UX will lead users to expect it.

I don't think this specific bug will help you with the payments-related use-case though, since it's not clear where it would get an `id_token` from in the first place.

> We'd planned to use ?prompt=none for this, but it sounds like that's not what
> ?prompt=none will ultimately provide.

I'm a little out of the loop, but I *think* the current prompt=none should suffice for what you need. For example, if you're signed in to FxA right now and you visit https://monitor.firefox.com/oauth/init?prompt=none&login_hint=yourSignedInUser@example.com, then the Monitor signing successfully completes without user interaction.

**Comment by 6a68** [comment]
> I don't think this specific bug will help you with the payments-related use-case though, since it's not clear where it would get an id_token from in the first place.

I think requesting the `openid` scope should return an id_token.

> I'm a little out of the loop, but I think the current prompt=none should suffice for what you need

Hey, you're right! I guess that clears the way for @lmorchard to just start using prompt=none for the payments server.

**Comment by lmorchard** [comment]
> but I think the current prompt=none should suffice for what you need. For example, if you're signed in to FxA right now and you visit https://monitor.firefox.com/oauth/init?prompt=none&login_hint=yourSignedInUser@example.com, then the Monitor signing successfully completes without user interaction.

> Hey, you're right! I guess that clears the way for @lmorchard to just start using prompt=none for the payments server.

The current implementation seems to work okay, practically speaking. 

My question, though, is whether the resolution of this issue #2132 will remove that `?login_hint` parameter in favor of `?id_login_hint` - thus breaking that current implementation. That's what the description of the issue sounds like

**Comment by rfk** [comment]
> My question, though, is whether the resolution of this issue #2132 will remove
> that ?login_hint parameter in favor of ?id_login_hint

IMHO we should accept either (as they're both defined by the spec) but not both at once.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

See https://github.com/mozilla/fxa/pull/4818 ( https://github.com/mozilla/fxa/pull/4818 ) for a PR to close out this issue.
