### ISSUE TITLE
Append device name in parentheses where possible for relying parties

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2153]
As the number of relying parties begin to grow, users will need a way to distinguish them between devices. We should include the device name when the services are first attached, and ideally can do this after the fact too.

**Current**
<img width="202" alt="Screen Shot 2019-08-12 at 9 59 52 AM" src="https://user-images.githubusercontent.com/68213/62870763-2fafdd80-bce8-11e9-9944-ef910fb3dcdf.png">

**Proposed**
<img width="277" alt="Screen Shot 2019-08-12 at 9 59 43 AM" src="https://user-images.githubusercontent.com/68213/62870764-30487400-bce8-11e9-8322-4e1b72cc47e1.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-268)
┆Issue Number: FXA-268

**Comment by shane-tomlinson** [comment]
I have wanted this for *so long*.

**Comment by clouserw** [comment]
The example given is probably possible because Notes is an extension so it can access more things.  For normal oauth clients, we don't see how this is possible at first glance.    (thanks jgruen)

**Comment by rfk** [comment]
One way to achieve this would be to try to "group" the OAuth reliers by the sessionToken that authorized them, so that e.g. all of the things you signed in to on "ryan's Firefox on MacBook" would appear grouped with the main device record for "ryan's Firefox on MacBook".  (I believe Shane has suggested something similar in the past, at least in conversation).

That's a big change from what we do currently, but it might be the right mental model for the user.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
