### ISSUE TITLE
"Send Tab" events stopped being tracked on Amplitude

### ISSUE THREAD

**Issue by dianehuang11** [mozilla/fxa#2167]
Ahead of [our A/B test on the new Send Tab tutorial feature](https://github.com/mozilla/fxa/issues/2165#issuecomment-520541756), we need to understand why we stopped tracking Send Tab events back in May 2019.

Amplitude Data: https://analytics.amplitude.com/mozilla-corp/chart/new/pjsr04g

Send Tab Feature Doc for context: https://docs.google.com/document/d/1ppfBNDpALb1ndOJvIlOzakToBAmYuHzN4abxzbCdtCE/edit#heading=h.7ajzt6c0gw5k

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-270)
┆Issue Number: FXA-270

**Comment by dianehuang11** [comment]
cc @davismtl

**Comment by philbooth** [comment]
@jbuck, I used to have a cron job running in EC2 to import these events along with the FxA ones and I think I forgot about it when we migrated the FxA ones to pubsub. If I give you the details, would it be okay to set these up in cron on `fxa-admin` or somewhere else so they're managed by you guys?

It's a couple of scripts from the `fxa-amplitude-send` repo, they read telemetry data from S3 then submit to Amplitude. I can provide you with the details, or wrap them in a Docker container if that's helpful.

**Comment by jbuck** [comment]
@philbooth yep, we can totally run it on the fxa-admin server. If you can wrap them in a docker container (or re-use the existing one maybe?) that'd be great!

**Comment by 6a68** [comment]
I've just learned from @mhammond that send tab metrics may have been removed on the client side when they moved to a new version. There's a WIP patch to restore the metrics on this BMO bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1583897

**Comment by mhammond** [comment]
> There's a WIP patch to restore the metrics on this BMO bug, might be possible to get it uplifted: https://bugzilla.mozilla.org/show_bug.cgi?id=1583897

After which, some magic will need to be done by @irrationalagent to get it into amplitude, which is being tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1586954

**Comment by davismtl** [comment]
Just to clarify, Sync had client-side metrics for sending and receiving. These were somewhat flawed because not all clients generated these metrics. The decoupling work is impacting them.

FxA, on the other hand, tracked Sent Tabs while they were in transit on the server side. These transiting tabs were being tracked in Amplitude. The FxA metrics have a different set of flaws that the client-side ones but they were an accurate estimate of product usage.

I hope this clarifies.

**Comment by 6a68** [comment]
Note also that bug 1583897 will include send tab submissions as part of telemetry, but won't include the part that sends the events to amplitude.

There's a separate BMO bug, https://bugzilla.mozilla.org/show_bug.cgi?id=1586954, to route the send tab data from the telemetry system to amplitude. It's assigned to @irrationalagent.

I'll leave this open as a tracker against the two BMO bugs, but I'm not planning to do further work here.

**Comment by 6a68** [comment]
(Reducing the estimate for my quarterly planning purposes)

**Comment by mhammond** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1583897 has landed, meaning progress can theoretically be made on https://bugzilla.mozilla.org/show_bug.cgi?id=1586954

**Comment by 6a68** [comment]
@irrationalagent Hey, need any help with plumbing the send tab pings into amplitude (bug 1586954)?

**Comment by irrationalagent** [comment]
Yes I would definitely need help with this lol I didn't realize that this was supposed to be on my plate

**Comment by irrationalagent** [comment]
looks like we need to modify this bit https://github.com/mozilla/fxa-amplitude-send/blob/master/sync-events.js to pick up the new version of the events.

**Comment by 6a68** [comment]
I think we want this done by the end of next sprint (train 152), but it's seeming a little bit complicated, based on Leif's [most recent comment](https://github.com/mozilla/fxa/issues/2167#issuecomment-545633545) above. I'll get started on this next.

**Comment by 6a68** [comment]
Resummarizing this issue:

The [amplitude taxonomy doc](https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4/edit#gid=879531055) lists several sync tab send events:
* `sync - tab_transit`, which, it turns out, was never implemented (see https://github.com/mozilla/fxa-amplitude-send/issues/46), contrary to alex's [comment above](https://github.com/mozilla/fxa/issues/2167#issuecomment-539524484).
* `sync - tab_sent` and `sync - tab_received`, events pulled from sync telemetry and submitted to amplitude by the [bin/sync.js](https://github.com/mozilla/fxa-amplitude-send/blob/master/bin/sync.js) script in fxa-amplitude-send. These must be the missing events that caused send tab amplitude to break, since no other events were implemented. (I'm doubly sure, because the fxa-amplitude-send sync code only refers to these two events.)

The missing pings therefore seem to be the sync client pings.

Near the top of this bug, Phil [commented](https://github.com/mozilla/fxa/issues/2167#issuecomment-532089422) that an fxa-amplitude-send cron job needed to be transferred to fxa-admin and restarted. I'm confused by this comment, as a sync processing script is already [in fxa-admin](https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/fxa/puppet/modules/fxa_admin/templates/copy-sync-data-to-amplitude.erb), and has been there [since February 2019](https://github.com/mozilla-services/cloudops-deployment/pull/2934/). TBD.

So: the fxa-admin code _should_ be pulling data from an S3 bucket and passing it to fxa-amplitude-send's `bin/sync.js`, which _should_ be submitting that data to amplitude.

Open questions:

1. Is the client telemetry data still being delivered to the same S3 bucket?
    - For reference, the sync data pipeline as of Nov 2017 is described in [fxa-amplitude-send issue 24](https://github.com/mozilla/fxa-amplitude-send/issues/24#issuecomment-341173459). 
2. Is the fxa-admin cron job actually running?
3. Has the sync event format changed? Meaning, if the data is being sent to S3, and if the cron job is running, is the bin/sync.js code able to process that data?

**Comment by 6a68** [comment]
OK, answering my first question:

> 1. Is the client telemetry data still being delivered to the same S3 bucket? 

Nope.

The sync dataset in question is marked "obsolete" by the data folks: http://docs-origin.telemetry.mozilla.org/datasets/obsolete/sync_summary/reference.html

We'll need to figure out where to get this data now. The S3 import code is basically a one-liner, so it wouldn't be much work to start pulling from GCP instead.

**Comment by 6a68** [comment]
Answering my first question:

> 1. Is the client telemetry data still being delivered to the same S3 bucket? 

It looks like the code that was feeding that S3 bucket is https://github.com/mozilla/telemetry-batch-view/blob/9e679f17a912fa16982f0bb46a2cec379d448a9b/src/main/scala/com/mozilla/telemetry/views/SyncEventView.scala#L18-L19, which hasn't been touched in a suspiciously long time.

There's also a sync dataset marked "obsolete" in the firefox data docs: http://docs-origin.telemetry.mozilla.org/datasets/obsolete/sync_summary/reference.html, though I'm not sure if this is the same sync data or something else.

Also, I re-read this issue, and noticed Leif's [earlier comment](https://github.com/mozilla/fxa/issues/2167#issuecomment-545633545) that we'd need to soon start pulling the data from BigQuery instead of AWS. At least the data should be there somewhere.

---

Going in the other direction, send tab telemetry was re-added by [BMO bug 1583897](https://bugzilla.mozilla.org/show_bug.cgi?id=1583897). It [appears](https://hg.mozilla.org/mozilla-central/rev/15f007ec4cac#l6.128) that the telemetry event we care about is a new implementation of `sync - tab_sent`: Telemetry events with object `"command-sent"` and method `"https://identity.mozilla.com/cmd/open-uri"`.

I don't see a replacement for `sync - tab_received`, but need to dig further.

**Comment by davismtl** [comment]
> which, it turns out, was never implemented (see mozilla/fxa-amplitude-send#46), contrary to alex's comment above.

So strange, I could have sworn we had it but we did have the sent and received events:
https://analytics.amplitude.com/mozilla-corp/chart/new/zgjpryu

**Comment by 6a68** [comment]
Updated with details from Leif:

`displayURI` is sendtab, `processcommand` is receive and `sendcommand` is sent.

The current dataset is the `sync` dataset in BQ. I'm working on getting access.

**Comment by 6a68** [comment]
The fix here involves coordination with the data team, as this data was being pulled from a now-obsolete telemetry data set. The data team can send these events into a GCP queue as they arrive, rather than the daily batch model approach we've used in the past, but they need a little lead time. See https://bugzilla.mozilla.org/show_bug.cgi?id=1601741

**Comment by jbuck** [comment]
It sounds like rather than running this import ourselves, the data team can do [a daily import into Amplitude](https://bugzilla.mozilla.org/show_bug.cgi?id=1601741#c1) - is there a reason we want/need to run it ourselves/have it be real-time?

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Alternative to fixing this bug: FXA-2597

**Comment by rfk** [comment]
(For visibility, the proposed alternative is that we stop sending these metrics because we're not using them anyway)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
