### ISSUE TITLE
Improve Delete account section

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2210]
Two improvements, loosely related.
![delete-sub](https://user-images.githubusercontent.com/68213/63104832-b1ed0b80-bf4d-11e9-9e4b-81fbf6f114cb.png)

**Comment by janiceahn** [comment]
I haven't reviewed this screen yet.

The left alignment makes sense. @LZoog 

We are intentionally not disabling the password field. Imagine that a user wants to delete their account, has pw auto-fill, and this is one case where it won't auto-fill, and he/she doesn't remember pw. Not a good situation, so we are allowing auto-fill. the Delete Account button is still disabled until all boxes are checked.

**Comment by ryanfeeley** [comment]
I'm not sure how it will interact. Ideally the password field is empty and disaled, and when the user checks all the boxes, the password manager kicks in. If it can't work like that, the current interaction is fine.

**Comment by janiceahn** [comment]
If the pw manager kicks in after boxes are checked, then disabling it until
they're checked is fine with me. Otherwise, yes, let's leave the current
interaction as-is.

**Comment by LZoog** [comment]
I'm fairly certain the password auto-fill won't occur if the field is disabled on page load. I can definitely address the text justification, though.

**Comment by janiceahn** [comment]
Great, then let's leave the pw field as-is. Thanks, Ryan and Lauren!

**Comment by ryanfeeley** [comment]
@LZoog Possible to accommodate a copy request from the marketing team? Add the word `paid` before `subscriptions` to reinforce it is unrelated to email subscriptions.

**Comment by LZoog** [comment]
@ryanfeeley can do!

Also, @janiceahn , looping you in on this.

Right now, if a data fetch for `subscriptions` or `clients` fails, I hide the list and the sentence above the list ("You've connected your Firefox account..."). I notice in Ryan's screenshot, there are 0 products listed. Would you like me to hide this sentence also if 0 products are returned? This is actually quite easy since I already have it hidden for errors and because I already have to get the total count to make the list two columns.

Additionally, I noticed the line-height of the checkboxes is different than the sentences above. Would you like me to increase the line-height of the checkbox text to match?

**Comment by janiceahn** [comment]
@LZoog Yes, good point—let's hide this sentence in that case. My thought had been that they would at least be connected to a browser, but I realize that's not true.

Also, thanks for bringing up the checkbox to line heights, as it does look odd right now. Increasing the checkboxes to line height, however, would prob make them too large. @ryanfeeley how do you handle alignment of checkboxes in fxa? Is it bottom-aligned with adjacent copy?

**Comment by LZoog** [comment]
I'll send you both a screenshot side-by-side comparison on that line-height when I get there so you can choose which one you like better. :)
