### ISSUE TITLE
Email preferences not showing up in German

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2217]
It was reported to me by marketing that email preferences are not showing up in German.

English:
![image](https://user-images.githubusercontent.com/19537086/63127690-d0600080-bf67-11e9-82a3-bc36aac3f523.png)

German:
![image](https://user-images.githubusercontent.com/19537086/63131941-5aae6180-bf74-11e9-966d-faedf4ec49f9.png)

I'm not quite sure why. I have not had the chance to verify this but the screenshots convinced me.

**Comment by shane-tomlinson** [comment]
Hmmm, that is a bit worrying, because [de is in the list](https://github.com/mozilla/fxa/blob/c2ecd5bbce9b081dcfde9ccfb584cc6fbd59e4c7/packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/communication-prefs.js#L14) of languages where it should be displayed. Are you set to "de" or "de-DE"?

**Comment by davismtl** [comment]
@shane-tomlinson , @clouserw reproduced with de-DE

**Comment by clouserw** [comment]
Yep.  'de' works as expected 'de-DE' is missing the link.  I also saw a missing link with other locales that aren't in that list above, eg. 'sq'.

When I try Albanian (which isn't in the list above), the text on the page is localized... so... what is the list for if it's not controlling what languages show up on the page?
