### ISSUE TITLE
Server-side solution for duplicate browser sessions when clearing site data

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#2256]
spin-off of #2019

When a user clears their site data, duplicate web sessions show in "devices & apps." They would show in "delete account" as well, but we made a [client-side patch](https://github.com/mozilla/fxa/pull/2216).

This issue is to open the discussion for possible server-side solutions. See #2019 for context.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-285)
┆Issue Number: FXA-285

**Comment by rfk** [comment]
I don't have anything concrete to suggest here, but wanted to summarize the options as I see them.

The trigger here is a signed-in browser doing something to "lose" its current sessionToken - maybe the user clears local site data, maybe they reset Firefox, I don't know. Anyway, when the user tries to use FxA again in that browser, it needs them to sign in again and generate a new sessionToken in order to access their account.

Problem is, nobody told the server that the previous sessionToken has been lost. So when we go to list all the sessions on the user's account, it's still there and appears to the user as a mysterious duplicate session.

There are a couple of ways we could try to do better here:

* We can delete sessionTokens that haven't been used for some time period, on the assumption that they've been lost. We currently do this after 4 weeks, unless the sessionToken is from a Sync signin, in which case they live forever.

* We could try to have the server guess at whether a signin is from the same device as an existing sessionToken, and delete the old one if so. This would need to be based on some sort of fingerprinting of the connecting browser, and would risk disconnecting a legitimate session in the case of a false positive.

* We could try to make it harder for sessionTokens to get lost in the first place. If you're in a browser that's signed in to Sync then we have some special logic for getting that sessionToken out of the browser and into web content rather than making you create a new token. We could consider expanding this logic to cover non-Sync use cases somehow, but it risks coming close to [Chrome's automagic signin thing](https://www.laptopmag.com/articles/google-criticized-automatic-chrome-sign) for which they were largely criticized.

Additional suggestions from folks with fresh eyes on this problem would be very welcome :-)

**Comment by shane-tomlinson** [comment]
> When a user clears their site data, duplicate web sessions show in "devices & apps."

IIUC, previous to PR #2056, we asked users to enter their password to sign into OAuth RPs if they were not already signed into Sync, whether they had a session or not. Each of these password entries would have created a new session, similar to what's happening here. With #2056, as long as the RP is not requesting keys and the user is signed into FxA, we allow them to sign into the RP w/o entering their password. This *should* reduce the number of duplicate sessions that are seen, however a variant of the case outlined here will still not be handled. If a user is *only* signed into OAuth apps and not Sync and then they clear their site data, the user will need to sign into FxA again, and this will generate a new sessionToken.

> We could try to make it harder for sessionTokens to get lost in the first place.... We could consider expanding this logic to cover non-Sync use cases somehow.

The sessionToken the browser holds is re-used for OAuth logins too as long as the user is not in private browsing mode. Users of perma-PB mode will generate a new sessionToken every time they sign into any site IIUC.

I'm +1 on trying to get the browser to not lose the sessionToken, though I thought except for refreshing the profile, this was pretty much solid at this point.

Perhaps as part of the great decoupling, we send the FxA sessionToken to the browser *any time the user creates an FxA session*. The browser could then hold the sessionToken in it's special storage so the sessionToken can be fetched even if the user clears their site data. This won't handle profile refreshes, but will handle pretty much everything else.

**Comment by rfk** [comment]
> Each of these password entries would have created a new session, similar to what's happening here.

Not necessarily, I believe they were using `/session/reauth` for this at least some of the time.

**Comment by shane-tomlinson** [comment]
> Not necessarily, I believe they were using /session/reauth for this at least some of the time.

Only if they were already signed into Sync.
