### ISSUE TITLE
Explore adding 'environment' to Sentry

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2295]
Currently we have our separate dev/stage/prod environments logging to separate projects with names like "content-express-server-prod".  Sentry v9 supports an [environment filter](https://docs.sentry.io/enriching-error-data/environments/?platform=javascript) which lets you tag data when you send it with the environment and then it can be organized under the same project in Sentry.  This would simplify the "projects" view as well as make it easier to compare which issues are appearing in which environments.  

I tried to get this working on our install, but wasn't able to see the dropdown in the top right.  It's possible it would need to be enabled in a config somewhere, or [it's possible that it doesn't work](https://forum.sentry.io/t/sentry-not-showing-environments-tab/4664/7).  

@dannycoates I was using Send to test this because it looked like it was sending the environment tag, and I could filter on it, but didn't see that dropdown.  Can you confirm that you're sending the environment properly in Send before we keep digging here?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-292)
┆Issue Number: FXA-292

**Comment by clouserw** [comment]
+ @jrgm @jbuck for visibility

**Comment by jrgm** [comment]
I set up a test project at https://sentry.prod.mozaws.net/operations/fxa-test/, and pushed some stack traces into it with the script below. Feel free to add more events and/or poke around with the UI (screenshots below).

Notes:
1. You just need to add the `environment` key to the sentry init call and that willl be tracked/shown in UI
2. The value of `environment` is free-form, can be any string, so probably need to agree on standard conventions (e.g., "stage" or "staging"...)

Back to @clouserw since each fxa package will need to change the init call.


```
// See project at https://sentry.prod.mozaws.net/operations/fxa-test/
const Sentry = require('@sentry/node')
Sentry.init({
  dsn: '<look this up under https://sentry.prod.mozaws.net/settings/operations/fxa-test/keys/>'
  environment: 'stage' // this can be any string value; nothing is pre-configured
}
setTimeout(() => AnUndefinedFunction, 1000)
```

<img width="642" alt="shot1" src="https://user-images.githubusercontent.com/758162/64293036-9d82aa00-cf20-11e9-8157-b6f1d9d5725c.png">

<img width="1107" alt="shot2" src="https://user-images.githubusercontent.com/758162/64293080-b9864b80-cf20-11e9-9a87-cb6bab481c94.png">

**Comment by jrgm** [comment]
-Although, yeah, I don't see that dropdown that is documented in https://docs.sentry.io/enriching-error-data/environments/?platform=node (and in the forum question you linked in here earlier). But I also don't see any documentation of any config to "turn something on" on the server side.

(And, yes, what is visible is not a particularly marked improvement over projects-per-environment UI).

**Comment by clouserw** [comment]
Send sends the `environment` key and can be filtered: https://sentry.prod.mozaws.net/operations/send-prod/

But yeah, it doesn't have that dropdown.  So, it sounds like Sentry is maybe just buggy about this and we should just close this one?  That would be fine -- thanks for investigating.
