### ISSUE TITLE
Last sync time on iOS firefox is wrong

### ISSUE THREAD

**Issue by juliemccracken** [mozilla/fxa#231]
Auth token is refreshed every 24 hours so browser isn't checking if it was disconnected. There may be a way to send a push to remotely disconnect the device so it doesn't take the 24 hours to know.  Need to confirm that it has the same behavior on Android.

This was originally filed as a Firefox iOS sync bug, but bug was closed with following comment: This is the expected behavior: the device is indeed syncing, regardless of what you did on accounts.firefox.com, so the timestamp is advancing. It will continue to successfully sync until its cached credentials expire, at which point it will fail to get more from FxA, and will then report an error to the user.

You might consider filing a bug in the Server: Sync component, and/or in FxA, to introduce the coupling required to forcibly lock out devices -- at present there's no real link like that between FxA and the identity-attached service (Sync), so this is not an instantaneous process. The same thing happens in a password change situation, IIRC: it takes a few minutes before a device with a stale password is locked out.

Push would help with timeliness, but push isn't 100% reliable, and it's opt-in for iOS users, and so it can be little more than advisory.

**Comment by rfk** [comment]
> Auth token is refreshed every 24 hours

I think this is *supposed* to 12 hours, we should double-check what the actual duration is.  But the point still stands regardless.

> The same thing happens in a password change situation, IIRC: it takes a few minutes before a
> device with a stale password is locked out.

IIRC there is already a backchannel SQS queue between FxA and Sync in order to deal with this problem - FxA will send a notification that a user has changed/reset their password, and the Sync tokenserver will update its internal state to lock out devices using the old password.  We could try expanding this to also lock out specific devices, although it will require non-trivial engineering work on the sync server side.

**Comment by vladikoff** [comment]
from mtg: file a bugzilla bug for ios component, close this.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1444979
