### ISSUE TITLE
How do we force email first to ignore the cached email?

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa#2334]
How do we force email first to ignore the cached email? 

Is there a param such as `email=none`?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-300)
┆Issue Number: FXA-300

**Comment by rfk** [comment]
Could you please say more about what's driving this question? We're going to need a lot more context on the issue you're encountering if "needs:discussion" is to have any effect :-)

From https://github.com/mozilla-mobile/android-components/issues/4027#issuecomment-525542132 I interpret the root problem here as being "signing out of Sync in Fenix doesn't sign you out of accounts.firefox.com", and we may be better served by arranging for that signout to happen reliably rather than adding a mechanism to ignore the web-content's state in some cases.

**Comment by rfk** [comment]
> web content state (e.g. sessionToken) is ignored if fxa-status says null

Sure, this seems like it will work to resolve the issue described. Would this apply only when loading web content with the special `context` query param?

My slight concern here is if it's treating a symptom of a larger problem, we might make that specific flow better but leave other edge-cases that we'll discover later.  If the webchannel work means that Fenix and accounts.firefox.com end up holding the same `sessionToken`, then you can probably implement a more complete fix without having to add any special "ignore cached state" behaviour: have Fenix destroy the `sessionToken` on signout, and web content will discover that it's invalid and discard its cache state without any special treatment.

**Comment by shane-tomlinson** [comment]
After reading #4027 and #4236, I'm confused as to the problem. Is the problem that FxA continues to show the previously signed in user and just allows the user to enter their password to sign in again? If so, this is how desktop works too so that users can easily sign in again. If that's *not* the desired behavior, rather than adding extra stuff to the WebChannel message, I think it'd make more sense to use [`prompt=login` from the OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) so that all RPs can make use of it.
