### ISSUE TITLE
Duplicate login complete metric events since train 144

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#2343]
If we look at the TOTAL number of login complete events across all services, they seem to be way up

![image](https://user-images.githubusercontent.com/5625313/63873278-8a019d00-c97c-11e9-89c0-881270615534.png)

But if we look at THE NUMBER OF USERS generating that event, its up only modestly

![image](https://user-images.githubusercontent.com/5625313/63873356-ab628900-c97c-11e9-889f-b985a8d39f3b.png)

Looking at individual user paths, its clear that some are generating duplicate events now
![image](https://user-images.githubusercontent.com/5625313/63873411-c7fec100-c97c-11e9-919c-d1d409863435.png)

First thought is that its somehow related to https://github.com/mozilla/fxa/pull/2224 but not sure yet... will continue to investigate.

Since we typically only count unique users this isn't an emergency emergency but we should still try to find the cause and get a fix out

cc @davismtl

**Comment by philbooth** [comment]
@vbudhram, iiuc, you want to filter the content server logs for amplitude events rather than flow events. The bugs is that you should see `fxa_login - complete` in both the auth and content servers.

**Comment by philbooth** [comment]
So, speculating purely based on reading the code, I think the correct fix here is to do something in `app/scripts/views/mixins/cached-credentials-mixin.js` because that seems to be the common path that is executed when the sign-in doesn't manifest as a request to the auth server.

Specifically, I think we should:

1. Inside `useLoggedInAccount`, if the call to `this.signIn(...)` is successful, log some kind of `signin.cached.success` event.

2. In `server/lib/amplitude.js`, change the mapping for the complete event from `signin.success` to `signin.cached.success` (or whatever we decide on).

With that in place, the desired outcome is for the content server not to emit a `fxa_login - complete` event in any of the flows where the auth server emits it. However, in the cached signin case, where the auth server doesn't emit any `fxa_login - complete` event, the content server should emit it instead.

Again, that's only based on reading stuff and I'm off on PTO in the morning so haven't got time to investigate properly. Apologies if it turns out I'm wide of the mark!

**Comment by clouserw** [comment]
Based on commits we think this is fixed (and live).  I'll close this -- @irrationalagent can you confirm this on your end?
