### ISSUE TITLE
Ensure source maps show up in Sentry

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2345]
Lots of the errors in sentry are in our JS bundles.  Let's add sourcemaps so we can decipher them.

Example: https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/6177303/

**Comment by meandavejustice** [comment]
Sentry sourcemaps are working on content server in my branch, I've run into a bit of trouble with configuration of the sourcemaps on the payment server, I think this may have to do with use using `react-scripts`, I had to bring in a separate package in order to override the default webpack config.

I've switched off of this until I finish the other issues in the current milestone, but will hopefully get back to it before the end of the week.
