### ISSUE TITLE
Rate limit OAuth access token creations

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2397]
One of the suggestions by @jvehent during the security review of the secure proxy is to rate limit the number of OAuth access tokens a given user can create for a given service over a period of time. Rate limiting in this manner is to prevent users from either 1) DDOSing us via token creation, and 2) abusing an RP with a multitude of tokens.

Some details that need to be figured out:

* Do we rate limit by client_id or by [resource indicator](https://github.com/mozilla/fxa/issues/1817)?
* What is a reasonable limit and what is a reasonable time window?
  * Do different limits apply to different client_ids or resource indicators?
  * Is there any notion of a maximum number of tokens across *all* services?
* What do we show users if an OAuth authorization request occurs via out front end
* How should RPs respond if they go to fetch an access token using a refresh token?

Similar to #1811 which is to rate limit PPID sub rotations

cc @bakulf

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-321)
┆Issue Number: FXA-321

**Comment by chelsea-lewis** [comment]
- This is a good idea and a low priority as Secure proxy is doing their own accounting. However, we SHOULD do this because it could cause a significant issue in the future.
- AWS WAF or nginx is an option in an emergency.

1. Do we rate limit by client_id or by resource indicator, or by IP Address?
(Secure Proxy requests 2 tokens every time. Resource indicator is what is used to scope those tokens to the individual services.)
Recommended some combination of IP & client_id or resource indicator

2. What is a reasonable limit and what is a reasonable time window?
Likely would depend on relying party. 

2a. Do different limits apply to different client_ids or resource indicators?
Yes, probably.

2b. Is there any notion of a maximum number of tokens across all services?
Maybe.

3. What do we show the users if rate limited?
Needs Product. @davismtl 

4. How should RPs respond if they go to fetch an access token using a refresh token?
If we implement rate limiting, we should implement rate limiting separately for RPs than for the end users.
Should not need to rate limit our RPs, instead rate limit authorization code grant

**Comment by davismtl** [comment]
> What do we show the users if rate limited?
> Needs Product. @davismtl

If the user is in a login or registration funnel, we should show one of our existing rate limit message.  (i.e. please try again later)

If it's a refresh to an existing session, it's unclear to me how we would surface it for a relying party. At the very least, we should return a descriptive error message to the RP that they can try to handle. Maybe in the future, we leverage our Bento/Account menu which should be visible across all sites and service.
