### ISSUE TITLE
login problems in FF 55?

### ISSUE THREAD

**Issue by newsjunkie247** [mozilla/fxa#256]
Is there some reason why I can't seem to login to Firefox Accounts in Nightly 55, which is also affecting sync and ability to log in for addon verification? I think it was working a few weeks ago and I didn't change anything on my end as far as I know. Same issue in different accounts using same Nightly 55 version.. It works in Nightly 56 but I have other reasons why I'm not really ready to use that regularly yet. I just get a spinning wheel. I saw some mention of privacy settings in relation to another problem, but I don't think I have that setting enabled.

**Comment by shane-tomlinson** [comment]
@newsjunkie247 - Thanks for the report - It is likely that the version of Firefox 55 Nightly that you are using does not yet have support for responding to the `fxaccounts:fxa_status` message that you [mention in this issue against the content-server](https://github.com/mozilla/fxa-content-server/issues/5171).

Firefox 55 is now in Beta, it is no longer on the Nightly channel. Nightly has moved on to Firefox 56. Since Nightly is a test bed for landing new features, old versions of Nightly are not supported. To get around this issue, you can either use Firefox 55 Beta, or a newer version of Firefox Nightly.

If you still have problems after updating, can you let me know? Thanks again for the report!
