### ISSUE TITLE
“Terms of Service” and “Privacy Notice” pages are not opened in new tabs

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#2573]
**Steps to reproduce:**
1. Go to https://accounts.stage.mozaws.net/signup?service=sync&context=fx_desktop_v3&entrypoint=menupanel
2. Left click on “Terms of Service” and “Privacy Notice” links which are displayed under the “Create account” button.

**Expected results:**
“Terms of Service” and “Privacy Notice” pages are successfully opened in new tabs on left click.

**Actual Results:**
“Terms of Service” and “Privacy Notice” pages are opened in the current tab on left click.

**Additional notes:**
This issue reproduces on FxA-stage and FxA- production using Firefox 69.0.1 under Windows 10 64-bit.

![terms and privacy](https://user-images.githubusercontent.com/18114210/65420022-cce25380-de08-11e9-8d9f-4f9d1415ffeb.gif)

**Comment by shane-tomlinson** [comment]
This won't work on Firefox for iOS where we can't load new tabs, but could in other environments. The original reason we opened these inline is because Firefox desktop was unable to open the agreements in a new tab. The other concern was user dropoff because every time we open a new tab, some percentage of users fail to make it back to the original tab.

cc @ryanfeeley for input

**Comment by ryanfeeley** [comment]
@shane-tomlinson @vasilicatamas If by left-click you mean default click, it should open in the same tab like a default link. It does work like that, but also supports command-click (Mac) to open in a new tab if users want to do that.
