### ISSUE TITLE
Stop using lineHeight on react stripe elements

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/fxa#2580]
```
The use of the style property lineHeight is discouraged, because it can lead to visual inconsistencies among various browsers. Consider using a padding on the Element’s container instead.
```

https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/components/PaymentForm/index.tsx

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-365)
┆Issue Number: FXA-365

**Comment by meandavejustice** [comment]
low priority

**Comment by PalAditya** [comment]
Hi, I would like to help out with this issue if possible. Is the above file the only place where the property needs to be tweaked?

**Comment by meandavejustice** [comment]
Hey @PalAditya the corresponding test will need to be updated as well, https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/components/PaymentForm/index.test.tsx

**Comment by LZoog** [comment]
I just looked into this out of curiosity.

I was going to ask if we use `reset.css` or `normalize.css` to take care of any weirdness around using `line-height`, but it would not apply to these elements since they're in an iframe.

It looks like `lineHeight` from our `.tsx` just affects these guys.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/13018240/66325084-3f186500-e8ec-11e9-8fcc-0eb3fb5c046e.png">

@PalAditya try to see if you can find a CSS property that the console won't complain about with the same visual effect as line-height. Maybe [padding or height](https://github.com/stripe/react-stripe-elements/issues/51) will work. Looks like the test Dave pointed out might be the only other file this needs updating in.

**Comment by PalAditya** [comment]
Noted. Will try to use padding around the container and make a PR as soon as possible :)

**Comment by LZoog** [comment]
@PalAditya great, thank you! It doesn't look like we have this in our front-page docs, but once you get everything running and you locally sign up for an account/verify it, you can see this console warning at: 127.0.0.1:3030/subscriptions/products/321doneProProduct

**Comment by clouserw** [comment]
@PalAditya are you still working on this?
