### ISSUE TITLE
Enhancement: "Stay safe ..." from password bubble to be displayed also on Mobile

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#2591]
Steps to reproduce:
1. Go to https://accounts.stage.mozaws.net/signup?service=sync&action=email on desktop and mobile
2. Type 2 characters and wait for password hint to be displayed.
3. Pay attention to desktop and mobile bubbles. 

Expected result: the password bubble are the same on all platforms.
Actual result: "Stay safe - don't reuse passwords." is not displayed on mobile devices.

![Screenshot_46](https://user-images.githubusercontent.com/24588037/65504656-25c8ef00-ded0-11e9-977d-276cf6df5f02.jpg)

**Comment by shane-tomlinson** [comment]
cc @ryanfeeley - I am not sure if the same rules apply to the updated bubble, on the old bubble on mobile we did not show that first line because it caused part of the bubble to go under the screen when the virtual keyboard was displayed. Perhaps in the smaller base form factor, that's no longer an issue and that first line can always be displayed?

**Comment by clouserw** [comment]
@ryanfeeley we're triaging now and don't think that line was in the mobile spec.  Do you want this bubble to have that line or not?  Thanks

**Comment by ryanfeeley** [comment]
No room on mobile as per spec https://mozilla.invisionapp.com/share/5UM3J3TXWMR#/316338169_Artboard
