### ISSUE TITLE
Refomat SVGs to be more consistent

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#2596]
I noticed that [our SVGs](https://github.com/mozilla/fxa/tree/master/packages/fxa-content-server/app/images) preview differently in macOS.

https://youtu.be/YbzOx2_84Do

Some appear to fit the preview window, others are fixed in size. Some have colour fill specified, others appear black. I'm not sure the solution, but I assume giving them a once-over might help us out, especially as dark mode is requiring us to have our assets in tip-top shape.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-371)
┆Issue Number: FXA-371

**Comment by LZoog** [comment]
We have some SVGs with the width/height set in the code, like `width="200px"`. When we inline like this, the preview will appear at this size. When we use non-inline code to set width/height, such as using an SVG as a `background-image` and setting a width on the container, you'll see the stand-alone SVG fill up the entire preview window. It looks like that's what's happening here.

I personally prefer to set the width on the container because it makes the image a bit more agnostic (if we use it twice, we can set the width/height without needing to override), _but_ that will cause massive previews for UX in GitHub. It would be nice if these were more consistent, but it will take a bit of time to go through every one and we'd definitely want some regression testing if/when we decide to move forward with one or the other.

As far as the `fill` goes, that can be more easily addressed - are there certain black icons that should be another color? Assuming they're exported correctly, we can likely add `fill` inline on the paths.

**Comment by ryanfeeley** [comment]
@LZoog I made a PR a week or two ago to make some the blues consistent. I think our greys are good. Mainly I just want to make sure they have had a good once over, so the quality level is set. Am all for removing size from the SVGs too.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
