### ISSUE TITLE
Infinite Loading on Create Account/Sign In from What's New page on stage.mozaws.net

### ISSUE THREAD

**Issue by AlinOIlea** [mozilla/fxa#2606]
Environment:
Windows, stage server

Steps for Create a new account:

    1. Open Firefox
    2. From hamburger menu select "What's new" and click on "Firefox now fights harder for your privacy".
    3. Click on "Get a Firefox Account" button (in the upper right corner)
    4. Complete all fields with valid credentials, click Create account button.

Steps for Sign In with an already registered account:

    1. Open Firefox
    2. From hamburger menu select "What's new" and click on "Firefox now fights harder for your privacy".
    3. Click on "Get a Firefox Account" button (in the upper right corner)
    4. Click on "Have an account? Sign in", enter the credentials for an already existing and verified account and click Sign in button.

Expected result:

    1. For Create a new account steps, the user is able to create a Firefox account.
    2. For Sign In with an already registered account steps, the user is able to Sign In into their account.

Actual result:

    1. For Create a new account steps, after the user complete all fields with valid data and click on Create account button, the page gets stuck in an infinite loading.
    2. For Sign In with an already registered account after the user complete the fields with credentials for an already existing and verified account and click on Sign In button also the page gets stuck in an infinite loading.

**Comment by dannycoates** [comment]
This isn't going to work on stage because the "What's new" link[1] points to production. When the browser is configured to use stage, the url needs to point to stage otherwise the webchannel fails and the page is broken.

1 - https://accounts.firefox.com/signup?service=sync&entrypoint=mozilla.org-globalnav&context=fx_desktop_v3&utm_source=mozilla.org-globalnav&utm_medium=referral&utm_campaign=globalnav&utm_content=get-firefox-account

**Comment by krupa-raj** [comment]
Is there a pref within the browser that we can set to point to stage?
