### ISSUE TITLE
(Phase 2) Recovery Keys and Secondary Email at Registration

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2653]
We’ve always had a steady volume of users complaining or reaching out to us via Bugzilla, SUMO, Twitter and Reddit due to being locked out of their accounts.

There are three reasons for this:
- They don’t have access to their email anymore;
- They forgot their password;
- They lost their device for TOTP.

This feature proposes to tackle the first two. The impact of the first reason is that users can’t get into their accounts. The impact of the second reason is that users risk losing their Sync data if they do not have more than 1 device actively Syncing.

In this second phase, we will also send users an email immediately after registration to encourage them to setup a recovery key and a secondary email. This email will *NOT* link to the settings like phase 1. For phase 2, we will link people to a screen that can be used from various places like our login flow and account toolbar menu in the browser.

Feature document: 
https://docs.google.com/document/d/1fJA_wfrgVF4cuQVzoWqQh22kiejDHbXJrkzTNuVldII/edit#

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-383)
┆Issue Number: FXA-383

**Comment by davismtl** [comment]
Secondary email after login:
https://mozilla.invisionapp.com/share/5JUK0JFFN3M#/390502550_Secondary_Email_Recommendation

**Comment by clouserw** [comment]
Please add the issues to this epic.  thanks

**Comment by davismtl** [comment]
from mtg:
This is now in progress. Just need to link out to bugs now.

**Comment by davismtl** [comment]
This will be going out in January.

**Comment by vbudhram** [comment]
* Code has landed to verify secondary email via a code.
* Started working on the UX for secondary email after registration

**Comment by davismtl** [comment]
Should we enable this as an experiment for adding a secondary emails in the flow?
@vbudhram @irrationalagent @davismtl to sync up on this.

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

[~vbudhram@mozilla.com] , Ryan Feeley and I have been updating the feature document to unblock you.

What is left?

  * Ryan is reviewing the copy because we don't like it.
  * He's making small changes to the design to account for two ways people can see the standalone recovery key flow
    * linked directly (e.g. email, eventually maybe toolbar menu)
    * in an auth flow like login or registration)

  * Ryan should have these done today or tomorrow at latest.

What has changed?

  * The copy will try to outline the benefit and strategic differentiation about how we handle data to underline the importance of a recovery key
  * In phase 2, based on Leif's analysis, we will likely just focus on recovery keys in the email. Users are responding to it better and we believe it will benefit more people given the volume of password resets.

See feature doc here. ( https://docs.google.com/document/d/1fJA_wfrgVF4cuQVzoWqQh22kiejDHbXJrkzTNuVldII/edit#heading=h.nf5jpsmtc84v )

**Comment by data-sync-user** [comment]
➤ Alex Davis commented:

Vijay is working on having users confirm they've downloaded their recovery keys in the upcoming train.

The majority of UX will land in this train.
