### ISSUE TITLE
How does Pocket handle primary email change?

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2654]
I was reading through FxA related support tickets and landed on this one.
https://support.mozilla.org/en-US/questions/1256736

Does Pocket support primary email change yet?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-384)
┆Issue Number: FXA-384

**Comment by shane-tomlinson** [comment]
They should be. This is one of the big reasons we started recommending that RPs key by uid rather than email address. Trying to find a bugzilla bug, so far nothing found.

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/5842

Pocket should be listening for `primaryEmailChanged` notifications from SQS, and handling those.

**Comment by vbudhram** [comment]
@davismtl I tested this out and it kind of works. I say kind of because the pocket lists were kept the same after changing primary email on FxA. 

However, the pocket UX did not reflect the new email address. After inspecting the account that is stored, it seems like the page should respect the `originalLoginEmail` value which is set when users change their email.

<img width="808" alt="Screen Shot 2019-10-28 at 10 38 20 AM" src="https://user-images.githubusercontent.com/1295288/67687982-8041e900-f96f-11e9-9e53-3772e667354c.png">

I think the *right* thing to do here is create a new property on the account object that stores what should be hashed with the password. That way we can get rid of the confusing `originalLoginEmail` and just set `email` to the user's current email address.

**Comment by rfk** [comment]
> I think the right thing to do here is create a new property on the account object
> that stores what should be hashed with the password.

If you do end up working on such a thing, please consider taking the opportunity to add verifier versioning along the lines of the proposal in https://github.com/mozilla/fxa/issues/512 (which proposes a `quickStretchSalt` property that sounds very similar to what you're proposing here).
