### ISSUE TITLE
FxA Toolbar Menu - Decoupling of Sync (Fx 71)

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#2682]
┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/FXA-391)
┆Issue Number: FXA-391

**Comment by davismtl** [comment]
Everything is merged and in Nightly.

Nothing to measure. Just track for regressions.

Going as expected.

**Comment by irrationalagent** [comment]
See the bottom three charts on [this dashboard](https://sql.telemetry.mozilla.org/dashboard/new-fxa-sync-probe-location) to monitor the new fxa/sync configured probe location. 

Currently, this probe indicates that among users who have a definite value set, about 94% of clients that have fxa_configured set to true, also have sync_configured set to true. 

However, according to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1582253) the values for this probe should almost always never be null (should be set explicitly to true or false) but its fill rate only seems to be at about 20%, so we should follow up with sync engineering to figure out what might be going on here.

**Comment by irrationalagent** [comment]
So according to markh, when both the sync and fxa probe are null, we can infer that neither of them are setup on the client, e.g. that they could be treated as false. When sync will be set explicitly to `false` when fxa is on but sync is not. FxA being explicitly set to `false` should not happen. It does seem to occur, but at really small volume.

**Comment by irrationalagent** [comment]
Summarizing what we know about this so far:

1. Based on [this chart](https://sql.telemetry.mozilla.org/queries/66707#169110) (client-side telemetry) about 6% of clients that report fxa turned on have sync turned *off*.

2. The server-side metrics indicate that the ratio of unique users generating the `cwts_do_not_sync` event to users completing the [login OR reg flows is about .06](https://analytics.amplitude.com/mozilla-corp/chart/sib46yr). For reg only it is currently a bit higher, maybe around [.07-.08](https://analytics.amplitude.com/mozilla-corp/chart/vcusnhz). Both ratios were about double that in the period immediately after the 71 release.  

3. For users starting out the auth flow (login or reg) about [2-3% of them ultimately choose not sync](https://analytics.amplitude.com/mozilla-corp/chart/wgi3rat).

Overall, I would say the numbers aren't totally crazy, BUT:
1. Naively, I would expect the client-side measures would indicate a smaller percentage of FxA users with sync turned off, since that's supposed to measure ALL users that have FxA on, not just those going through the auth flows. Instead, its only slightly smaller than the server side ratios that indicate how many clients turn off sync *during the authentication flow*. 6% is also just barely in the realm of gut-feeling-this-is-plausible for me. 

2. As discussed in #3734, we should confirm that [we are properly logging](https://analytics.amplitude.com/mozilla-corp/chart/0f1rqp9) `complete` events after a user turns sync off during the auth flow (given the discussion there I think the real problem has to do with the email confirmation event, but we should confirm).

**Comment by davismtl** [comment]
@irrationalagent I'm observing that in the initial Amplitude charts charts you shared, you're looking at all the flows in general.

What motivated you to do that rather than look at only the entrypoints (or the `service`) leveraging the Sync-optional flow?

Is there a distinction to be made between certain entrypoints? For the entrypoints where we don't use Sync-optional, should we consider using it in light of your results?
