### ISSUE TITLE
send an “engagement” metrics ping from Monitor

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fxa#2743]
We would like to send an “engagement” ping from Monitor if our visitor came from one of our breach alert email links.

We’d like to be able to attribute this valuable engagement that our subscribers have with Monitor, even if they don’t sign in to the site.

We could definitely include (Monitor) uids in the email links sending them back to Monitor, and then look up their FxA uid to include in the ping.

cc @irrationalagent 

_edit: related to https://github.com/mozilla/blurts-server/issues/1191_

**Comment by irrationalagent** [comment]
So this would (again) involve changes to this endpoint https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/server/lib/routes/get-metrics-flow.js

One thing we have talked about in the past is expanding this endpoint to allow RPs to log events that relate to product usage, rather than authentication. For example, we could have one catch-all event like `fxa_activity - rp_active` or something that would subsume whatever specific actions the rp wants logged. For 2020 we are definitely looking to measure more granular events that indicate a user is getting value out of the product (rather than just authenticating) so this would be a step in that direction.

**Comment by groovecoder** [comment]
Based on Slack conversation, we'll send our own Monitor UID in the email link, and when the user comes back to monitor.f.c, we'll include their FxA UID in the ping to `metrics-flow`.

@6a68 - does that un-block you from updating `metrics-flow` endpoint to receive these kinds of engagement pings?

**Comment by 6a68** [comment]
I _think_ so. I'll follow up with Leif to understand what exactly needs to be changed in that endpoint

**Comment by irrationalagent** [comment]
@groovecoder @6a68 

Here's a brief overview of how I think we could do this:

1. https://github.com/mozilla/fxa/blob/46bc33d45c0d9cdf14adf62fb474093ecd69ccd3/packages/fxa-content-server/server/lib/routes/get-metrics-flow.js#L46-L64 FxA expands this ^ to accept new `uid` and `event_type` params
2. When the monitor server detects a user returning to the monitor site via email, they make a call to that endpoint ^ with the user's `uid`, event_type = `engage`, service = `fx-monitor` (or do we need the oauth client_id here instead? i know the amplitude pipeline code maps `service` from the oauth client_id, but I *think* its ok we just pass the `service` string directly. we should confirm)
3. FxA logs a new amplitude event type `fxa_rp - engage` with the relevant uid and `service`. 

I think this is the cheapest most generic solution. It only allows RPs to log one type of event. if they need to log multiple different types, we will have to handle different values from `event_type`. I think we would prefer to limit the scope at this point, but @groovecoder do you think you will need to log more than one type of event?

**Comment by irrationalagent** [comment]
We are going to consult with data steward-type people about this

**Comment by 6a68** [comment]
Reminder for myself: if the ping format needs to include client ID, not client name, let groovecoder know.

**Comment by rfk** [comment]
>  if the ping format needs to include client ID, not client name

FWIW...if you mean the OAuth `client_id`, I would argue that you should indeed include this value in the ping rather than a human-readable client name, and rely on the existing logic in the FxA event pipeline that maps client_ids to readable names. Otherwise we risk config in different places getting out of sync.

**Comment by juliemccracken** [comment]
Might not go out with train-150. Depends on how quickly we hear back from legal. Will discuss in the Nov. 4th legal review.

**Comment by davismtl** [comment]
I've looped in Michael Feldman to this discussion during our bi-weekly legal sync up. He will speak to Alicia Gray tomorrow.

**Comment by 6a68** [comment]
@rfk Hmm. Do you happen to know where I can find the existing logic that maps client_ids to readable names? I'm confused, because this get-metrics-flow endpoint doesn't have a `client_id` parameter, but does have a `service` parameter, with a regex that looks like it might allow for either a few special strings, like "sync", or a `client_id` (16-digit hex number):

https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/server/lib/validation.js#L29

Here's the client_id validator. It's the only one in the same `validators` file that's exactly 16 chars in length, but that doesn't convince me I'm right:

https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/server/lib/validation.js#L20

**Comment by 6a68** [comment]
Aha, answering my own question, the mapping is specified in content-server config as `oauth_client_id_map`, https://github.com/mozilla/fxa/blob/fedc92bccb6dff7bbd86c06b4b7c90f387fc6887/packages/fxa-content-server/server/lib/configuration.js#L386-L395 and it's passed into amplitude as the first argument to the `initialize` method, https://github.com/mozilla/fxa/blob/fedc92bccb6dff7bbd86c06b4b7c90f387fc6887/packages/fxa-shared/metrics/amplitude.js#L124-L125 https://github.com/mozilla/fxa/blob/fedc92bccb6dff7bbd86c06b4b7c90f387fc6887/packages/fxa-shared/metrics/amplitude.js#L141

**Comment by 6a68** [comment]
As a reminder, we'll need to add the fx-monitor engage event to the [amplitude taxonomy doc](https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4/edit#gid=879531055) when this lands.

**Comment by 6a68** [comment]
We'll also need to make sure the CORS config on stage and prod allows /metrics-flow to accept input from monitor's stage / prod domains.

**Comment by 6a68** [comment]
The data collection review is still in process (https://bugzilla.mozilla.org/show_bug.cgi?id=1594388) and I'm still working on the code. Planning to do a point release when this lands, to get it out week of Nov 18 as planned.

**Comment by 6a68** [comment]
Data collection is approved. I have this working, adding tests, will have PR open today.

**Comment by 6a68** [comment]
Reopening: I validated with the "unique user ID", which is 36 chars, but the fxa uid is actually 32 chars 🤦‍♂

**Comment by 6a68** [comment]
This is fixed in #3393, which landed straight into the `train-150` branch for release today. Closing.
