### ISSUE TITLE
[fxa-payments-server] Handle stripe tokenization errors like test card use in prod

### ISSUE THREAD

**Issue by bbangert** [mozilla/fxa#2812]
When a test card is used in prod, the error is:

![image](https://user-images.githubusercontent.com/100193/66504390-dd880000-ea7d-11e9-8cfc-222e0af6756e.png)

When looking at my network explorer, I see a 402 POST to api.stripe.com at /tokens, with the following response:
```json
{
  "error": {
    "code": "card_declined",
    "decline_code": "live_mode_test_card",
    "doc_url": "https://stripe.com/docs/error-codes/card-declined",
    "message": "Your card was declined. Your request was in live mode, but used a known test card.",
    "param": "",
    "type": "card_error"
  }
}
```

We should display an error indicating the user has entered an invalid card instead and review what other Stripe errors we handle.

**Comment by LZoog** [comment]
A temporary error message update was done in #2914. 

This issue is blocked from being resolved until @johngruen has time to work with someone else on better error messaging.

**Comment by LZoog** [comment]
It looks like we handle this error based on `createTokenError.type`, as with all Stripe errors. We don't have one specifically set for type `card_error` in `errors.ts` so we're displaying the generic message.

We _are_ checking for `code === 'card_declined'` if there is a `createSubscriptionStatus.error`, however, which we receive from `/v1/oauth/subscriptions/active`. It seems like the fix for this particular messaging would be to copy, or possible just move, the check for `code` into `createTokenError`.

This relates to https://github.com/mozilla/subhub/issues/98, in which @jackiemunroe states: "Also, from a security standpoint, we probably don't want to tell users why their card was declined, just that it was," so maybe we don't want to display what's returned from `message` here. @johngruen, should we have that error messaging meeting soon and move this to the next train, or would you prefer I go ahead and create a patch for this error in particular (and if so, what should it read besides a "Your card was declined." heading?) to close this out?
