### ISSUE TITLE
Convert the password reset flow from link based to code based verification

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2815]
Like the equivalents for the signin/signup flows, converting the password reset flow from link based to code based verification would probably result in a higher completion rate.

Doing so would also allow us to [remove hundreds of lines of polling code](https://github.com/mozilla/fxa/blob/c759ba95c659d0bc527a2bff34a2ffcf9f83c1cb/packages/fxa-content-server/app/scripts/views/confirm_reset_password.js#L57:L248) that is necessary to handle users confirming in a 2nd tab or device. Yuck.

blocks #2814

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-422)
┆Issue Number: FXA-422

**Comment by davismtl** [comment]
I just went through this flow when trying to sign in to a RP. Since it opened a new link, it was "unclear" to me how to return to the RP after my successful password reset.

Meanwhile once I found the tab where I had started the reset, I was pleased to see that it had advanced me into the RPs flow.

Codes would make it much easier to get back into RP's flow.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
