### ISSUE TITLE
Minor styling issue: orphan with login panel.

### ISSUE THREAD

**Issue by tublitzed** [mozilla/fxa#2926]
## Description

Minor text issue seen in nightly; widow in Firefox Send description:

![Screen Shot 2019-10-15 at 4 10 22 PM](https://user-images.githubusercontent.com/1756056/66866096-9b235f00-ef66-11e9-894f-f92610b27b64.png)

### Steps to reproduce
Visit [this URL](https://accounts.firefox.com/?service=sync&context=fx_desktop_v3&entrypoint=fxa_discoverability_native). I got here by trying to sign into my account.

### Expected result

Text should be re-styled, or padding adjusted so that text wrapping doesn't create orphan of the word "eyes".

### Actual result

Text wrapped :)

### Environment

Prod

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-441)
┆Issue Number: FXA-441

**Comment by johngruen** [comment]
IIRC this copy is all changing soon, but yeah this is gross...hard to avoid with l10n tho

**Comment by johngruen** [comment]
Paging Professor @ryanfeeley

**Comment by LZoog** [comment]
@tublitzed thank you for opening an issue :)

Agreed, @johngruen. If we're going to be updating this copy soon then I'd just recommend leaving it as-is but we'll see what Ryan says. I'd normally advise against padding adjustments for copy line breaks anyway in case we know it's going to be static for quite some time, otherwise we're stuck micro-adjusting per every copy update, and especially with language translation as you mentioned.

**Comment by clouserw** [comment]
I'll mark this as needs:ux since y'all got here first, but with L10n there isn't much we could do about a word wrapping to the next line.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

the VPN has replaced Send here so marking this fixed
