### ISSUE TITLE
Investigate unexpected changes in Amplitude events on May 2nd, 2018

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#296]
On May 2nd, the email click rate went way up, but retention was way down.

See https://analytics.amplitude.com/org/31251/chart/m0j0d4n
and https://analytics.amplitude.com/org/31251/chart/8kkdy18

cc @philbooth, @irrationalagent

**Comment by philbooth** [comment]
The first one is expected, it's the fix from mozilla/fxa-content-server#6044. The second one is the one I don't have an opinion on yet.

**Comment by irrationalagent** [comment]
@shane-tomlinson that retention chart is plotting 7 day retention for each calendar day, meaning that (IIUC) the data point for each day is the *percent of users who registered on that day that showed up 7 days later*. since we didn't have any data at all last wed-thu (ish), **this wed-thu** our retention will be very very bad.

**Comment by shane-tomlinson** [comment]
> since we didn't have any data at all last wed-thu (ish), for the new data computed for this wed-thu (i.e. now) our retention will be very very bad.

Got it. I didn't realize that's how it worked.

Thanks @philbooth and @irrationalagent. From the sounds of it, this is safe to close.
