### ISSUE TITLE
Generate Dockerfiles from templates

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa#2990]
Our Dockerfiles have a lot of duplication and a lot of near-duplication to do similar tasks. Maybe we could improve them by using a templating library to generate the Dockerfiles.

**Comment by dannycoates** [comment]
I was toying with the idea of having a "monodocker" instead of an image per service. I think it offers a few advantages:

- code sharing is easier since all source is available by default. today it's a bit awkward to copy the shared code into each image
- less total docker code, all in one place
- never any question of mismatched service versions
- these are more fuzzy
  - probably easier to maintain
  - could lead to faster ci times
  - might be easier for ops to manage

My big concern here was image size so I made a prototype that isn't _too much_ bigger than any of our other images https://hub.docker.com/r/dannycoates/fxa

**Comment by dannycoates** [comment]
see also #785

**Comment by dannycoates** [comment]
@jrgm and @jbuck what's your take on a single docker image?

**Comment by jbuck** [comment]
> @jrgm and @jbuck what's your take on a single docker image?

Interested! I imagine most of the size of the docker image comes from the base OS and the `node_modules` directory. And I see with your docker image that's totally correct.

So, yeah, I think this is worth pursuing!

**Comment by lmorchard** [comment]
Just taking a peek at this... Looking at [content-server](https://hub.docker.com/r/mozilla/fxa-content-server/tags) (~217mb) vs [monoimage](https://hub.docker.com/r/dannycoates/fxa/tags) (~390mb), it looks like not quite double. Is that a fair comparison?

That said, at least it's not an order-of-magnitude change :) And even though this one image is larger, it's one image to push & pull & cache, so I'd think that it would be an overall improvement and simplify a lot of things?

**Comment by dannycoates** [comment]
s/390/360/ 😉

**Comment by lmorchard** [comment]
I think I was upside down when I read it

**Comment by dannycoates** [comment]
duping to #785
