### ISSUE TITLE
It takes two "Revoke" clicks to actually revoke device access

### ISSUE THREAD

**Issue by rlr** [mozilla/fxa#3017]
## Description

When I go to the FxA settings page to revoke access, it takes two clicks of the Revoke button to actually revoke.

### Steps to reproduce

- Sign into a site/app that uses FxA. https://monitor.firefox.com/ for example
- Go to https://accounts.firefox.com/settings
- Expand "Devices & apps"
- Click "Revoke" button for the site. "Firefox Monitor Last active a few seconds ago", for example.
- Click the "Refresh status" button below. The site revoked reappears.
- Click "Revoke button again". Now it's gone for good.

Screen recording: https://cl.ly/e8a6daf57bb6

### Expected result

It should take one click to revoke a site.

### Actual result

It takes two clicks

### Environment

I've  consistently seen this on stage and prod.

**Comment by rlr** [comment]
I *think* I only see this when I've access the site recently. If I was a gambler, I'd bet one revoke click is revoking the access_token and the next click is revoking the refresh_token.

**Comment by clouserw** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1589463

**Comment by rfk** [comment]
Thanks for the report!

> If I was a gambler, I'd bet one revoke click is revoking the access_token and the next click is
> revoking the refresh_token.

I suspect it's the opposite - the first click is revoking the refresh_token but leaving active access_tokens in the db. The second click destroys the access tokens and removes the client from the list entirely.

Addressing https://github.com/mozilla/fxa/issues/1249 would fix this issue, but involves a migration on the oauth `tokens` table (so that we can know which refresh_token was used to generate a particular access_token), and I get the impression we're a bit hesitant about doing those at the moment...

**Comment by juliemccracken** [comment]
Made this a blocker after discussion in this morning's SubPlat meeting. Let's see what needs to be done about this.

**Comment by shane-tomlinson** [comment]
Caused by #2480 and #1249

**Comment by davismtl** [comment]
Are #2584 and #1802 related?

**Comment by rfk** [comment]
> Are #2584 and #1802 related?

I don't believe so.

**Comment by shane-tomlinson** [comment]
Basic idea outlined in https://github.com/mozilla/fxa/issues/1249#issuecomment-544720161. I'm happy to do this tomorrow, unless someone beats me to it.
