### ISSUE TITLE
Support Submit Error / Incorrect state reported to user

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3090]
From Andrew Morales...reported in production

User sees an error, but also receives an email indicating that support request is received.

> When I went to submit my Support Ticket I received an error letting me know that my request was not successful. I tried twice. Got the same error twice. When I closed my window and went to my GMail inbox I see that my support tickets were created even though I was given an error message. 

<img width="704" alt="180-9ffb08b9570e970af7b6291d06f42192_Screen_Shot_2019-10-22_at_11 00 24_AM" src="https://user-images.githubusercontent.com/3323249/67388076-4e5c0b80-f598-11e9-994c-1e29abeb2676.png">

**Comment by johngruen** [comment]
Ben to look in logs

**Comment by bbangert** [comment]
I should note, I can see why this is happening. Due to how Zendesk works, we must first create a ticket, which creates the user record if needed. Then we have to fetch and update the user to add the fxa user id to the Zendesk user record. Since the support request was created, the first call to make the ticket did work, but one of the followup calls to add the fxa user id must have failed.

To attempt to remedy this, I will add a retry to the request, and then capture the error to Sentry (it's currently not reported at all).

**Comment by clouserw** [comment]
We discussed this in our general meeting this morning and confirmed that this is **not** a blocker.

**Comment by bbangert** [comment]
Retries have been added, and more error reporting to track if it happens again.
