### ISSUE TITLE
Change card_declined error message to use card_error string

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3151]
This is the generic declined message and it shows when a user mis-enters their card expiry. We should use the `card_error` message which is more descriptive.

Related to #3106

**Comment by lmorchard** [comment]
I'm having trouble reproducing this one... can we get a screenshot of the exact error that's happening, and what error should appear?

**Comment by LZoog** [comment]
I _think_ I see what you're wanting here, but agreed we need a screenshot of some sort - when handling Stripe `card_error` errors at the `createToken` level we're displaying the message implemented in [this PR](3136). We have a `createSubscription` piece that does show a "Card declined" header with the message received from Stripe (admittedly I'm not entirely sure when we hit this instead of `createToken` errors without digging further) - is this what you're wanting us to change? We have "Subscription failed" if it fails at this level but is _not_ a `card_declined` error. I'm not sure what the history is around handling that the way we are there.

See [the code here](https://github.com/mozilla/fxa/blob/5546fb97b310c4d8dee8e166c0cd5a5ac9613bce/packages/fxa-payments-server/src/routes/Product/index.tsx#L272). This might be what you're referencing?

**Comment by LZoog** [comment]
@johngruen I know we chatted really briefly about this on Slack today - after looking into this a bit more I'd still like you to post a screenshot if possible.

@lmorchard, correct me if I'm wrong, but it looks like we hit a `createSubscription` error if the Stripe payment goes through but the subscription fails to submit on our end (with the plan name and such), but it doesn't make sense for that to be applicable here. If Stripe rejects the payment, which it should if the expiration is incorrect, it should be caught in `createTokenError.error`, in which case, this issue should already have been taken care of.

BTW John, are you using your own card on prod? I can't find a Stripe test card that works locally or on stage to reject for this reason... 🤔

**Comment by johngruen** [comment]
I am using my own card on Prod, yes...here's a screenshot of the error. Not sure if this is helpful...my concern is that this error is being displayed when i mis-enter my card's expiration date.

<img width="740" alt="Screen Shot 2019-10-28 at 7 23 31 PM" src="https://user-images.githubusercontent.com/3323249/68040520-c5974b00-fcce-11e9-80c9-42138c6f70f4.png">

**Comment by lmorchard** [comment]
Taking a quick look at [where this dialog message is coming from](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/routes/Product/index.tsx#L27).

It's displayed on a `card_declined` error from subscription creation. The "Card declined" title is ours. But, "Your card was declined." is the `message` passed to us from Stripe in the error.

We could just replace that [`{message}`](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/routes/Product/index.tsx#L280) with `getErrorMessage('card_error')` to display ["Your transaction could not be processed. Please verify your credit card information and try again."](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/lib/errors.ts#L38)

Only thing might be that the `message` comes from Stripe & the bank. Not sure if that message will ever say something more specific about why the card was declined? (e.g. a reason *not* to try again with the same card?)

**Comment by lmorchard** [comment]
> it looks like we hit a createSubscription error if the Stripe payment goes through but the subscription fails to submit on our end (with the plan name and such), but it doesn't make sense for that to be applicable here. If Stripe rejects the payment, which it should if the expiration is incorrect, it should be caught in createTokenError.error

From what I understand, the token we create via Stripe is just the encoding of the user's **intention** to initiate a payment with the card they submit. But, creating a token doesn't actually perform the payment processing.

Passing the token to the backend in the `createSubscription` call is what initiates the payment - and thus is where errors like `card_declined` will surface.

This stuff is kind of intentionally obscure, because it's what prevents us from ever actually handling credit cards on the FxA side. It's up to Stripe to decide where validation, verification, etc of cards happens.

**Comment by LZoog** [comment]
> here's a screenshot of the error. Not sure if this is helpful...

That's what I wanted to see, thanks! 😀

> We could just replace that `{message}` with `{getErrorMessage('card_error')}` to display our generic "Your transaction could not be processed. Please verify your credit card information and try again."

👌 Exactly what I was thinking. I don't think we want to display a more specific message to the user - in mozilla/subhub#98, @jackiemunroe states: "Also, from a security standpoint, we probably don't want to tell users why their card was declined, just that it was." @johngruen had confirmed in #2812 that we just want to display that generic "could not be processed," error so I'd say it's safe to assume `{getErrorMessage('card_error')}` is the fix.

> Passing the token to the backend in the `createSubscription` call is what initiates the payment back in subhub-land - and thus is from where errors like `card_declined` will surface.

Thanks for the explainer, this makes more sense now. It might be useful if we had some type of chart to reference to show the communications happening here between FxA, Stripe, and Subhub if one does not already exist.

**Comment by LZoog** [comment]
Patch: #3230
