### ISSUE TITLE
Cancel sub button should display spinner while loading

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#3298]
Reported in our internal beta...

> STR:  1. https://subscriptions.firefox.com/subscriptions  2. Click "Cancel" at bottom right  3. Click the checkbox and then click "Cancel Subscription"  ACTUAL RESULTS: During the resulting pageload, the text on that button disappears. The button just turns blank.  EXPECTED RESULTS: The text should still be visible so that I can tell what I just clicked.

![164-02e8b605f94e59f9d644dcd696d17eca_Screenshot_from_2019-11-06_14-08-04](https://user-images.githubusercontent.com/3323249/68590129-16a4fd00-048e-11ea-851e-252517c886f5.png)

**Comment by clouserw** [comment]
This CSS already exists

**Comment by LZoog** [comment]
@johngruen It looks like this _may_ have been fixed 3 weeks ago with @meandavejustice's PR: #2971 

When was this tested? It looks like Dave's fix was in 149 and I'm seeing prod is on 149.4 now, since I'm not quite sure when that was pushed to prod or when this was tested can I get confirmation this is an issue right now? If it is, it may be another SVG we need to inline because I can't reproduce this locally. 😞 Also, did you click "Cancel Subscription" and then quickly stop the page from loading to get the screenshot or does this actually appear to hang long enough for you to get a screenshot?

**Comment by johngruen** [comment]
This was produced on production last Wednesday.
The screenshot was taken by a contributor, but i believe he just took a screenshot while the cancellation request was ongoing.

**Comment by LZoog** [comment]
Hey @johngruen, I have really tried to reproduce this locally and also on stage and I am seeing the spinner every time. The code is there - the only thing I can think of is inlining the SVG if this is an issue for some people, but I don't think it's necessary.

Please feel free to reopen if this can be replicated somehow, but I think it was fixed somewhere in train 149.

Stage:
![cancel-sub](https://user-images.githubusercontent.com/13018240/68781906-1b88be80-05fe-11ea-9be2-c8c7dd5960c1.gif)

**Comment by johngruen** [comment]
WFM. thanks for investigating
