### ISSUE TITLE
Email first form should focus the email field

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#3357]
STEPS TO REPRODUCE
1. Create a fresh profile
2. Enter Sync through any entrypoint (not about:welcome) or visit https://accounts.firefox.com/?action=email

EXPECTED RESULTS
* Email field has focus

ACTUAL RESULTS
* Email field does not have focus

<img width="817" alt="image" src="https://user-images.githubusercontent.com/68213/68793386-1e45dc80-061b-11ea-89c8-05b28fe05a72.png">

**Comment by shane-tomlinson** [comment]
This was fixed by https://github.com/mozilla/fxa/commit/a6813b76aefd40b6e60330d8adcaf9fc3212e1e3 which will go out with train-150. You can see it in action by visiting here: https://accounts.stage.mozaws.net/?action=email

**Comment by vasilicatamas** [comment]
This issue is verified fixed on FxA Prod 1.150.9 using Firefox 72.0a1 (2019-11-24), Firefox 71.0.b12 and Firefox 70.0.1 under Windows 10 64-bit and Mac OS X 10.14.6. Email field is automatically focused when opening the Email first form.

![emailfield](https://user-images.githubusercontent.com/18114210/69539915-22181e00-0f8e-11ea-91cd-a0b263024356.gif)
