### ISSUE TITLE
Consider adding a return value to fxaccounts:oauth_login

### ISSUE THREAD

**Issue by grigoryk** [mozilla/fxa#3380]
Currently `fxaccounts:oauth_login` does not expect a return value. Client receives a data bundle (which has an OAuth code in it), and is expected to "take care of it" from then on, while a "success" message is displayed to the user.

However, client then needs to exchange this OAuth code, and that operation may fail for a number of reasons, most common being network failures. In the context of `a-c` and its consumers (Fenix, FxR) handling these failures is awkward at best, since the UI with which user was interacting already displayed a success message.

ISTM that the main UI with which user is interacting needs to be aware of the failure cases; if that's not the case, we're essentially looking at patchy workarounds to provide a decent UX in case of things going wrong.

Is it possible to change this flow so that web content which sends `fxaccounts:oauth_login` expects a success/failure response from the host application, and doesn't display a success screen until it receives a success response? A basic error screen is probably something we'd want in this scenario as well; it could offer a "try again" option, for example; we could also auto-retry in case of intermittent failures either at the webchannel levels, or lower down in the stack.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-549)
┆Issue Number: FXA-549

**Comment by shane-tomlinson** [comment]
What we could do is in the `fxaccounts:fxa_status` message that's sent, the client responds with a new capability, something like `responds_to_oauth_login: true`.

That would be a flag to us that we should use a query that expects a response rather than a fire and forget message.

**Comment by rfk** [comment]
>  since the UI with which user was interacting already displayed a success message.

So, just to make sure we understand the full suite of architectural choices...are we committed to having the success UX live in web content on an ongoing basis here?  Another option would be that the browser takes over with its native Accounts Settings UX after receiving the `fxaccounts:oauth_login` message, where it can show whatever success or failure messaging it likes.

I don't recall whether we're showing the success UX in web content because it's the best design, or because it was the most expedient option available on Fenix's shipping timeline.

**Comment by grigoryk** [comment]
Our current approach to handling a success scenario is to just hide FxA web content once we know we're done, and go back to whatever user was doing before (signing in via onboarding, or via settings). 

So the happy path is essentially "get out of the way".
 
I'm not sure what a native error UI that fits well into this model would look like. To me it feels clumsy to context switch from web content to native (an error!) and back to web content (try again). We're already in web content, so let's just handle the errors there?

Now, it'd be a whole different conversation if we wanted to "natify" the whole experience... but alas :)

**Comment by rfk** [comment]
Grisha and I chatted synchronously about this earlier today.

I have concerns about trying to build an elaborate error-handling experience in web content, with "try again" handling and things like that, since it doesn't seem like a comfortable fit with an OAuth-style login flow.  But I can see scope for some very simple error handling that just waits for a response from the app before showing either "success!" or "sorry, something went wrong!".

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
