### ISSUE TITLE
Modify SubscriptionRedirect to display user survey.

### ISSUE THREAD

**Issue by marty331** [mozilla/fxa#3456]
This is a change request to modify the SubscriptionRedirect flow to include a user survey  and a link to download the newly purchased product.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-572)
┆Issue Number: FXA-572

**Comment by clouserw** [comment]
@johngruen for adding details here

**Comment by marty331** [comment]
![Subscription Ready, Survey](https://user-images.githubusercontent.com/663316/70001520-2199fd00-1523-11ea-8408-c3fce55da58a.png)
Adding mockup per @lmorchard

**Comment by lmorchard** [comment]
We definitely need more details here.

Seems like a small thing to add a survey. But, also has potential to grow in scope - i.e. as we consider adding auth-server routes or a standalone service to guard a surveygizmo API secret. Also, considering that this is at the end of a process where a user has paid us money, it seems a sensitive spot for potential disruption.

Some general answers / requirements we need - if only for review, QA, and general care & feeding of the feature going forward:

* What's the deadline? (should it fit in one of our sprints?)
* How long will this survey live?
* Do we need to instrument this for any metrics?
* Will all users see this survey every time they are sent to download any product?
* What are the failure states and how should we message them? (i.e. what happens when loading the questions or submitting answers fails or is rate limited?)
* Have we done something like this elsewhere at Mozilla as an example? (On other projects, I've seen us *link* to an external survey. But have we embedded like this before? If so, how was that done & how did it work out?)
* Can we bend on the UX & styling if it simplifies integration? (e.g. use an embedded iframe survey hosted by surveygizmo vs implementing our own survey component & API proxies with an ops-managed API secret)
* If we consider embed via iframe
  * Seems secure, but are there concerns worth a review? (probably no worse than the iframe'd Stripe components we already use)
* If we consider including a 3rd party JS lib from surveygizmo on payments-server
  * does it need security review? (payments-server is intended in part as a kind of DMZ for 3rd-party Stripe JS - we're sensitive to adding more external resources to FxA in general)
* If we consider building our own web API proxy to guard the surveygizmo API key
  * How sensitive is the key? Would leaking it grant access to PII or altering surveys?
  * How is the key rotated and who is involved? (e.g. ops, whoever owns the surveygizmo account, anyone else?)
  * Should the key be rotated regularly?
* What are the constraints of the surveygizmo API and our account with them?
  * do we need to rate limit calls to it / cache question results? ([240 requests per minute](https://apihelp.surveygizmo.com/help/api-request-limits) - sounds like a high ceiling, considering the place in the flow)
  * do we need to send a unique identifier per user? (i.e. any PII concerns, etc?)

**Comment by jvehent** [comment]
> If we consider including a 3rd party JS lib from surveygizmo on payments-server
> does it need security review? (payments-server is intended in part as a kind of DMZ for 3rd-party Stripe JS - we're sensitive to adding more external resources to FxA in general)

Keeping third party scripts strongly isolated from payments.f.c is important. Displaying the survey on an untrusted domain, like we do for user uploaded images on firefoxusercontent.com, is the preferred approach.

**Comment by marty331** [comment]
@jvehent per @lmorchard 's recommendation I'm using an iframe delivered from SurveyGizmo, so no external JS is imported directly into the FxA project.

**Comment by mozfreddyb** [comment]
There's a phishing risk with a compromised surveygizmo iframe redirecting to the top-level-window away from payments.firefox.com to the proverbial evil.com.

Fortunately, iframe sandbox can help us here. We should start with `<iframe sandbox="allow-scripts allow-forms">` and iterate over other sandbox flags that might be required (See [mdn article for iframe sandbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe)).
E.g., if the finished survey is supposed to open popups, you might have to add `allow-modals`.

But the resulting sandbox attribute should absolutely **not** contain the `allow-top-navigation`  token. This is what's protecting us against the phishing risk.

**Comment by marty331** [comment]
@mozfreddyb Thanks for the link, the survey will NOT be opening up any modals or popups.  It's a 3 question survey that then uses window.parent.postMessage to trigger a redirect to the subscription download url from the React app (SubsciptionRedirect.tsx).

**Comment by johngruen** [comment]
Some additional context here...
- This work comes out of a proposal from Marina on the IT team from the culture of experiments workshop. The design of the survey and questions have been vetted by data folks who work run this workshop.
- The survey questions are intended to be a baseline gauge for user sentiment of our payment form. The intent would be to run them for a sprint or two when we are in a user-acquisition phase to try to capture sentiment at the time of purchase. Once we're satisfied with the answers we can simply revert the PR. It would also be worth exploring the possibility in some logic to deploy this survey occasionally when we add features, change designs etc. to sample how platform changes affect sentiment.
- Because our platform has a small user-throughput, it seems easiest for all users to see the survey at first so we can establish a baseline completion rate.
- In terms of "when should this go live?" the answer is, when it's ready, that would include sign-off from relevant security folks (guessing @jvehent), legal/policy/ team engineers and myself.
- We do not need any metrics instrumentation beyond the survey itself which captures submissions and our existing amplitude events.

**Comment by lmorchard** [comment]
> This work comes out of a proposal from Marina on the IT team from the culture of experiments workshop. 

Do we have this proposal somewhere (e.g. in a Google Doc)? Any documentation would help. QA will want it for sure. Any sec-review will want to have it too

>In terms of "when should this go live?" the answer is, when it's ready, that would include sign-off from relevant security folks (guessing @jvehent), legal/policy/ team engineers and myself.

Do we / should we have any reviews (e.g. security) scheduled before we merge & deploy this?

**Comment by jvehent** [comment]
Ping us when it's in stage and someone (like @mozfreddyb ) will give it a poke.

**Comment by lmorchard** [comment]
Reopening - we have [open questions](https://github.com/mozilla/fxa/issues/3456#issuecomment-566204181) and an env var got added which needs some tweaking

**Comment by johngruen** [comment]
I spoke with legal about this yesterday, and they described it as heads-up level for the trust and and privacy folks, so i am reading them in today. Marina has a doc, I am running it down.

**Comment by chenba** [comment]
If this is enabled by default in dev/ci environments, it might break a couple content server functional tests.

**Comment by lmorchard** [comment]
> If this is enabled by default in dev/ci environments,

There is no enable / disable, it's a direct change to the SubscriptionRedirect view

**Comment by johngruen** [comment]
Here's a write-up for additional context: https://docs.google.com/document/d/11FIsQ4raFc6Rm5zUdO0oY3pL7T0f_I70h-kNcSyApY8/edit?usp=sharing

**Comment by marty331** [comment]
@clouserw Can you tell me when this will be rolled out to stage? Prod?  Was expecting it in stage on Dec 23.

**Comment by chelsea-lewis** [comment]
@marty331 Currently planning for this to hit Stage on January 5 and to hit Production on January 13. Our push schedule was adjusted for the holidays. cc: @clouserw
