### ISSUE TITLE
Standardize Sync Optional Flow to New Winning UX

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3490]
**Context:**
We recently ran an experiment to increase email confirmation rates by moving the codes form immediately after the registration form and moving the CWTS checkboxes into the registration form. It has had a tremendously big impact on our registration rates. It improves our form submit rates and our email confirmation rate while providing more transparency to the user in the registration form. The biggest impact seems to be on the about:welcome page where this additional context seems to be benefiting the user.

As of Firefox 71, the about:welcome is suppose to use a "Sync Optional" that we previously designed to give users more control during registration. This new flow will regress gains we've made as a result of our latest A/B test.

**Proposed change:**
After discussions with @shane-tomlinson and @ryanfeeley , we believe that our new design that has CWTS in the registration form accomplishes the same thing as the Sync Optional flow, avoiding users a "Sync surprise" as some have called it.

You can see the new flow here:
https://youtu.be/UktAKUrVdXk

This being said, we no longer believe that we need to make a distinction between Sync and Sync optional flows.

**Specifics:**
- eliminate the sync optional flow
- default the sync optional to the new flow
- change the new flow so that when users un-select all sync engines, sign them into Firefox but NOT SYNC. This would be the equivalent to people opting to not sync on the CWTS screen of the Sync optional flow.
- CWTS screen will no longer exist in registration flows
- CWTS screen will remain for users signing in to Sync for the first time

CC @rfk @vladikoff @left47

Note: Firefox 71 is being released December 2nd so we do not have much time and will likely need to do an FxA dot release if we want to avoid a big performance regression with the release of Fx71..

*EDIT: Many people have asked me if anything needs to land in Mozilla Central. The answer is no. All of these changes can happen on the FxA side.*

**Comment by vladikoff** [comment]
Let's make sure we capture the metrics where the users uncheck everything, we have that new "doNotSync" event in amplitude. It might be beneficial to add a "doSync" event so we can easily compare, but might not need.

**Comment by vladikoff** [comment]
Also keep an eye on the service= param. When users go and uncheck everything we MUST specify the OAuth client id of Firefox Desktop instead of sync for metrics and marketing purposes. (This means we can later ask those users to turn the Sync feature on)

**Comment by rfk** [comment]
> eliminate the sync optional flow

We had been planning to use the "sync optional" flow for other things, such as when signing in to the browser to connect Monitor in about:protections. Please let's keep that in mind as we're making this change (IIUC the expectation is that we should not show any CWTS messaging in this case, not even in the new location on the password form).

That might not actually affect anything in the code yet, I just wanted to call it out explicitly for context.

> change the new flow so that when users un-select all sync engines, sign them into Firefox but NOT
> SYNC. This would be the equivalent to people opting to not sync on the CWTS screen of the Sync
> optional flow.

IMHO it would be clearer to still include an explicit "don't sync this device" option so that users understand that it's easy to opt out; but, I accept that there's limited real-estate on this screen, and will happily yield to the experts on such UX matters :-)

> CWTS screen will remain for users signing in to Sync for the first time

I want to clarify the wording here so we don't confuse future readers: the separate "would you like to sync" page will remain for users who are signing in to sync (regardless of whether it's their first time using sync or not).

We do not currently offer "choose what to sync" during sync sign in at all. We *should* do it when signing in to sync for the first time, but we currently do not.

**Comment by davismtl** [comment]
CC @irrationalagent ^^

Makes sense @vladikoff . We should also set the user property `sync_engines` on the form submit or reg created.

**Comment by davismtl** [comment]
> We had been planning to use the "sync optional" flow for other things, such as when signing in to the browser to connect Monitor in about:protections.

I think we have time to revise the flow to make sure it works for about:protections in in time Fx73 (Feb 2019). Even the sync optional flow had CWTS after registration so perhaps even that flow would have required some tweaking.

**Comment by vasilicatamas** [comment]
Considering the short-notice of these changes and the multiple areas that are targeted, the QA team will test this implementation based on a high-level test cases. In order to create them we need to clarify a few scenarios:
1. We understand that “Don't sync this device” button will be eliminated from the registration flow and this might be a bit confusing for the users. Considering that the Sync decoupling changes are not promoted we think that would be helpful to have a tooltip (as the one that is displayed for the password field) pointing to Choose What to Sync section from registration form, informing the users about the new option that they have which is to turn the Sync OFF.
2. Based on the fact that Toolbar, Hamburger menu and about:preferences#sync were forced sync entries, will be sync turned off also for this entry points when none of the CWTS options will be selected?  
3. What does it mean that the CWTS screen will remain for users signing in to Sync for the first time? It means that if a user want to sign-in using a different device than the device where he registered?
4. How will impact these changes the Mobile side of the registration flow? How will affect the Add-ons and Preferences options from cwts the Mobile side since the mobile settings doesn't have those two checkboxes? Will be greyed those options if you will register/log-in from a mobile device?

**Comment by shane-tomlinson** [comment]
@vasilicatamas Great questions, quick answers before I'm out for the day:

1. I defer to @ryanfeeley, though I'm personally not sold on a tooltip for this purpose.
2. I did not make that change, if coming from a "sync required" flow, even if deselecting all the buckets, Sync is still "enabled".
3. If a user signs up to FxA for Monitor and then they sign into sync, they should see the old CWTS screen.
4. Mobile shouldn't change since the sync optional flow is Desktop only.

**Comment by vasilicatamas** [comment]
Thanks Shane for these quick answers!

> 2\. I did not make that change, if coming from a "sync required" flow, even if deselecting all the buckets, Sync is still "enabled".

So, the same registration flow will be available regardless of the entry point but the results will be different, which means that Sync will be OFF if the account will be created from about:welcome page and ON when starting from Toolbar, Hamburger menu and about:preferences#sync. But how will users be notified about this difference?

**Comment by davismtl** [comment]
1. At this time, I don't believe that the tooltip will be needed to tell people that they can unselect all the boxes. I think we should just do the right thing based on the choices they make and remove the cognitive load from the user.

Furthermore, the simple presence of the checkboxes are already providing way more context to the user than the previous flow, even prior to registering.

Finally, the about:welcome page will be testing a lot of Sync value proposition in Firefox 71 so I think that this further aligns with that.

2. @vasilicatamas I think you're right. We should be more consistent. I think this is a great follow up for after the release. @shane-tomlinson, we should discuss with @ryanfeeley about trying to align the behavior of all of these touchpoints. I don't think that there needs to be different behaviors. It could be confusing to the user. Sync could theoretically be considered optional in the Sync flows if the user unselects everything. I would not make this a blocker though.

> 3. If a user signs up to FxA for Monitor and then they sign into sync, they should see the old CWTS screen.

That's correct. 

> How will affect the Add-ons and Preferences options from cwts the Mobile side since the mobile settings doesn't have those two checkboxes? Will be greyed those options if you will register/log-in from a mobile device?

Shane is right that it won't change anything on mobile but your question is very relevant to the overall changes we released last Friday to the registration flow. I don't think we previously exposed all of those sync engine options on mobile. I just went through the flow on iOS and we seem to be exposing them in the registration flow now. To be honest, I actually think that this is OK and perhaps even preferable since their selection is global and will apply to any future desktop devices that they add. The experience was much worst before because we had no way of easily resurfacing those sync options to the user on desktop if they had started on mobile. This might have just worked out for the best.

Good catch and thanks for bringing this to our attention.

**Comment by vasilicatamas** [comment]
> 3\. If a user signs up to FxA for Monitor and then they sign into sync, they should see the old CWTS screen.

This expected result is not met. When a user, which is already registered in Monitor, tries to sign in to sync sees the new CWTS flow - this happens for both sync and sync optional flows. 

Any thoughts about this?   

![cwts1](https://user-images.githubusercontent.com/18114210/69958736-21dbcd80-150e-11ea-9fff-ac1612cc77c5.gif)

**Comment by shane-tomlinson** [comment]
> This expected result is not met. When a user, which is already registered in Monitor, tries to sign in to sync sees the new CWTS flow - this happens for both sync and sync optional flows.
>
> Any thoughts about this?

Hmm, there is a different account signed into FxA, vtamas+1@mozilla.com. If you start with a totally fresh profile and sign into Monitor, then into Sync, does the same thing happen?

**Comment by vasilicatamas** [comment]
> Hmm, there is a different account signed into FxA, [vtamas+1@mozilla.com](mailto:vtamas+1@mozilla.com). If you start with a totally fresh profile and sign into Monitor, then into Sync (using the same email), does the same thing happen?

Yes. Same behavior is encountered.

![issue2](https://user-images.githubusercontent.com/18114210/69976860-62e5d900-1532-11ea-8eab-2e49ae812b4e.gif)

**Comment by shane-tomlinson** [comment]
> Yes. Same behavior is encountered.

I just re-looked at that video, you'll notice that signing into Monitor uses accounts.firefox.com, whereas signing into Sync uses dev-stomlinson.lcip.org, this is using two different fxa instances.

To approximate signing into Monitor, use the https://123done-stomlinson.dev.lcip.org/ and click signup. That'll use stomlinson.dev.lcip.org to sign up too.

**Comment by vasilicatamas** [comment]
> To approximate signing into Monitor, use the https://123done-stomlinson.dev.lcip.org/ and click signup. That'll use stomlinson.dev.lcip.org to sign up too.

For this time the "Would you like to sync" page is displayed instead of the old CWTS page. Is this the intended behavior?

![cwts2](https://user-images.githubusercontent.com/18114210/69983972-9cbddc00-1540-11ea-8ff8-50e57ce16bff.gif)

**Comment by rfk** [comment]
> For this time the "Would you like to sync" page is displayed instead of the old CWTS page.
> Is this the intended behavior?

Yes, this is expected, thanks for confirming (ref https://github.com/mozilla/fxa/issues/3490#issuecomment-558783324 for more about why this is the expected behaviour)
