### ISSUE TITLE
Why did we need xlarge on circleci again?

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#3515]
follow-up to #3512

**Comment by lmorchard** [comment]
Yeah, to be clear: My switching us back to xlarge was very handwavy. I did it because it appeared to be the thing that worked and unblocked a bunch of PRs. I didn't manage to measure any resource usage or come up with a definitive reason why. Would be nice to do that, maybe trim some tests, and actually get us reliably running on a smaller resource class.

**Comment by lmorchard** [comment]
Things I *did* notice, though, included the content-server process getting killed and the Firefox instance running selenium tests dumping core. Those smell like out-of-memory issue to me, but it's just a hunch.

**Comment by chenba** [comment]
In one of the debug runs, I printed the value of `os.freemem()` when the process was terminated by the EPIPE error, and it was 16GB.  That made no sense since it was using the default resource size, which should have had only 4GB.
