### ISSUE TITLE
Sync Preferences not saved for an account confirmed on a different profile

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#3542]
**Build:**
FxA Stage [Train 1.151.1]

**Affected platforms:**
Windows 10 64-bit

**Affected versions:**
Firefox 71.0

**Steps to reproduce:**
1. Launch Firefox with a clean profile and click on "Firefox Account" icon from the toolbar.
2. Click on "Turn on Sync..." button.
3. Type a new email address which does not have associated a Firefox Account and click “Continue” button.
4. Fill with valid credentials all the fields and select a few sync options (bookmarks, history) in registration form.
5. Click “Create account” button.
6. Launch Firefox with a new profile and login using the recently created account.
7. Confirm your account via email.
8. Check the sync options from about:preferences#sync.

**Expected results:**
Only the sync options selected during the account creation flow are checked in about:preferences#sync.

**Actual Results:**
All sync preferences appears as check in about:preferences#sync.

![issue1](https://user-images.githubusercontent.com/18114210/69974911-dab20480-152e-11ea-8e35-04d6b4976a45.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-70)
┆Issue Number: FXA-70

**Comment by rfk** [comment]
Wow, this is a thorny one, nice find @vasilicatamas!

IIUC, because the first browser is still sitting on the "enter verification code" screen, FxA has not yet sent the `fxaccounts:login` message to that browser, meaning that it's not yet syncing and hasn't yet saved the sync data choices.

I expect there's not much we can do about this in the short term, but we should try to clean it up when we revisit CWTS more broadly in the new year.

**Comment by johngruen** [comment]
@ryanfeeley i wonder if we want to add some sort of reminder to verify email in Firefox Sync Settings?

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
