### ISSUE TITLE
Domain drop-down does not resize according to the email address length

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#3557]
**Note:** 
This issue is a follow-up for #3197

**Build:**
FxA Prod [Train 1.151.2]

**Affected platforms:**
Android 8

**Affected versions:**
Firefox 71

**Steps to reproduce:**
1.Launch Firefox app and go to menu -> settings -> SIGN IN
2.Taps on Sign in to Sync button
3.Type a long username followed by the “@” symbol and then type the first character of the email domain.

Expected results:
The domain dropdown size is successfully updated according to the email address length.

Actual Results:
The domain dropdown size is updated according to the results number.

![20191203_161811](https://user-images.githubusercontent.com/18114210/70060616-8e78ca00-15eb-11ea-857c-b5dc1c00463a.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-63)
┆Issue Number: FXA-63

**Comment by LZoog** [comment]
Eeeep. This is really similar to #3558. Tagging @ryanfeeley @davismtl here too, as the character limit could help this out as well but it looks like this one would need a shorter limit. I already have `isAndroid` checks in there so that would be OK but I'll leave the decision up to you guys on 1) if this is something we should address and 2) what the max character limit should be if so.

**Comment by davismtl** [comment]
I'm not sure I understand the character limit. Is that to just prevent text wrapping?

**Comment by ryanfeeley** [comment]
@LZoog One way to mitigate this is to reduce the padding on the page. I will file that separately.

As this is native UI, I don't think we have control over it, though we can file a bug with the team to truncate and append a … can't we?

**Comment by LZoog** [comment]
@davismtl Sorry, see #3558 for more context. Yes, that's the only thing I believe we can do to solve this issue and 3558 from our end. We can't determine how the drop-down behaves since it's native to the browser/OS.

@ryanfeeley We actually have it set at an explicit width. We can increase the width, and then place a `max-width` on there of a percentage (like 90% or whatever seems right) to ensure it's not too large on smaller screens. We can definitely file a bug with Android Issue Tracker. Although, I am curious how Chrome handles this same issue on Android. I'll make a note to look into that. How would you propose the "..." look, would the username be truncated? See #3558 for how iOS truncates the domain with "...".

**Comment by ryanfeeley** [comment]
@LZoog Yes, definitely how iOS does it. Although IIRC some languages use a different character than … for truncation, and German puts a space before it (in some contexts).

**Comment by johngruen** [comment]
@LZoog @ryanfeeley 

Can we just reduce the padding and move on? i think the dropdown is probably OS level and we can't do much about it?

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
