### ISSUE TITLE
Synchronized devices form displays the Sign in/Create account buttons for a logged in user

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#3638]
**Build:**
Stage [Train 1.152.0]

**Affected platforms:**
iOS 13.1.2

**Steps to reproduce:**
1 .Launch the Firefox app.
2. Go to History tab -> Synchronized devices
3. Tap on “Create an account” link
4. Follow the account creation flow
5. Observe the “Synchronized devices” form.

**Expected results:**
“Synchronized devices” form displays the following:
![Screenshot_40](https://user-images.githubusercontent.com/18114210/70633812-d1651e00-1c39-11ea-863e-b8d6aa75dac7.png)

**Actual Results:**
Synchronized devices from displays the Sign in/Create account buttons even the account is logged in.

**Additional notes:**
This issue is not reproducible for “Sign in to Sync” button.

![RecordIt-1576076293](https://user-images.githubusercontent.com/18114210/70633838-da55ef80-1c39-11ea-8790-b2563f45e2e5.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-29)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15944/gif17.gif">gif17.gif</a>
┆Issue Number: FXA-29

**Comment by clouserw** [comment]
@garvinkeeley is this a bug on the browser side?

**Comment by st3fan** [comment]
@clouserw this needs investigation. It is definitely a bug that the empty state is presented even if the user is logged in. Although the steps here are not entirely clear. Maybe that screen just needs a refresh after you log in? (I think some of the results may be cached)

**Comment by st3fan** [comment]
@nbhasin2 would you mind investigating this one a bit?

**Comment by nbhasin2** [comment]
@st3fan Sure thing, I'll take this one on and investigate.

**Comment by nbhasin2** [comment]
Proper Steps: 
- Tap on bottom hamburger menu button
- Tap on your library 
- Go to the Synced Tabs 
- Tap on create account 
- After successful creation 

The issue here is that right after account is created it asks for user's input on verification code. After verification code is entered we come back to the sync'd view but FxA account still returns with needs verification instead of no action needed (FxAActionNeeded.none). After a second when user switches tab and refreshes it then returns proper (FxAActionNeeded.none) and user sees correct view.

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is no longer reproducible on Stage [Train 1.203.6] under iOS 14.4. The Sign in/Create account buttons are no longer offered to the already logged in user.
