### ISSUE TITLE
Form views to logins/registrations makes less sense since our train 152 fix

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#3734]
In https://github.com/mozilla/fxa/issues/3611, we resolved the fact that we were not tracking form views for sync optional flows (sync decoupling).

We seem to be counting them now (which is awesome):
https://analytics.amplitude.com/mozilla-corp/chart/9ppjf21/edit/z192ouz

However, they don't make much sense with the authentication volume we're observing.
https://analytics.amplitude.com/mozilla-corp/chart/llx323e

As a result, we see our authentication rate declining steeply with train 152:
https://analytics.amplitude.com/mozilla-corp/chart/5t9duzh

On Monday (train 152), our login completes for sync-optional flows seems to drop at 12pm:
https://analytics.amplitude.com/mozilla-corp/chart/new/qzin0o9

In contrast, we seem to have a brief registration complete data outage at 8am:
https://analytics.amplitude.com/mozilla-corp/chart/new/9zuiidh 

The last very strange thing is that iOS and Android seem to impacted more since they don't recover from the train 152 drop. (however, note that the slow decline in success rate over the last weeks is likely due to volume from ad spend)
https://analytics.amplitude.com/mozilla-corp/chart/67f16ti/edit/y0nqhw0

@irrationalagent and I are still digging in but something clearly broke with train 152.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-836)
┆Priority: Medium
┆Issue Number: FXA-836

**Comment by irrationalagent** [comment]
Login completion volume is down for the `firefox-desktop` service [since train 152](https://analytics.amplitude.com/mozilla-corp/chart/t1dhox3) - all entrypoints except the toolbar icon, which does not send users through the sync-optional flow in release Fx 71 (is that another bug?)

**Comment by vbudhram** [comment]
> Login completion volume is down for the firefox-desktop service since train 152

Off top of my head I suspect this might be sign-in codes related. It became the default for most (if not all) entrypoints. I'll dig into this a little bit more.

**Comment by irrationalagent** [comment]
I wonder if we may have stopped recording fxa_login - complete after users decline to sync: compare [this](https://analytics.amplitude.com/mozilla-corp/chart/0f1rqp9 ) to [this](https://analytics.amplitude.com/mozilla-corp/chart/0k558vu) 

note there is still a smaller decline in the second chart, though given the timestamp weirdness i may not be full excluding users who declined sync there.

**Comment by irrationalagent** [comment]
> > Login completion volume is down for the firefox-desktop service since train 152
> 
> Off top of my head I suspect this might be sign-in codes related. It became the default for most (if not all) entrypoints. I'll dig into this a little bit more.

Yea, I think this may be at least part of it. The completion rate has dropped much more for [logins that require email confirmation](https://analytics.amplitude.com/mozilla-corp/chart/np13xcv) vs [logins that don't ](https://analytics.amplitude.com/mozilla-corp/chart/5j9e2s3) 

to be clear, I'm pretty sure this is due to us not recording the login email confirmed events and subsequent login complete events, not that the rate is actually dropping

**Comment by rfk** [comment]
> if they generate login complete it appears to be at the wrong time

This may be due to [incomplete logic for setting the flow-complete signal](https://github.com/mozilla/fxa/blob/a8c316ea874c5db86b78c626be8ffec15b7c6451/packages/fxa-auth-server/lib/routes/utils/signin.js#L235), which uses `service=sync` as a signal to wait for an `account.signed` event before signalling that the flow is complete. So for the sync-optional flow, it will select an earlier event like `account.login` rather than `account.signed`.

We could add the Desktop Firefox OAuth client_id in there as well, but I think a less fragile approach would be to have the client code send along its `context` parameter and make the choice based on that.

**Comment by rfk** [comment]
Indeed, according to that logic, logins that require verification will [select `account.confirmed`](https://github.com/mozilla/fxa/blob/a8c316ea874c5db86b78c626be8ffec15b7c6451/packages/fxa-auth-server/lib/routes/utils/signin.js#L240) as their flow-completion event. If the sign-in codes flow does not emit this event (perhaps because it's using a different verification endpoint) that that would explain the missing `flow.complete` events as well.

**Comment by vbudhram** [comment]
> perhaps because it's using a different verification endpoint

Yup that is indeed what is happening here. Both sign-in and signup verification use the `/session/verify_code`. Looks like metrics are emitted for signup but not for [sign-in](https://github.com/mozilla/fxa/blob/ebce25c4985d3434a7ede1b97f77f70f0ca10cd8/packages/fxa-auth-server/lib/routes/session.js#L376).

I'll draft a patch for this and target this train.

**Comment by davismtl** [comment]
> Looks like metrics are emitted for signup but not for sign-in.

This seems to make sense. When I dive into the drop in registration rate, it seems to be driven by mobile acquisition. I suspect the users they are acquiring are of slightly lower quality than normal (or at least different).

https://analytics.amplitude.com/mozilla-corp/chart/67f16ti/edit/twjxs2w
