### ISSUE TITLE
FPN button in emails isn't a link

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#3796]
This was reported to us.  It looks like the HTML in the email doesn't have an href attribute.

![image](https://user-images.githubusercontent.com/80098/71740527-50044400-2e11-11ea-99ed-24d68f00e2f9.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-858)
┆Priority: Medium
┆Issue Number: FXA-858

**Comment by chrismore** [comment]
The URL to the download page is: https://fpn.firefox.com/vpn/download

**Comment by chrismore** [comment]
@rlr r? on this url?

**Comment by johngruen** [comment]
This is verified fixed

**Comment by vladikoff** [comment]
YAY! Thanks @johngruen !!!

**Comment by lmorchard** [comment]
For future reference (if only my own), here's the culprit in the code:

https://github.com/mozilla/fxa/commit/eb3a58224ef04b7b6501aaf4ea1c60547775262b#diff-9437bdee47e1fcc021d46b2e851618f3L1604

This *should* have had a fallback that used the URL from server config when the Stripe metadata value had not yet been supplied. But, ugh, I missed implementing that in this spot.

**Comment by rbillings** [comment]
**What type is it? How frequently will users hit this issue?**
Bug because the link didn’t work
**Frequency**: low
**How was this found?**
User filed in JIRA.
**What caused it?
Where was the gap which caused this issue
Why didn’t we catch it sooner?**
This did not occur in stage during testing or sign off- it was a result of a config change.
**How do we ensure it doesn’t repeat?**
Discussed being more careful about config changes, added code.
**Is this a symptom of a broader issue**
No
