### ISSUE TITLE
Payment form should not allow submission while a request is in progress

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#3851]
Saw a report on Slack of a customer getting two subscriptions to the same product. Took a look at PaymentForm and I see that we *do* disable the submit button while a create subscription request is in progress.

But, thinking about it some more, I noticed that [the `onSubmit` handler itself doesn't check `inProgress`](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/components/PaymentForm/index.tsx#L91). Turns out you can submit a form by hitting enter as well as clicking the button - I was able to reproduce the issue by hitting enter a bunch of times fast on the form.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-900)
┆Priority: Medium
┆Issue Number: FXA-900

**Comment by bsurd** [comment]
I've managed to reproduce this as well, quite easily by just double-clicking on the **Submit** button when making a subscription.
Clicking tree times triggers the failed message but the subscription is still made and two charges appear in the Stripe dashboard.

![image](https://user-images.githubusercontent.com/17178945/72067462-77648080-32eb-11ea-8842-aa8b45a72cbd.png)

**Comment by rbillings** [comment]
What type is it? How frequently will users hit this issue?
Bug because users were able to create multiple subscriptions, which should not be allowed. This is unlikely to happen again.
Frequency: low
How was this found?
A user on slack reported the issue, and a developer filed it.
What caused it?
Where was the gap which caused this issue
This was an edge case 
Why didn’t we catch it sooner?
This test was actually done in staging and it didn’t repro there
How do we ensure it doesn’t repeat?
All forms will continue to get this type of testing
Is this a symptom of a broader issue
No
