### ISSUE TITLE
No additional charge is made after upgrading a tiered product

### ISSUE THREAD

**Issue by bsurd** [mozilla/fxa#3856]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.6
- Linux Ubuntu 16.04 (64-bit)

#### Steps to reproduce
1. Make a tiered product subscription.
2. Upgrade to the next tier.
3. Open the stripe dashboard and observe the charged amount for that account.

#### Expected result:
- An additional charge is displayed in the stripe dashboard for the upgraded tiered version product.

#### Actual result:
- Only the initially paid amount is displayed, no additional charge has been made for the upgraded product.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-903)
┆Issue Number: FXA-903

**Comment by bsurd** [comment]
This was tested with a monthly product, when tested with a daily product on renewal you are charged the proper amount, but I still don't see any extra mail where I'm charged a difference between the plans.

**Comment by jackiemunroe** [comment]
@bsurd the same is the case for monthly products, you should see the proration amount on the next scheduled renewal. Stripe handles all prorations such that they are bundled into the next billing cycle. Are you not seeing the proration information on the renewal email in the monthly case? It should be contained within the expected renewal email.

**Comment by jackiemunroe** [comment]
@clouserw After reading the scenario for this ticket again, noting that it specifically states they were looking at the Stripe dashboard, I would say that this is an invalid ticket. Stripe's behavior is such that the charge does not happen until the next cycle, so the expected case here does not match Stripe's actual behavior. It is only because of the billing cycle for daily's that it appeared to work this way for the testing. Below I will provide information on how to verify the pending charges within the Stripe dashboard.

@bsurd if you would like to verify that the charges will happen as expected look to the "Pending invoice items" section to see where proration items were created, and then verify that they will be on the next bill by checking the "Upcoming invoice" section where you should see a link to view the next invoice in full. You can also check the "Events" section at the bottom to see this information in a more "human readable" format.
So, these images will read a little funny, but what happened in this scenario was a user initially p subscribed to a $500/mo plan, then downgraded to a $5/mo plan, and finally upgraded (went back to) the $500/mo plan
<img width="1034" alt="pending-upcoming-invoice-sections" src="https://user-images.githubusercontent.com/3428280/72284554-24920e00-35f6-11ea-92f6-eea42249838d.png">
<img width="983" alt="event-section" src="https://user-images.githubusercontent.com/3428280/72284555-24920e00-35f6-11ea-9d0e-430dcc6660da.png">
<img width="980" alt="upcoming-invoice" src="https://user-images.githubusercontent.com/3428280/72284556-24920e00-35f6-11ea-9548-7ab42977754b.png">

**Comment by clouserw** [comment]
Thanks @jackiemunroe .  Closing this for verification.

**Comment by bsurd** [comment]
Thanks @jackiemunroe for the clarification here, I was looking at **Payments** only as I was expecting a charge to be displayed there, didn't check in **Customers** for each individual account as I was not aware that I can see extra information there.

Marking this as invalid.
