### ISSUE TITLE
Ensure we are no longer using inefficient remote Docker test runs in CircleCI

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#3996]
Seemed like there were areas in CircleCI runs where we still used remote Docker for tests, which is outdated infrastructure that's possibly wasteful & slow. We should audit & ensure that's not still the case.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-992)
┆Issue Number: FXA-992

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

I went through to verify where we're using the remote (slower) docker in our build process. Only two of our steps properly use it just to tag, three of them are using it for the full build + test.

Since `build-module` uses the remote docker right up front, this could easily be slowing a bunch of steps down.

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

After discussing with Les, these steps are only used for building the final deployment artifact. As such it looks like the remote commands are in the right spot.
