### ISSUE TITLE
Define an OpenAPI spec for endpoints

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#403]
From the [OpenAPI Spec](https://swagger.io/specification/):

> The OpenAPI Specification (OAS) defines a standard, language-agnostic interface to RESTful APIs which allows both humans and computers to discover and understand the capabilities of the service without access to source code, documentation, or through network traffic inspection. When properly defined, a consumer can understand and interact with the remote service with a minimal amount of implementation logic.
> 
> An OpenAPI definition can then be used by documentation generation tools to display the API, code generation tools to generate servers and clients in various programming languages, testing tools, and many other use cases.

I can't take credit for this, this is all @bbangert. He just showed me the [docs generated for Push](https://mozilla.github.io/application-services/api/push_bridge.html#tag/Subscriptions) from their [OpenAPI spec](https://github.com/mozilla/application-services/blob/master/website/static/api/push_bridge.yml), and they are great! 

There is a lot of tooling around OpenAPI to help with things like creating libraries in arbitrary languages and test generation.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-610)
┆Issue Number: FXA-610

**Comment by Cronus1007** [comment]
@shane-tomlinson Shall I take over this issue?

**Comment by shane-tomlinson** [comment]
Hi @Cronus1007 - I no longer work on this project, @dannycoates or @clouserw should be able to give you an answer though!

**Comment by Cronus1007** [comment]
@shane-tomlinson  @meandavejustice  @dannycoates @clouserw For this issue would you want me to implement only testing via Open API Spec 3.0 or update both the testing and Documentation (key features of Open API Spec).

**Comment by bbangert** [comment]
@Cronus1007 if you want to take this, I would suggest using a package like https://www.npmjs.com/package/hapi-swagger, that allows additional parameters to be passed to the hapi routes in auth-server (which is the primary API surface in FxA). The goal would be to replace this page:
https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/api.md

...with a nicely generated OpenAPI spec. There's a lot of routes there to update, so I'm not sure of how large of an issue this is, but it shouldn't affect any functionality since the route additions are for the swagger generator. The OpenAPI docs should be grouped in a similar manner to the manually documented ones above, with similar descriptions/comments.

Does that give you enough to go on?

**Comment by Cronus1007** [comment]
@bbangert  Rather then using https://www.npmjs.com/package/hapi-swagger we can directly use swagger hub to document 
our API's rather than going via hapi-swagger and then replace the documentation. The reason being hapi modules constantly get deprecated and may effect the documentation in a long run.

**Comment by bbangert** [comment]
@Cronus1007 Indeed, the main reason for using a code-driven tool is to ensure the docs are accurate. Unfortunately the FxA API docs have some slight discrepancies from the actual code. We haven't had great luck in the past keeping docs up to date with the implementation, having them driven from it alleviates that concern. I'm not sure there's much to gain from moving them from one manual format to the swagger hub web service (what happens if/when that shuts down?).

**Comment by Cronus1007** [comment]
@bbangert  Actually I am planning to update the documentation as well while making a transition from API. md to Open API Spec.And one more question won't it be fair enough to shift all of the API. md files to Open API Spec rather than only one package. Plus are the documentations necessarily updated.And we are going to use Open API Special 3.0.0 version for making our documentation So indeed this might happen that it shuts down but the possibilities are very less. :)

**Comment by Cronus1007** [comment]
@bbangert  Swagger Hub is asking for the email contact of the developer. So can you tell anything related to this?

**Comment by bbangert** [comment]
@Cronus1007 I'd prefer not to use or require a 3rd party service for docs. While you were planning to update our markdown docs while adding Open API docs (which we would greatly appreciate!), that still leaves us with a manual process to update docs that can result in future documentation drift from the implementation. Hapi modules do get deprecated, but so do 3rd party websites, as long as NPM has the module though, our code should work.

I should note that a longer term goal of ours is to move relevant API's into the graphql-api package (which self-documents), so while this issue is a 'nice-to-have', having our current markdown docs accurate is probably a higher priority.

**Comment by Cronus1007** [comment]
@bbangert  There is a great need to refactor the https://github.com/mozilla/fxa/blob/main/packages/fxa-profile-server/test/api.js file.
Since such a large file like this poses a great difficulty.

**Comment by Cronus1007** [comment]
@bbangert  #6992 plzzz share your review about the update docs.

**Comment by Cronus1007** [comment]
@bbangert Shall I restart with the work on updating the documentation of the API's  of the `fxa-profile-server`.
