### ISSUE TITLE
Confusing error messages

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/fxa#4030]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- MacOS 10.14.6
- Ubuntu 19.04 (x64)
- Windows 10 (x64)

#### Preconditions
- Have a FxA account without a subscription.

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn).
2. Click on the Subscribe Now button and complete the subscription process using the following Card number: 4000-0000-0000-0119.
3. Click on the Subscribe button

#### Expected result:
- An error message is displayed with "Subscription failed" as title with "An error occurred while processing your card. Try again in a little bit." message under the title.
- No payment is made.

#### Actual result:
- An "Internal server error" message appears.

#### Notes:
- It's the same result with the following card numbers: 4000-0000-0000-0127, 4000-0000-0000-0069, 4000-0000-0000-9979, 4000-0000-0000-9987, 4000-0000-0000-9995, 4000-0000-0000-0002, 4000-0000-0000-0101.
- Sometimes the error message is "Unauthorized for route" for the same card number.

![Screenshot_2020-02-03 Firefox Accounts](https://user-images.githubusercontent.com/48829350/73654592-cd330b00-4694-11ea-91ba-9f0d4129c43d.png)

![Screenshot_2020-02-03 Firefox Accounts(1)](https://user-images.githubusercontent.com/48829350/73654598-d1f7bf00-4694-11ea-8ccd-ba8bd925c3cb.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1022)
┆Issue Number: FXA-1022

**Comment by lmorchard** [comment]
I think the internal server error message should be fixed by PR #4047.

The "unauthorized for route" error needs some investigation. The only spot I can find this error message is [in the auth-server under the oauth unauthorized error](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/oauth/error.js#L226). 

I haven't been able to reproduce it myself, but my guess is that the problem is the OAuth token for the subscription form has expired. 

I think the token lifetime defaults to 30 minutes, and we don't have a graceful process to refresh it. S, in other words, if you leave the subscription form open for over 30 minutes, things will break and not in a graceful way. See also issues #1694 #1695 #1834

**Comment by SoftVision-LorandJanos** [comment]
The original issue is not reproducing. I no longer get either of the two mentioned error messages. For some card numbers I get the correct error messages, but for the following card numbers I get "Something went wrong. Please try again later." as an error message: 
4000-0000-0000-0127
4000-0000-0000-9979
4000-0000-0000-9987
4000-0000-0000-9995
4000-0000-0000-0002
4000-0000-0000-0101
![Screenshot (98)](https://user-images.githubusercontent.com/48829350/74032322-5b243400-49bc-11ea-9fac-682aef668136.png)

I will file a new bug report for this issue, so we can track it more easily.

**Comment by lmorchard** [comment]
Depending on the actual error cause, "Something went wrong. Please try again later." may indeed be the intended message and not a bug.

The "something went wrong" message is our ["basic" error message](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/public/locales/en-US/main.ftl#L18). We roll up [a lot of error conditions under this message](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/lib/errors.ts#L34) because we've decided not to provide exact information for these failure cases that might assist in fraud.

There are two other error messages - one suggests [trying again](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/public/locales/en-US/main.ftl#L19), the other suggests [contacting payment provider](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/public/locales/en-US/main.ftl#L20). A smaller collection of errors [are rolled up](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/lib/errors.ts#L72) under each of these messages, respectively.
