### ISSUE TITLE
Unable to access FPN after changing primary email address on Firefox Account [bz1616148]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4176]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1616148

A user reported this [on reddit](https://www.reddit.com/r/firefox/comments/f5h1z4/subscribed_to_firefox_private_network_updated_my/), and in Matrix:

> So far the Firefox VPN has been great, kudos to the Firefox team. However my account is
> currently glitched (probably due to changing my primary email) and the main website
> https://fpn.firefox.com wants me to join the wait list when I try to sign in. Clicking the
> download link in the email I was sent by the Firefox VPN team also redirects me to the
> wait list page.
>
> Could a Mozilla employee help me out? Or can somebody direct me to the correct form to
> contact somebody who can? https://accounts.firefox.com/support Redirects me to my
> main account page, which has no support link. The support articles instruct me to open
> my Firefox VPN application to contact support, but I currently don't have it.

Filing as a bug so we don't lose track of it, and in bugzilla rather than github in case we need to ask for PII from the user in order to debug.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1121)
┆Issue Number: FXA-1121

**Comment by rbillings** [comment]
**What type is it? How frequently will users hit this issue?**
Bug because email was cached incorrectly. Reports were about 1x/week.
**Frequency**: low
**How was this found?**
Users file in bugzilla.
**What caused it?
Where was the gap which caused this issue**
This was caused by an error storing old email addresses in local storage.
**Why didn’t we catch it sooner?**
Edge case for testing
**How do we ensure it doesn’t repeat?**
Automation has been created to cover this scenario.
**Is this a symptom of a broader issue**
No, but is the same as https://github.com/mozilla/fxa/issues/4504
