### ISSUE TITLE
Fix border radius on send SMS button

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#4218]
A little background color swap, and zooming in indicates that the border radius of the button does not match the parent.
![Screen-Shot-2020-02-20-at-1 05 33-PM](https://user-images.githubusercontent.com/68213/74964718-e0a6db80-53e1-11ea-9789-215e5da78616.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1166)
┆Issue Number: FXA-1166

**Comment by LZoog** [comment]
FWIW, this is also an issue for "show password":
<img width="700" alt="image" src="https://user-images.githubusercontent.com/13018240/74980707-92e89e00-53f6-11ea-9304-11ab1a72eb6b.png">

**Comment by aryamanpuri** [comment]
@LZoog Can I take up this issue?

**Comment by LZoog** [comment]
Hey @aryamanpuri, sorry I missed your comment, sure thing! :)

Get the project running, and then run `npm run firefox`. This should run the `fxa-dev-launcher` and allow you to see the Sync flow. Go to the content server (`http://127.0.0.1:3030/`) and click on the "Get started here" link in the grey box. Type in any email and click continue, then click the show password eye. You'll be able to see the border-radius issue in the screenshot I posted that needs to be fixed.

To see the SMS button in the original post, continue through the account creation flow and verify the account (I think you've contributed before so you don't need step-by-step instructions, see the front page README otherwise 🙂), and you'll see the "Send" button. The border-radius miss on this is so minor, you're probably going to have to zoom the page in quite a bit (command (or control if Windows) and "+") or View > Zoom > Zoom In to see it. Let me know if you have any questions.

**Comment by namandangi** [comment]
@LZoog can I try this  one??

**Comment by aryamanpuri** [comment]
Hi @namandangi , I am working on this feel free to take other issues :+1:

**Comment by clouserw** [comment]
This has been fixed
