### ISSUE TITLE
Trying to activate 2FA always returns "Invalid two-step authentication code" error [bz1617201]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4254]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1617201

Created attachment 9128160
Error shown

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

Steps to reproduce:

1. Go to https://accounts.firefox.com/settings
2. Login
3. Two-step authentication > Enable...
4. Scan QR Code with your 2FA app
5. Input the generated code

Actual results:

The message "Invalid two-step authentication code" is shown even if the code is correct.

I had 2FA enabled previously but disabled it because I changed the app I use, no one works now.

Expected results:

I expected 2FA to be enabled.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1192)
┆Issue Number: FXA-1192

**Comment by edumucelli** [comment]
Same problem recently. What worked for me is to remove item from the 2FA app (I am using andOTP) and add it again, but this time not scanning the QR code with the camera, but from an image (previously printed screen the QR code in the phone itself). Once I have added it again through the "QR from image" it the 2FA code will be valid only at the **first** time I have added it. I have seen it only works at the first time because I have failed to enter the recovery code (second step after the 2FA code is correct) and when I came back to the screen "input your code" screen it failed on me. So it either works at the first time or nothing. It may be related to some clock (a)synchronicity. In any case it is really broken for me.

If you are using the Google 2FA app [this](https://support.mozilla.org/en-US/questions/1247606) may help you. The person talks about the clock adjustment you can do on the Google's app.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

Closed in Bugzilla.

**Comment by BartAgterbosch** [comment]
You can open it back up, because it's broken again, exactly this, unfortunately removing and re-adding doesn't work either, nor does printing it out on paper first (which is a ridiculous solution)
