### ISSUE TITLE
FxA Sign-in: "use a different account" not available in all cases

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/fxa#4256]
x-ref to https://github.com/mozilla-mobile/firefox-ios/issues/6158

## Description

Unable to switch account email during sign in flow on Firefox iOS

### Steps to reproduce

Unknown repro, was signing in on Firefox iOS. I need to switch accounts frequently during testing.

### Expected result

Sign in screen should have link: "sign in with different account".
Basically, there should be no state the user can get into whereby the sign in screen does not show this link.

### Actual result

No link to change the account.

### Environment

Firefox iOS rust-integration branch.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1194)
┆Issue Number: FXA-1194

**Comment by garvankeeley** [comment]
This is the screen that I saw with no link to change the account:
![image](https://user-images.githubusercontent.com/5495083/75162178-1a7e2780-56eb-11ea-8574-a201c89b5e67.png)

**Comment by garvankeeley** [comment]
cc @vladikoff

**Comment by rfk** [comment]
The "continue to Account Settings" part is a little unusual here, I guess this encountered this when trying to access the FxA settings page from a signed-in browser, which might be a clue to reproducing this.

In other words, regarding this from the STR:

> Unable to switch account email during sign in flow on Firefox iOS.
> [...] was signing in on Firefox iOS.

If you *had* successfully managed to switch accounts on this screen, I don't think it would have actually signed you in to Firefox as that different account.

> Basically, there should be no state the user can get into whereby the sign in screen does not show this link.

FxA does have a couple of flows where "use a different account" is deliberately hidden, but the caller is supposed to have to opt-in to them by specifying particular URLs. If you happen to reproduce this again, it would be very useful to capture the URL that's being loaded in view there.

**Comment by rfk** [comment]
Looking at the structure of the page shown here, I'm pretty confident this is the `/force_auth` view, which deliberately does not have the "use a different account" option, because we only expect reliers to load this page when they want to force a user to sign in to a particular already-known account.

You may have somehow triggered this branch in the appservices client code, which shows `/force_auth` if you're signing in to a browser in which there is already a signed-in user:

  https://github.com/mozilla/application-services/blob/8285df9c89dcd9137d6b0a05ef7e24c99c2f47e2/components/fxa-client/src/oauth.rs#L126-L128

So this may be a client-side bug in appservices rather than an FxA-side bug.  I'm still not sure why it would say "continue to Account Settings" rather than "continue to Firefox Sync", though.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for the investigation Ryan.  The `force_auth` view makes sense.

**Comment by garvankeeley** [comment]
This type of problem comes up in Sync Fest, so I'll follow up with them to look our for this and any STR.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Since it's been more than a year without an update I'm going to close. If this continues to be an issue please re-open.
