### ISSUE TITLE
”Unverified session” error when deleting an account after password reset on account with 2FA enabled

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#4257]
**Build:**
Stage [Train 1.159.0]

**Affected platforms:**
Windows 10

**Steps to reproduce:**
1. Launch Firefox and login using a Firefox account.
2. Go to Manage account page and enabled the two-step authentication.
3. Change the account password.
4. Try to delete the account, inserting the new password. 

**Expected results:**
Firefox account is successfully deleted.

**Actual Results:**
“Unverified Session” error is displayed and the account is not deleted. 

**Note:**
- A potential solution would be to show a dialog asking for the security code as a  reset password confirmation for accounts which have 2FA enabled.

![deleteaccount2](https://user-images.githubusercontent.com/18114210/75162144-b7f64d00-5725-11ea-8a81-4b9f7edd0856.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1193)
┆Issue Number: FXA-1193

**Comment by rfk** [comment]
Thanks for finding this! A couple of notes from a quick look since I saw this in my inbox:

> Change the account password.

This step destroys all the user's sessionTokens, and then creates a new sessionToken so that they can appear to be seamlessly still signed in on the calling page. The code for creating this new sessionToken is [here](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/routes/password.js#L337), but it looks like it does not correctly copy the 2FA verification status. So when this happens:

> Try to delete the account, inserting the new password.

The FxA serve quite rightly refuses to process the request, thinking that the user has not done their 2FA verification loop.

@vbudhram I know we talked in the past about a way to clean up some of these flows by refactoring the way sessionTokens and the verification thereof are handled, perhaps it's time for us to revisit that topic.

**Comment by vasilicatamas** [comment]
The error still appears on Stage [Train 1.192.0] but only for a few seconds, because the “Enter security code” screen is displayed. After typing the security code, the Manage Account page is refreshed and the user needs to insert again the password in order to finish the deletion process.

![issue19](https://user-images.githubusercontent.com/18114210/97182111-c8733180-17a4-11eb-904a-c88a9fff37af.gif)

**Comment by vasilicatamas** [comment]
This issue was verified as fixed in FxA Stage [Train 1.199.0] under Windows 10 64-bit and Android 9. “Unverified Session” error is no longer displayed and the account is successfully deleted.

![issue79](https://user-images.githubusercontent.com/18114210/106561224-f9e06380-6530-11eb-8c33-3803c73bfe19.gif)
