### ISSUE TITLE
Post-payment survey isn't styled properly on Pixel 3XL

### ISSUE THREAD

**Issue by rlr** [mozilla/fxa#4261]
A user just reported: "This is what the post-payment survey looked like on my Pixel 3XL"

![Screenshot_20200224-133706](https://user-images.githubusercontent.com/36629/75189621-917fe400-571c-11ea-94b0-524384711e36.png)
![Screenshot_20200224-133727](https://user-images.githubusercontent.com/36629/75189624-92b11100-571c-11ea-8eb9-78eac9381c86.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1195)
┆Issue Number: FXA-1195

**Comment by lmorchard** [comment]
FWIW, [this survey is embedded via iframe from Survey Gizmo](https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/routes/Product/SubscriptionRedirect/index.tsx#L64).

I think the styles for the survey are managed from a Survey Gizmo admin panel. I'm not sure who all has access to that. Maybe @marty331 and @johngruen ?

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

What browser is this in?  Thanks

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

I think this is fixed...reviewing

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

there's a pref in survey gizmo where you can disable their default mobile styles...i just did that

**Comment by rbillings** [comment]
**What type is it? How frequently will users hit this issue?**
Bug because the mobile styling was incorrect
**Frequency**: low
**How was this found?**
Dev filed in Github.
**What caused it?
Where was the gap which caused this issue
Why didn’t we catch it sooner?**
The surveys were part of this release, not enough mobile testing was done.
**How do we ensure it doesn’t repeat?**
Added mobile tests for coverage
**Is this a symptom of a broader issue**
No
