### ISSUE TITLE
Can't sign-in to Firefox account. "Primary account email required for sign-in"

### ISSUE THREAD

**Issue by cca310** [mozilla/fxa#4279]
## Description

I cannot sign-in to my Firefox account. It states "Primary account email required for sign-in"
https://i.imgur.com/QLueDTW.png

As you can see, I do not have a secondary email address: https://i.imgur.com/biRIOmu.png

### Steps to reproduce

When I originally created my Firefox account, I used a gmail address. I added my outlook address as a secondary email. I made my outlook address my primary email. I then deleted my now secondary gmail address.

### Expected result

Firefox account is signed in

### Actual result

Firefox account is not signed in

### Environment

Windows 10 Firefox 73.0.1

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1201)
┆Issue Number: FXA-1201

**Comment by cca310** [comment]
I was able to sign in to firefox preview mobile on my oneplus 6 android 9
still can't on my desktop

**Comment by cca310** [comment]
I was just able to sign in to sync on firefox 73.0.1 on ubuntu 18.04.4 LTS. I was also able to sign in to firefox preview mobile on my oneplus 6 android 9

I still can't log in on to sync on windows 10 firefox 73.0.1 because "Primary account email required for sign-in"

How can I tell if anyone is seeing my issue? If this isn't the correct place to post this, please let me know

**Comment by rfk** [comment]
> How can I tell if anyone is seeing my issue? If this isn't the correct place to post this, please let me know

Sorry for the lack of feedback here; this is a fine place to file such issues, but it looks like you've also filed this in bugzilla at [Bug 1619033](https://bugzilla.mozilla.org/show_bug.cgi?id=1619033), and that's probably a better place to continue the discussion because it's possible to mark the bug as private if necessary.

> I still can't log in on to sync on windows 10 firefox 73.0.1 because "Primary account email required for sign-in"

I wonder if some buggy state has been saved in to local storage on the windows machine. You could try browsing to https://accounts.firefox.com, and then [clearing cookies and site data](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox#w_clear-cookies-for-the-current-website) for that site using the instructions at that link.

**Comment by clouserw** [comment]
Closing in favor of bugzilla issue
