### ISSUE TITLE
[iOS, FxA Rust] FxA settings web view now showing a 'sign out' button

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/fxa#4284]
Suddenly seeing a "Sign Out" button, which I am not sure is intentional, as it doesn't exist in release Firefox iOS. I suspect there was a past UX decision to not show this deliberately.

<img width="297" alt="image" src="https://user-images.githubusercontent.com/5495083/75359027-c2c5f480-5881-11ea-903e-37d0d3917398.png">

Expected Behaviour: "Sign Out" button is hidden on Firefox iOS

x-ref to https://github.com/mozilla-mobile/firefox-ios/issues/6178

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1205)
┆Issue Number: FXA-1205

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~rkelly@mozilla.com]- would you add some context here?

**Comment by rfk** [comment]
I did a bit of digging around to reconstruct what's going on here.

There's some logic in the FxA settings page to hide the "sign out" button when the session token belongs to a browser that's using sync, see. e.g. the logic around setting `showSignOut` [here](https://github.com/mozilla/fxa/blob/eefb89dfdddc0fe0d5ca8f2eb111b3d2b70c0347/packages/fxa-content-server/app/scripts/views/settings.js#L96). This is a little bit of a hack designed to avoid confusing the user by having web content that can sign them out of their browser.

Whether or not the session token belongs to a browser using sync, is controlled by a special property in localStorage called `sessionTokenContext`. That property is set by [this code in fxa-client](https://github.com/mozilla/fxa/blob/eefb89dfdddc0fe0d5ca8f2eb111b3d2b70c0347/packages/fxa-content-server/app/scripts/lib/fxa-client.js#L103) if the connecting relier `isSync`. (I don't know why it's fxa-client's job to set this, but that's a separate matter...).

The base relier class [is not sync](https://github.com/mozilla/fxa/blob/eefb89dfdddc0fe0d5ca8f2eb111b3d2b70c0347/packages/fxa-content-server/app/scripts/models/reliers/base.js#L36); only the special sync relier [is sync](https://github.com/mozilla/fxa/blob/eefb89dfdddc0fe0d5ca8f2eb111b3d2b70c0347/packages/fxa-content-server/app/scripts/models/reliers/browser.js#L70).

Firefox for iOS is in the process of refactoring its FxA client code, to stop using a custom `fx-ios-v1` auth_broker and start using the more generic `oauth-webchannel-v1`, using the shared rust components. In the process, I guess it has stopped using the special sync relier model and started using the generic OAuth relier model, for which `isSync` returns false.

The smallest fix here, may be to extend the oauth relier model so that `isSync` returns true when the connecting client is requesting scopes that indicate it is connecting to sync. But this might also be an opportunity to take a step back from this set of abstractions, look at them with a fresh set of eyes, and see if there's a more deliberate cleanup we want to apply here.

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

[~rkelly@mozilla.com] I'm onboard with what you mentioned above. Another option might be to exchange capabilities via webchannels, similar to what happens with pairing. That could be overkill though.

However, I tested this today and was not able to reproduce the above error, ref https://github.com/mozilla-mobile/firefox-ios/issues/6178#issuecomment-594207260.

**Comment by rbillings** [comment]
**What type is it? How frequently will users hit this issue?**
Bug because it changed the mobile options
**Frequency**: low
**How was this found?**
Dev filed in JIRA.
**What caused it?
Where was the gap which caused this issue**
Mobile UI change isn’t the focus of testing
**Why didn’t we catch it sooner?**
Mobile flows aren’t the focus of testing
**How do we ensure it doesn’t repeat?**
Discussed and forwarded to mobile team
**Is this a symptom of a broader issue**
No
