### ISSUE TITLE
Navigating to FxA with incorrect UID param signs user out of sync

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4293]
## STR
1. Have two Firefox accounts (Account A & Account B)
1. Sign into Sync with Account A
1. Grab the uid from Account B (you can do this by signing in in a different browser and opening the network panel and looking at the profile)
1. In the Firefox where you are signed into Sync with Account A go to `accounts.firefox.com/settings?uid=\{uid-for-account-b}

## Expected
User is prompted to sign into Account B

## Actual
1. User is signed out of Sync and Account A and then prompted to sign into Account A.
1. Signing back into Account A here does not restart sync

### Notes
* passing in UID and EMAIL params for Account B resolves this problem.

* passing in a nonsense param `uid=hello` doesn't cause this problem. The UID has to at least have valid formatting

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1210)
┆Issue Number: FXA-1210
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/12634/Screen+Shot+2020-02-27+at+9.34.28+PM.png">Screen Shot 2020-02-27 at 9.34.28 PM.png</a>

**Comment by data-sync-user** [comment]
➤ Mark Hammond commented:

FWIW, I failed to repro this on Nightly, but didn't get around to testing on other channels yet. John, what were you on?

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

I was on nightly and i demo-ed this for Ryan Kelly live as well. Let me try to repro on video.

**Comment by rfk** [comment]
I was able to repro just now I think, looking for logs...

**Comment by rfk** [comment]
> looking for logs...

And uh, there aren't any, perhaps because I got signed out of sync :-/

**Comment by rfk** [comment]
Here's a live link to one of my testing accounts that folks are welcome to try for repro:

  https://accounts.firefox.com/settings?uid=cf13183f033b4c30be3767521ed5e2d5

When signed in to Sync with some other account, if I open the above link in a new tab, I am immediately signed out of Sync.

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

[~rkelly@mozilla.com] [~mhammond@mozilla.com] I can only repro if the FxA menu is in the little >> More tools... menu in the Firefox toolbar

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

err actually i can repro this regardless of where this thing is located.

**Comment by rfk** [comment]
> Expected
> User is prompted to sign into Account B

On reflection, we're not actually able to provide this expected behaviour. In order to sign in to a specific account, we *must* know the email associated with that account, in order to perform the login flow. I don't think it's reasonable to provide an unauthenticated endpoint that takes a uid and returns the email address, which would be required in order to implement the "user is prompted to sign into account b" behaviour.

Users should never encounter a URL like this in the wild, so I think the simplest and best behaviour here would be for us to show an "invalid parameter" error. The user has somehow followed a bad link that includes `uid` without `email`.

Alternately, we could ask them to generically sign in to their account, requiring them to enter both their email address and password. But we don't need this for any active product ask, and given the current undesirable side-effect, I think we should consider that *after* making the buggy behaviour go away.

**Comment by rfk** [comment]
When I repro this, console output for accounts.firefox.com tells me "Session expired. Sign in to continue." but it also seems to do a hard refresh of the page (or at least, it clears the scrollback in my devtools network panel).

**Comment by data-sync-user** [comment]
➤ Mark Hammond commented:

For some reason it doesn't repro 100% of the time - but I did manage with trace logging:

1582842319553   FirefoxAccounts DEBUG   FxAccountsWebChannel message received: fxaccounts:fxa_status
1582842319554   FirefoxAccounts DEBUG   fxa_status received
1582842319554   FirefoxAccounts DEBUG   service
1582842319554   FirefoxAccounts DEBUG   is private browsing: false
1582842319575   FirefoxAccounts DEBUG   FxAccountsWebChannel message received: fxaccounts:logoutSo FxA is explicitly telling us to log out. There's really nothing the client can do to mitigate this.

There are a number of 500 responses from the FxA server too just before this is logged - not sure if that's relevant or not.

**Comment by data-sync-user** [comment]
➤ Daniel Coates commented:

this mixin is used by /settings https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/views/mixins/account-by-uid-mixin.js#L30 ( https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/views/mixins/account-by-uid-mixin.js#L30 ) ... triggers fxaccounts:logout message

**Comment by dannycoates** [comment]
Turns out it does log out of sync if `email` is included, but only once, because `/force_auth` adds a record to localStorage which prevents it from doing it again.

**Comment by rbillings** [comment]
**What type is it? How frequently will users hit this issue?**
Bug because it has incorrect expected results and can be repro’d
**Frequency**: low
**How was this found?**
PM filed in JIRA.
**What caused it?
Where was the gap which caused this issue**
Edge case
**Why didn’t we catch it sooner?**
Edge case for testing
**How do we ensure it doesn’t repeat?**
Discussed and added to exploratory tests.
**Is this a symptom of a broader issue**
No
