### ISSUE TITLE
Un-substituted % substitution in security code prompt

### ISSUE THREAD

**Issue by djmitche** [mozilla/fxa#4296]
In adding a new device via firefox.com/pair:

![Screenshot_2020-02-26 Enter security code to continue to %(serviceName)s](https://user-images.githubusercontent.com/28673/75394543-587f7500-58be-11ea-8da3-0fc074f2f368.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1212)
┆Issue Number: FXA-1212

**Comment by rbillings** [comment]
What type is it? How frequently will users hit this issue?
Bug because typo is in the UI. Users going through the CAD flow would see this.
Frequency: low
How was this found?
Developer filed from hitting the bug in production.
What caused it?
Where was the gap which caused this issue
This was caused by a typo 
Why didn’t we catch it sooner?
This flow is regularly tested, and this was missed.
How do we ensure it doesn’t repeat?
All emails and flows will continue to get regular testing.
Is this a symptom of a broader issue
No
