### ISSUE TITLE
fxa-amplitude-send: introduce JSON schemas at input/output points

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4355]
Use the FxA output schemas as input schemas here.

Might turn out to be a 5-pointer.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1251)
┆Issue Number: FXA-1251

**Comment by chenba** [comment]
@6a68 what's the "here" in the description referring to?  fxa-amplitude-send in general?

**Comment by 6a68** [comment]
@chenba Yup, the idea is to have JSON Schemas that describe the metrics events generated by the fxa server code (just before they are logged), and which can then be used to validate the inputs arriving at fxa-amplitude-send.

**Comment by 6a68** [comment]
@chenba I have some minimal schemas and a few realistic test cases in [a pipeline-schemas PR](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/512) that we can reuse in our metrics code, and which you can use as a starting point here. Note that the schema validates the `Fields` property of the PubSub message. You can examine the full message format in fxa staging, see if you can load [this URL](https://console.cloud.google.com/logs/query;query=jsonPayload.Fields.op%3D%22amplitudeEvent%22%0AjsonPayload.Logger%3D%22fxa-payments-server%22%0AlogName%3D%22projects%2Fmoz-fx-fxa-nonprod-375e%2Flogs%2Fstdout%22;timeRange=P7D;summaryFields=jsonPayload%252FFields%252Fevent_type:true:64:beginning?folder=true&organizationId=true&project=moz-fx-fxa-nonprod-375e). I wasn't sure how the stackdriver logging / splitter to amplitude PubSub topic would modify the events, but as you can see from the link above, the `jsonPayload.Fields` property of the messages look identical to what's logged by the fxa servers. So you could also generate test cases by observing the format of messages logged locally.

Further down the road, I was thinking we would eventually land these schemas and test events in the `fxa-metrics-processor` package, and probably just stick with the naming convention used by data engineering, just to make sharing simpler. There's not yet any code written to test the schemas validate the valid test events or fail the invalid test events. This work probably falls under https://github.com/mozilla/fxa/issues/4353, though I could see some argument for consolidating the schemas there sooner rather than later.

**Comment by 6a68** [comment]
@chenba Although, now that I think about it for a minute, there's really a two-way process at work here: going from the Joi schemas to JSON schemas on the fxa servers side, which will become the input schemas for fxa-amplitude-send, and also going from the [amplitude taxonomy](https://analytics.amplitude.com/mozilla-corp/manage/project/178231/schema?sort=name&direction=asc) backwards to JSON Schemas, for the output schemas for fxa-amplitude-send.

The fxa output / fxa-amplitude-send input schemas are covered by some other issues in the epic, though I don't think the fxa-amplitude-send output is covered anywhere else. So it'd be reasonable to focus on the outputs here, and maybe just use a simple placeholder schema to validate the inputs. Your call on how you want to slice the work up across issues, feel free to modify the issue titles / descriptions.

**Comment by chenba** [comment]
> Joi schemas 

@6a68 what Joi schemas are you referring to here?  The only relevant one I can think of is the request body schema in post-metrics.js on fxa-content-server.  It's not amplitude specific though.

**Comment by 6a68** [comment]
Yup, there's not a lot of explicit schemas to draw from. There are useful fragments in https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/server/lib/validation.js, as well as matchers (including fuzzy matchers) in https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/server/lib/amplitude.js (and similar spots on the other servers).

**Comment by data-sync-user** [comment]
➤ Barry Chen commented:

I'm closing this as done.  I've merged a patch that will validate the Amplitude events from auth, content, and payments with a JSON schema.  There's error reporting that will help to further refine the schema.  The validation can be disabled via configuration.
