### ISSUE TITLE
[payments] Repeated Clicks on Payment Submit Button Create Duplicate Subscriptions

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4386]
STR:

1. Go to payment page for a subscription plan
1. Enter credit card details
1. Click the submit button as fast as you can like you are playing StarCraft

Expected:

A subscription is created for the user.

Actual:

Multiple subscriptions are created.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1275)
┆Issue Number: FXA-1275

**Comment by lmorchard** [comment]
Hmm, I made an attempt to debounce the payment form submit button about a months ago by relying on the `inProgress` prop of the form component:

https://github.com/mozilla/fxa/commit/c018bc3e259967e98d788915ace23c1d9f027925

This gets set when a create subscription API request starts loading:

https://github.com/mozilla/fxa/blob/master/packages/fxa-payments-server/src/routes/Product/SubscriptionCreate/index.tsx#L65

But, since we're still seeing the issue, my guess is that there's enough time between button push, starting the request, and updating the app state that multiple requests can still get fired off.

So, I think an even more direct approach is required. That is, rather than relying on that roundabout state sequence, set a local state flag within the payment form component to disable the button and only clear that state flag when we're ready to take another submission.

**Comment by lmorchard** [comment]
Oh yeah, and additionally: The Stripe API supports an [idempotency key](https://stripe.com/docs/api/idempotent_requests) in requests. That's a value we can generate on the front end and only re-generate when we're absolutely sure we're initiating a new request - Stripe will then process only the first of many requests that are sent with that key.

Supporting the idempotency key would require some auth-server changes along with payment-server changes, so we might want to break up that work into two stages. (i.e. better button debouncing, followed by idempotency key support)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

An additional issue was reported today [~lorchard@mozilla.com]  - are we on track with completing this work by Thursday?

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

It's a known issue and on my todo list, but I haven't started it yet. Hoping to get it done by Thursday, but no progress yet

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Okay, now I have started on it and think I'm half-way there with at least a front-end fix. We might want to open a follow-up issue to address the server-side of things if we think the front-end fix isn't enough.

https://github.com/mozilla/fxa/pull/4476

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I dropped the story points estimate on this issue, because I closed it with just the client-side half of the proposed solution. That should fix the immediate problem.

Also filed a follow up issue with the server-side part of this - we could decide not to do it or backlog for awhile.

https://github.com/mozilla/fxa/issues/4516
