### ISSUE TITLE
[admin panel A1.0] Add server tests, version, heartbeat to admin-panel package

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4410]
Reference the payments server.

The config could also be set with expected types. This can/should likely be done before the security checklist (#FXA-1221).

Also, switching from Express to Hapi at this point could be worth looking into at this point, as I believe we've decided that should be our de facto standard.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1288)
┆Issue Number: FXA-1288

**Comment by LZoog** [comment]
@jodyheavener has expressed interest in grabbing this and since I won't get to it this sprint I'm going to add some more context for this issue:

We probably don't want to move from Express to Hapi so disregard that comment, or if we do, we'll do it in a followup.

Right now, you can only run frontend tests for this by running `npm run test`. Similar to how we have `fxa-payments-server` setup (I believe we run `npm run test:frontend` or `npm run test:server`), we need to also be able to run backend tests.

This issue mentions getting `__lbheartbeat__` and `__version__` setup. It can be closed with a PR that adds these (reference payments), adds a server testing option, and tests `__lbheartbeat__` and `__version__`.

I hope a good chunk of this is copy-and-pastable. We do have `fxa-shared` that I'd like to use for component sharing but I'm not sure that's applicable here. Also, Ben mentioned he made an express middleware to handle the load-balancer routes which can be copypasta'd and sent this link, I haven't checked it out: https://paste.ofcode.org/SDThrfGx4TdyZbhAuG5ZDw

For extra bonus points you could also implement CSP here with tests which we'll need to do shortly after or that can just be done separately. 👍
