### ISSUE TITLE
Sync will not accept my phone number (says invalid), probably because area code 689 is fairly new. [bz1619105]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4444]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1619105

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0

Steps to reproduce:

I tried to input my cell phone number into the https://accounts.firefox.com/sms?service web page to add synced Firefox to my phone.

Actual results:

I keep getting message "invalid phone number."

Expected results:

It should have accepted my phone number and I am guessing because 689 is a relatively new area code that it will not recognize it.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1307)
┆Issue Number: FXA-1307

**Comment by jbuck** [comment]
Fixed by #4471

**Comment by rbillings** [comment]
**What type is it? How frequently will users hit this issue?**
Bug because new area code wasn’t accepted.
**Frequency**: low
**How was this found?**
User filed in Bugzilla.
**What caused it?
Where was the gap which caused this issue**
New area codes weren’t accepted.
**Why didn’t we catch it sooner?**
We don’t watch new area codes
**How do we ensure it doesn’t repeat?**
Discussed how to be aware of these type of changes
**Is this a symptom of a broader issue**
No
