### ISSUE TITLE
Emit SQS event on profile-server changes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4499]
Right now the profile-server emits an SQS event that the auth-server catches, and then pushes out the notification to a users devices.

This should also emit a profileChanged Service Notification event for the event-broker.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1338)
┆Issue Number: FXA-1338

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~clewis@mozilla.com] to grab related issue from SV's smoke test results

**Comment by vbudhram** [comment]
Currently, the profile server listens for the `profileDataChanged` SQS message and then flushes its cache. 

When a user changes their display name/avatar, the profile server emits a SQS message the auth-server receives and then sends connected devices a [push notification](https://github.com/mozilla/fxa/blob/e914b95ace6ac7170c858283b3df7947cef013d1/packages/fxa-auth-server/lib/profile/updates.js#L16). If at this point we emit a `profileDataChanged` message, the profile-server should probably ignore it since it has already process it. 

Otherwise, the two servers could end up sending messages back and forth, and get stuck in a loop.
