### ISSUE TITLE
I swapped around emails on my two accounts and now I can't sign-in to either due to a "Primary account email required for sign-in" error. [bz1621590]

### ISSUE THREAD

**Issue by bug-mirror** [mozilla/fxa#4504]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1621590

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0

Steps to reproduce:

Note: I tried posting a question on Mozilla Support (https://support.mozilla.org/en-US/questions/1280648) but haven't received a response so I'm trying here.

I have two accounts, one I don't use too much anymore. I wanted to swap the emails on my accounts, so my newer account would use the email I use more often and my older account would use the other email. I did this and it seemed to work. Firefox Accounts sent the "Primary email updated" notification for both accounts even. 

Actual results:

When I try to login to Firefox Sync/Firefox Accounts now with the new primary email for either account I get a message that says "Primary account email required for sign-in", even though it is the primary email for that account.

Expected results:

I should have been signed in to the account.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1341)
┆Issue Number: FXA-1341

**Comment by rbillings** [comment]
What type is it? How frequently will users hit this issue?
Bug because email was cached incorrectly. Reports were about 1x/week.
Frequency: low
How was this found?
Users file in bugzilla.
What caused it?
Where was the gap which caused this issue
This was caused by an error storing old email addresses in local storage.
Why didn’t we catch it sooner?
Edge case for testing
How do we ensure it doesn’t repeat?
Automation has been created to cover this scenario.
Is this a symptom of a broader issue
No
