### ISSUE TITLE
Not sending `postAddAccountRecovery` email after recovery code setup through new flow

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#4613]
We send this email template when someone sets up a recovery key via settings, but if they use the new recovery key setup flow we won't send it.

cc @davismtl this can affect measuring rate of recovery key setup, before we had `fxa_pref - confirm_recovery_key_success` we used this template to measure how many users setup codes per day.

to get around this problem i created a meta-event in amplitude called `fxa - recovery_key_setup` that fires if either the postAddAccountRecovery email template is sent OR `fxa_pref - confirm_recovery_key_success` is fired. Note however there was a period between 3/2 and 3/10 that, for the new flow only, we were not logging the new events or recording the email template (since it wasn't being sent). So we have incomplete data for recovery key setup during that period.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1398)
┆Issue Number: FXA-1398

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Pulling this into current sprint since it is metrics related.

**Comment by rbillings** [comment]
What type is it? How frequently will users hit this issue?
Bug because recovery email wasn’t being sent.  Unclear how many users hit this, but it was between 3/2 and 3/10.
Frequency: low
How was this found?
Developer filed from metrics.
What caused it?
Where was the gap which caused this issue
This was caused by a new recovery flow
Why didn’t we catch it sooner?
There is test case coverage for this, unclear why it wasn’t found.
How do we ensure it doesn’t repeat?
All emails and flows will continue to get regular testing.
Is this a symptom of a broader issue
No

**Comment by rbillings** [comment]
Also: there is automation for recovery key flows, but it is currently in the group of stage failures. The current work to fix stage failures will increase coverage and reduce the likelihood of another incident.
