### ISSUE TITLE
WError: Failed to send email

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#4636]
https://sentry.prod.mozaws.net/operations/auth-prod/issues/7630845/

```
WError: Failed to send email
  File "/app/lib/error.js", line 864, in Function.AppError.cannotSendEmail
    return new AppError({
  File "/app/lib/routes/utils/email.js", line 21, in Object.sendError
    return error.cannotSendEmail(isNewAddress);
  File "/app/lib/routes/utils/signin.js", line 402, in null.<anonymous>
    throw emailUtils.sendError(err, isUnverifiedAccount);
  File "/app/lib/routes/session.js", line 209, in async handler
    await signinUtils.sendSigninNotifications(
...
(4 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1403)
┆Issue Number: FXA-1403

**Comment by vbudhram** [comment]
I've looked at a few things but couldn't really pinpoint anything

* No deployments that could have interrupted our email service
* No known developer testing with email service
* No more errors have occurred since

I'm going to close this for the time being but continue to monitor it in sentry to see if the error comes back.
