### ISSUE TITLE
TypeError: can't access property "toLowerCase", p is undefined

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#4784]
https://sentry.prod.mozaws.net/operations/fxa-payments-stage/issues/7737531/

```
TypeError: can't access property "toLowerCase", p is undefined
  at c (components/PaymentConfirmation/index.tsx:95:16)
  at call (store/sequences.ts:57:5)
  at action (store/sequences.ts:53:46)
  at call (store/sequences.ts:70:11)
...
(35 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1505)
┆Issue Number: FXA-1505

**Comment by data-sync-user** [comment]
➤ David Justice commented:

There are only 3 instances of this event and they are all from a 1 hour span on April 3rd. It seems that there was a hiccup with the `brand` being provided which may indicate there was something with the version pushed to stage at that time or that there was an issue with stripe. I believe the issue has since been resolved.
