### ISSUE TITLE
[setup] Create HTML semantics chart (or image) of UI screens

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4824]
To ensure elements are semantically correct the first time and for developer semantic confidence, prior to development of the UI we should have a reference chart or image of what the generated HTML should look like. This includes all heading levels, lists, landmarks (nav, header, footer), section elements, buttons vs links, etc.

This can be closed with a comment of screenshots of the wires with hand-drawn DOM tags next to them, nothing fancy.

This should cover 1) the main Settings page (and with one drop-down from the header) and complicated screens including the 2) two-factor auth flow and 3) avatar flow. These should help cover other "inner view"s for reference while working on the UI.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1544)
┆Issue Number: FXA-1544

**Comment by LZoog** [comment]
NOTE: In the `fxa-content-server`, we tend to prefer `background-image` over using `img`. We should use `img` where we can because it’s semantically preferred, but in cases where we need to use a `background-image`, we need to ensure that the div has an `aria-label=“text"` on it with text for screenreaders, essentially acting as “alt text."

For the avatar adjustment/cropping screen we can reference the current DOM, it LGTM, but it definitely needs some a11y beefing (noted in related ticket).

Links labeled as “link (external)” should use the `LinkExternal` component to ensure consistency on receiving `rel=“noopener noreferrer”.

---

![settings](https://user-images.githubusercontent.com/13018240/79361710-4b205780-7f0b-11ea-8879-ccdf1d1b4e55.png)
![avatar-menu](https://user-images.githubusercontent.com/13018240/79361753-583d4680-7f0b-11ea-8d1e-837b7128ff93.png)
![profile](https://user-images.githubusercontent.com/13018240/79361719-4eb3de80-7f0b-11ea-8679-cae55d5e170e.png)
![1-2fa](https://user-images.githubusercontent.com/13018240/79361768-5ecbbe00-7f0b-11ea-9862-22e8efe97212.png)
![2-2fa](https://user-images.githubusercontent.com/13018240/79361773-5ffceb00-7f0b-11ea-9418-570e85f6beb2.png)
![3-2fa](https://user-images.githubusercontent.com/13018240/79361780-625f4500-7f0b-11ea-9d76-918ee5e3eb2d.png)
![mobile](https://user-images.githubusercontent.com/13018240/79361794-655a3580-7f0b-11ea-9686-120b319c7bf3.png)

**Comment by jodyheavener** [comment]
Off the top, I am seeing a lot of `img`s. I'm betting most of these could be SVGs over actual images. And if that is the case, my preference is to use actual `<svg>` and **not** `<img src="blah.svg" />` or any sort of base64 encoding, specifically for styling purposes.

**Comment by jodyheavener** [comment]
For clarification, is the difference between the buttons that are labelled "link" and the buttons that are labelled "button" that the links take you to a new page and the buttons perform an action?

**Comment by LZoog** [comment]
> Off the top, I am seeing a lot of `img`s. I'm betting most of these could be SVGs over actual images. And if that is the case, my preference is to use actual `<svg>` and **not** `<img src="blah.svg" />` or any sort of base64 encoding, specifically for styling purposes.

Ah yeah, I can see that. There's also a class-based approach where you add a class to the SVG and then with the class we can specify `fill`. I like the idea of inlining SVGs where we can, especially because we don't have to bust any caches and they can be gzipped + reduced network requests, although I don't like having hard `width`/`height` properties on them and prefer to do that with CSS. This kind of leads into a question on the best way to handle our SVGs though.

**Comment by jodyheavener** [comment]
I'm not stuck on this idea, but because each section is a `<section>` I wonder if we can turn each section title from an `<h3>` to an `<h1>` to provide better [document outlines](https://webdesign.tutsplus.com/articles/the-truth-about-multiple-h1-tags-in-the-html5-era--webdesign-16824). Would also likely mean bumping the row titles up to an h2 or h3.

**Comment by jodyheavener** [comment]
You can definitely say no, but I wonder if it would be beneficial to add a11y notes to this doc as well for reference? e.g. flash messages having `role="alert`

**Comment by jodyheavener** [comment]
> Let me know if you disagree with this approach

100% agree with this approach. 😄

**Comment by LZoog** [comment]
> I'm not stuck on this idea, but because each section is a `<section>` I wonder if we can turn each section title from an `<h3>` to an `<h1>` to provide better [document outlines](https://webdesign.tutsplus.com/articles/the-truth-about-multiple-h1-tags-in-the-html5-era--webdesign-16824). Would also likely mean bumping the row titles up to an h2 or h3.

The "Profile," "Security," "Connected Services" (`h2`s) are part of those sections so I guess that would mean bumping the `h2`s to `h1`s and `h3`s to `h2`s etc. I disagree that having an `h1` at the top of sections provides a better document outline though, since all of the sections fall under "Firefox Accounts" (the page `h1`). I'm picturing this with a doc outline visualization tool like Wave. It seems kind of strange to me to have "Profile" at the same heading level as "Firefox Accounts", however this is just my opinion.

> You can definitely say no, but I wonder if it would be beneficial to add a11y notes to this doc as well for reference? e.g. flash messages having role="alert"

I strongly considered this, but honestly these images would be way, way messier than they already are. I tried to limit them to just be a DOM element references, I do have all a11y recommendations in the ticket creation for those elements though so they'll definitely be readily available when someone's working on them. 😁

**Comment by jodyheavener** [comment]
> It seems kind of strange to me to have "Profile" at the same heading level as "Firefox Accounts"

That definitely was the case for a very long time, but my understanding with modern HTML semantics is that headings are contextual, so while an H1 could represent the title of an entire document, an H1 could also represent the title of an entire Settings section. But I'm really not stuck on this, just a thought.

**Comment by jodyheavener** [comment]
LGTM 👍

**Comment by LZoog** [comment]
> That definitely was the case for a very long time, but my understanding with modern HTML semantics is that headings are contextual, so while an H1 could represent the title of an entire document, an H1 could also represent the title of an entire Settings section. But I'm really not stuck on this, just a thought.

Yeah, it could go either way. SEO isn't a factor for us since these pages aren't indexed. I guess my only "real" argument for keeping them `h2`s would be that when using a screenreader, you can jump to heading levels that match. If you're on an `h2`, you can go forward/back to hit other `h2`s. It might not be ideal to include "Firefox Accounts" within that same jump range, so unless anyone else has a reason to prefer `h1`s or you've got a counter point to that I'd suggest they stay `h2`s. 🤔

> LGTM 👍

Sweet! I'll adjust the link/button text note so it's more visible for the main settings screen too and then I'll close this issue.
