### ISSUE TITLE
Can we make the npm audit flow less annoying?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#483]
Imagine you have a simple PR that you need to get out for a point release. You open said PR but your build fails because of a new security advisory for an unrelated dependency that already exists in `master`. So now you have a completely unrelated problem that you are forced to resolve before you're allowed to deploy your fix that makes a broken thing in production not broken any more. The tail is wagging the dog.

This is not a frequent occurrence, but I wouldn't exactly call it rare either. And it happens at the most annoying times almost by definition, when you have some kind of fix or improvement for an existing problem. It's maddening.

Could we tweak our tooling around `npm audit` in CI to be a little bit smarter? For instance, if there are no changes to `package.json` or `npm-shrinkwrap.json` and the build is for a pull request, don't fail that build? Perhaps in combination with regular, scheduled builds of `master` so that we see `npm audit` failures there and can target them without blocking other work?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-660)
┆Issue Number: FXA-660

**Comment by philbooth** [comment]
BUMP because #2328

**Comment by 6a68** [comment]
Related: In #2234, I've just landed audit-filter integration into the lint command for all but two of the monorepo packages. (The remaining two are tracked by #2229.)

Once we have all our dependencies up to date, we might try using one .npmrc for the whole monorepo, instead of per-package .npmrc files. Might make it a lot easier to handle these issues when they come up, even if it's not quite a fix for this issue.
