### ISSUE TITLE
[main] Build out Settings > Profile except emails

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#4901]
Using the reusable unit row and data from the already completed issues in this user story, create the Profile section.

Add the routes for `avatar/change`, `display_name`, and `change_password` on the corresponding buttons, setting them up for "inner view" functionality work. 

If a user has a profile image set, "Add" in this section should become "Change". Similarly, "Add" for display name should be "Change".

"Primary email" and "Secondary email" will be done in follow up issues.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1608)
┆Issue Number: FXA-1608

**Comment by LZoog** [comment]
It turns out this ticket is 95% finished with the merge of #5513 and #5318. 🙌

The only thing remaining is adding the routes to the existing buttons/links in the Profile section. This is very trivial, but blocked by #4899. I'm going to pull this into the current train (174), mark it as complete, and add the trivial task to #4899. It doesn't increase the scope of that ticket.
