### ISSUE TITLE
Wrap up 2FA flow changes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5089]
Currently have a working flow that takes users through 2FA setup as part of the login flow if acr_values=AAL2 is passed in the query string and the user doesn't yet have 2FA setup.

This bug captures remaining work to clean up these changes: move duplication between settings and login flows to shared code, add tests, add a 123done button for the prompt=none and 2FA required case, get quick UX signoff on changes.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1750)
┆Issue Number: FXA-1750

**Comment by 6a68** [comment]
Adding comments and attachments on the github side, because Jira image attachments seem to have their order scrambled at random.

-----

This particular issue (enabling FxA relying parties like AMO to require users enable 2FA as part of the login flow) has a fairly long history, so I'll attempt to summarize here to reduce the amount of research needed:

AMO has had some issues with automated bot submissions. They would like to require addon developers have 2FA enabled to reduce bot spam. However, for AMO to know if a user is a developer, the steps are a little involved:

- user visits AMO, clicks login button
- user is redirected to FxA to login, goes through login flow
- user is redirected back to AMO once logged in
- AMO can then check if the user is a developer, and if the user has 2FA enabled.

At this point, if the user is a developer and does not have 2FA enabled, AMO wants to:

- redirect the user back to FxA, skipping the login step, but sending the user into a 2FA setup flow
- user will enable 2FA for their FxA account,
- then redirect back to AMO after 2FA setup is complete
- AMO will verify again the user is a developer and has 2FA, at which point, the user is logged in (whew!).

To add a tiny bit more background, OpenID Connect provides a special query string parameter, `prompt=none`, which AMO can put in tthe FxA login request, along with a user identifier (either the user's email address, or an ID token). Very roughly, if the user has an active FxA session, then the the explicit login step will be skipped. This was already implemented in another bug.

This current bug is concerned with taking the existing FxA 2FA setup flow, which previously only lived in the settings page, and adapting it to the different UX challenges of a login flow.

-----

OK. I'm interested in getting UX feedback on the new flow. Here are screenshots of the existing settings flow (note that you can enable 2FA by either scanning a QR code or manually typing in the key, so those aren't successive steps):

<img width="775" alt="Screen Shot 2020-04-24 at 5 38 16 PM" src="https://user-images.githubusercontent.com/96396/80267580-9696dc00-8656-11ea-9581-ec5f7fea9594.png">

Click the 'Enable' button to see the 2FA setup screen:

<img width="757" alt="Screen Shot 2020-04-24 at 5 38 23 PM" src="https://user-images.githubusercontent.com/96396/80267579-9696dc00-8656-11ea-8301-2a41372ec100.png">

Most users will just scan the QR code. However, by optionally clicking the 'Can't scan code?' link, 2FA can be configured by manually typing this key into the app. Note we're now in a modal view on the settings page:

<img width="793" alt="Screen Shot 2020-04-24 at 5 38 30 PM" src="https://user-images.githubusercontent.com/96396/80267577-95fe4580-8656-11ea-98bb-7e471e7ed06d.png">

Once the 2FA app is configured, it generates a TOTP code, which the user then enters into the form, clicking 'Ready'. The user is then sent into a recovery keys modal flow:

<img width="746" alt="Screen Shot 2020-04-24 at 5 38 49 PM" src="https://user-images.githubusercontent.com/96396/80267575-94cd1880-8656-11ea-8a7a-a2d757e8b724.png">

<img width="706" alt="Screen Shot 2020-04-24 at 5 38 56 PM" src="https://user-images.githubusercontent.com/96396/80267573-926abe80-8656-11ea-9932-c199538c7005.png">

Once the user pastes a recovery key in the final screen, 2FA setup is complete.

-----

Here is the equivalent 2FA setup flow as part of the login flow. Because this is a prompt=none flow, there won't be an initial 'confirm your email address' screen, we just jump straight into 2FA setup:

<img width="1170" alt="Screen Shot 2020-04-24 at 5 33 09 PM" src="https://user-images.githubusercontent.com/96396/80267709-4b30fd80-8657-11ea-9566-058c8221dabc.png">
<img width="1170" alt="Screen Shot 2020-04-24 at 5 33 13 PM" src="https://user-images.githubusercontent.com/96396/80267710-4bc99400-8657-11ea-813d-7e21faba030e.png">
<img width="1170" alt="Screen Shot 2020-04-24 at 5 33 16 PM" src="https://user-images.githubusercontent.com/96396/80267712-4c622a80-8657-11ea-890b-a2811e21073b.png">
<img width="1170" alt="Screen Shot 2020-04-24 at 5 33 19 PM" src="https://user-images.githubusercontent.com/96396/80267714-4cfac100-8657-11ea-9bf5-bc48c9466b24.png">
<img width="1170" alt="Screen Shot 2020-04-24 at 5 33 23 PM" src="https://user-images.githubusercontent.com/96396/80267715-4d935780-8657-11ea-8167-c6691902414e.png">








 I have a bit more cleanup to do before opening a pull request, should have that out Monday.

Things that particularly need UX feedback in the new flow:

1. The settings-based 2FA setup flow does not have titles for some of the individual steps, while the login flow has titles for most screens. I've tried hard to stick with the prevailing pattern of keeping the login flow titles short and direct (a scannable, one-line explanation of the action required by the user), but could use guidance here.
2. I've added an introductory "you need to set up 2FA" screen, but the copy in the body of the page is borrowed from the settings 2FA setup screen. I'm not sure it quite conveys that this is a required step. I'm also not completely sure it's worth having an extra step like this, but it seems like we need to do something to help the user understand what's happening.
3. The settings-based 2FA flow is not in a login flow context, so the location of cancel affordances is a little different. I've been liberal with the cancel links in the new 2FA login flow, could use feedback on whether we need a "Cancel setup" at each step of the flow or not.
4. I'm not sure what error we want to display if the user decides to cancel 2FA setup. I want to avoid simply redirecting back to AMO, which presumably would just create a redirect loop: AMO would check that the user is a developer, and see that the user does not have 2FA, and they would bounce the user back to FxA again :-(. This means we need to clearly warn the user that they won't be able to login until they enable 2FA.

**Comment by 6a68** [comment]
@pwalm and I discussed the above questions today. He also dug up a UX mock with suggested copy changes:

![image](https://user-images.githubusercontent.com/96396/80431812-4ebac380-88a7-11ea-9771-3d4c303f2c73.png)

**Comment by 6a68** [comment]
Landed in #5131. Closing.
