### ISSUE TITLE
Provide a way on the Web for FxA relying parties to determine if the user has previously logged into FxA

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa#51]
As a developer, I want to know whether my user is a user of FxA, so I can customize her experience in my Web application.

If the Web application knows the user is already an FxA user, then it might prioritize getting the user to log in because she already has an account.

This might eventually be able to provide a more SSO-like experience.

**Comment by ckarlof** [comment]
@andymckay asked for this because it would help with a Payments integration. @bryanbell also suggested it would helpful in IdeaTown.

**Comment by shane-tomlinson** [comment]
What are the privacy repercussions of this?

**Comment by rfk** [comment]
We've already explicitly traded off "leak whether you've got an account with us" in order to get better UX in a variety of places, but those places required you to know the user's email address.  IIUC this ask is more "tell whether the current visitor, whoever they are, has a Firefox Account"?

I feel like we must explicitly scope this down to trusted reliers, at least initially.  We might even get a lot of mileage out of setting a flag cookie on a shared domain suffix.

@ckarlof can you comment on prioritization/timelines for this?

**Comment by ckarlof** [comment]
Agreed that this should be initially limited to internal reliers. 

Given that we don't have many Web based reliers at the moment, it's fairly low priority, IMO. At the earliest, probably Q4.

**Comment by ryanfeeley** [comment]
à la Messenger
<img width="1198" alt="messenger" src="https://cloud.githubusercontent.com/assets/68213/9533338/63fc3fca-4cdf-11e5-802a-3465b370c84b.png">

**Comment by billmaggs** [comment]
After discussion is was agreed that the most logical initial internal user of this feature would be a developer of a Mozilla service such as Hello. Hello hasn't currently prioritized this work. I am going to put in a Feature in the Hello Desktop and Fennec clients, link to this issue,  and let Romain know, so he can prioritize it up or down.

**Comment by rfk** [comment]
Exporting these FEATURE cards from Aha has not turned out to be useful in practise, I'm closing them in favour of more direct use of Aha.

This feature lives at: https://mozilla.aha.io/features/FXA-32

And it's references in: https://mozilla.aha.io/features/HELLO-392
