### ISSUE TITLE
Disallow creating a new Firefox Account with a Firefox Private Relay address

### ISSUE THREAD

**Issue by diox** [mozilla/fxa#5128]
STR:
- Create a Firefox Private Relay address for your Firefox Account, note the address
- Log out or use a new Private Window and create a new Firefox Account using the relay address

Expected result:
- Account creation with the relay address fails

Actual result:
- A new Firefox Account is created with the relay address as primary email.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1772)
┆Issue Number: FXA-1772

**Comment by jrconlin** [comment]
Not sure if it's covered, but probably also want to limit services like these: 

https://duckduckgo.com/?t=ffab&q=ten+minute+mail&ia=web
https://duckduckgo.com/?q=temporary+email&t=ffab&ia=web
https://github.com/ivolo/disposable-email-domains

Rationale: 
Using a disposable email address to get a disposable email address generator would be useful in order to break tracing chains back to an abusive individual.

**Comment by diox** [comment]
Absolutely, but that would be more of an issue on fx-private-relay side. (side note: would be interesting to compare https://github.com/wesbos/burner-email-providers/ with  https://github.com/ivolo/disposable-email-domains)
