### ISSUE TITLE
Survey A11y issue tracker

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5165]
While the survey itself has good a11y, there are a few things we'll need to make sure we do to make the experience accessible...Feel free to add to this checklist:

1. Add a title to the iframe "optional survey"
1. Add an aria-label to the button "dismiss"

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1793)
┆Issue Number: FXA-1793

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

from mtg:

This is not a blocker for initial feature. We should get these answers though.

**Comment by data-sync-user** [comment]
➤ David Justice commented:

RTL => https://github.com/mozilla/fxa/pull/5333#discussion_r426738151

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

I know that [~lzugai@mozilla.com] is busy with the settings work, but as our very own a11y expert, maybe we could have her do an audit and track the issues here. I'll ping her to see availablility and maybe setup a zoom session to review.

**Comment by Rudresh22** [comment]
Hello, can I work on this issue?

**Comment by aayushi221** [comment]
Hey!
I'd like to work on this issue if it's still open. 
I'd also like to request a bit of guidance as to how to start this.

**Comment by LZoog** [comment]
I'm going to close this issue. We had an audit of the survey in July 2020 and filed related issues.

It looks like we've closed the related issues around a11y issues here, but #5839 is open. I think that might be a little hairy to get set up though and wouldn't call it a `good first issue`, we need some docs around surveys and I'm not sure if that issue is still valid. The FxA team is currently triaging old issues and will assess then if it can be closed. @Rudresh22 @aayushi221   please feel free to check out our other `good first issue`s!
