### ISSUE TITLE
Add long poll for detecting an added device after CAD QR

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5239]
We should in theory be able to use the `/attached_clients` endpoint to detect when a user has logged into a new device. Once they log in, the QR code page will be redirected to a "Device connected" page.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1845)
┆Issue Number: FXA-1845

**Comment by rfk** [comment]
FWIW, `/attached_clients` is a pretty expensive endpoint that slurps a *lot* of stuff out of the db. If you want to poll, it may be worth considering adding a new route under in the [`/signinCodes` namespace](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#post-signincodesconsume) to poll for the result of a specific code, perhaps e.g. `/signinCode/status` or similar.

**Comment by vbudhram** [comment]
@rfk That makes sense, I'll investigate adding another route to do this 👍

**Comment by vbudhram** [comment]
> I'll investigate adding another route to do this

I've looked into this a bit while building out https://github.com/mozilla/fxa/pull/5288 and here are some thoughts I had

* The `/account/devices` states it was built for getting devices that can you can send commands too, but I don't see why we couldn't use it for this?
* The SQL behind the scene joins [4 tables](https://github.com/mozilla/fxa/blob/00434b4e345f48228010ffac3ec3894f1b9a430e/packages/fxa-auth-db-mysql/lib/db/schema/patch-096-097.sql#L125), this seems a bit heavy but maybe ok for this experiment?
* Adding an endpoint that checks for sign-in code login seems like it could provide a confusing user experience since deeplinking in practice is flakey and breaks a bit
* We could add another route under `/signinCode/` that is optimized for checking new device logins

**Comment by rfk** [comment]
> Adding an endpoint that checks for sign-in code login seems like it could provide a confusing 
> user experience since deeplinking in practice is flakey and breaks a bit

Ah OK, so you want "wait until a new device has joined" regardless of *how* that new device joined.  👍
