### ISSUE TITLE
Update FxA Subscription Support Form

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5302]
Changes:

1. For the product drop down: add `Firefox Account` as an option
1. For the issue drop down, update the options to be:
  * Payment & Billing
  * Account Issues
  * Technical Issues
  * Provide feedback / Request features
  * Not Listed
1. Ensure Product label is being sent to Zendesk

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1879)
┆Issue Number: FXA-1879

**Comment by ValentinaPC** [comment]
Verified this in stage, using Fx76 and Windows 10 (64-bit).
Observed the following:
- extra "Getting started" option in the issue dropdown;
- product name appears in the confirmation popup, but the issue does not. (https://github.com/mozilla/fxa/issues/5298)

@jackiemunroe is the extra option intended?
Also, is there an option for QA to check if the product label was sent to Zendesk?
Thanks!

**Comment by jackiemunroe** [comment]
@ValentinaPC 

"Getting Started" should have been removed - I will open a PR to fix this
For the confirmation popup issue, it will be fixed with https://github.com/mozilla/fxa/pull/5406

I don't believe we have a way for QA to verify what is sent to Zendesk - I have verified that the data is propagating manually. @clouserw - do you know if we have any options for QA here?

**Comment by clouserw** [comment]
I don't know of one

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx76 and Windows 10 (64-bit).
Postfix screenshot below.
![csform](https://user-images.githubusercontent.com/15685960/83489195-bbcd0480-a4b6-11ea-9728-05b89c741103.png)
