### ISSUE TITLE
Add Script to Remove Test Users from Dev Stripe

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5326]
Our functional tests create subscriptions with test users on SUB_PLAT_DEV.  We should have a script that we can run periodically to remove those users.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1893)
┆Issue Number: FXA-1893

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Les says this script exists, but it's not run regularly.  We should add it to a schedule.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

CircleCI can run cron jobs (ask clouserw for an example).

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Here's the script. Needs a stripe key. Should be run on a schedule.

https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/scripts/clean-up-old-ci-stripe-customers.js

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

This script recently saw some changes to make it work with TypeScript. Feel free to ping me if there are issues using it.

**Comment by lmorchard** [comment]
Digging into this and found that I needed to make a few tweaks to get the script working again. Also, an `npm install -g ts-node` is necessary for the new shebang to work.

But, doing a manual run resulted in `Deleted 1215 customers`. Did a dry run first to make sure all those customers were created by content-server functional tests. The script defaults to looking for customers with an email pattern of 'signin.*@restmail.net', which matches what we create for those tests.

And, now that I'm looking at things, I think this script might be best run after content-server functional tests rather than a scheduled task. Seems like a quick tag-along after the tests that create these customers, instead of setting up a new job / executor / whatever
