### ISSUE TITLE
[iOS] Account picture modal highlighter Ui issues

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5346]
**Build**
Stage [Train 1.170.3]

**Affected platforms**
iOS 13.4.1

**Steps to reproduce**
1. Launch Firefox and login using a Firefox account.
2. Go to https://accounts.stage.mozaws.net/settings/
3. Click "Add" button from the Account picture area.
4. Observe the account picture modal highlighter.

**Expected results**
There are no Ui issues encountered.

**Actual Results**
- The highlighter is interrupted and it doesn’t correctly surround the modal
- Highlighter right corners are not curved.

![Screenshot_17](https://user-images.githubusercontent.com/18114210/82219148-8b696000-9925-11ea-8229-8e9fea3f3c47.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1906)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/13276/screenshot-1.png">screenshot-1.png</a>
┆Issue Number: FXA-1906

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

The `avatar-options` nav is definitely receiving focus here for some reason rather than the individual items inside (see screenshot).

This is low priority since it's still functional, and it might not be straightforward to fix because `modal-panel-mixin` has some custom JS to set tabbable elements, and this issue seems iOS specific.

screenshot-1.png|thumbnail!

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is no longer applicable considering the new Settings page replacement.
