### ISSUE TITLE
Audit server metrics for eco_anon_id mgmt

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5351]
We should verify that all the correct metrics are logged for the new AET feature. This includes events for creation, deletion, updated etc.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1909)
┆Issue Number: FXA-1909

**Comment by 6a68** [comment]
I did find one obscure spot we missed, and updated the auth-server docs with another missed update:

New endpoints specific to AET

Profile server

`GET /v1/ecosystem_anon_id`
- added a logger call. ✅

`POST /v1/ecosystem_anon_id`
- we log using mozlog under the `routes.ecosystem_anon_id.post` route header

Auth server

`PUT /account/ecosystemAnonId`
- we log using mozlog via a `log.begin('account.updateEcosystemAnonId')` call

Auth-db server

`PUT /account/:uid/ecosystemAnonId`
- logging is baked in for all db-server routes, including this new one


The eco_anon_id otherwise flows from auth-db to auth via the existing account-related GET calls, and from auth to profile via the existing GET _core_profile call.
