### ISSUE TITLE
The activation of the Secure Proxy extension fails at sign in

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5465]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.172.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Preconditions:
 - have the Secure Proxy extension installed

#### Steps to reproduce
1. Click on the SP icon from the toolbar.
2. Click “Continue” from the onboarding panel and finalize sign in.
3. Click again the SP icon from the toolbar 

#### Expected result:
- The extension is active.

#### Actual result:
- A “Sign in failed” error message is displayed after signing in. The extension is not active.

#### Notes:
- Reproducing with the live, intermediate and message Secure Proxy version.
![sign in failed](https://user-images.githubusercontent.com/15685960/83014841-19310380-a028-11ea-9d77-7ecb1f67a767.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1990)
┆Issue Number: FXA-1990

**Comment by rbillings** [comment]
**What type is it? How frequently will users hit this issue?**
Bug because users were unable to sign into the Secure Proxy addon.
**Frequency: low**
**How was this found?**
This was found after a FxA release.
**What caused it?**
TTL token times were being lowered and hit an unexpected low threshold.
**Where was the gap which caused this issue**
This was not found on staging as the environment wasn’t set up to reflect the TTL changes.
**Why didn’t we catch it sooner?**
The original staging site for Secure Proxy was set up to use the prod_auth_server, as Cloudflare rejected our staging certificates.
**How do we ensure it doesn’t repeat?**
* We are working with Cloudflare to accept staging certs
* Staging will be updated to connect to the staging_auth_server, not prod
* Automation will be written to cover Secure Proxy account creation and sign in
* We will create a set of prod automation smoke tests to be run after every release
**Is this a symptom of a broader issue**
This elevated the issue of the staging site not using staging authentication, creating a gap in coverage. It also brought up the need to create an automated smoke test for production, especially for FxA relying parties.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This was resolved last week when we increased the TTL from 1 to 2.

**Comment by ValentinaPC** [comment]
Verified as fixed in prod, using Fx76 and Windows 10 (64-bit).
Postfix video below.
![SPsignin](https://user-images.githubusercontent.com/15685960/83607841-94dd0400-a584-11ea-8925-444163f75b87.gif)
