### ISSUE TITLE
The password field focus changes from red to blue while the error is still displayed

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5607]
**Note**
This is a follow-up bug for #5312

**Build**
Stage [Train 1.174.0]

**Affected platforms**
Windows 10 x64
Android  9

**Steps to reproduce**
1. Launch Firefox and login using a Firefox account.
2. Go to https://accounts.firefox.com/settings
3. Click on "Change" button from Password section.
4. Type the old password in all 3 fields: “Old password”, “New password” and “Re-enter password”.
5. Click on “Change” button.
6. Click on “Change” button a second time.

**Expected results**
The field focus where the error points to remains red.

**Actual Results**
The field focus turns from blue to red after clicking a second time on “Change” button.

![issue6](https://user-images.githubusercontent.com/18114210/84148623-f3641f80-aa67-11ea-9b64-2bb380a56060.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2074)
┆Issue Number: FXA-2074

**Comment by byrw** [comment]
Can I work on it?

This is happening because of the function `markElementInvalid()` (responsible for marking the field as red) is being called before the tooltip is destroyed. To solve this, is necessary to just change the function `markElementInvalidAndMaybeFocus()` to `maybeFocus()`, and use `markTheElementInvalid()` after tooltip being destroyed.

**Comment by LZoog** [comment]
Hey @byrw, sure thing! I won't get to this in the next week so that would be really helpful, thank you. :)
