### ISSUE TITLE
Privacy Notice links return “Page not found” error when they are accessed from Firefox Services

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5626]
**Build**
Prod [Train 1.170.0]

**Affected platforms**
Windows 10 64-bit
Android 9 

**Steps to reproduce**
1. Go to https://addons.mozilla.org/en-US
2. Click on the “Register or Log in” button.
3. Type the email address and click on the “Continue” button.
4. Click on “Privacy Notice” link.
5. Click on “privacy policy” link.

**Expected results**
Mozilla Privacy Policy [page](https://www.mozilla.org/en-US/privacy/) is successfully displayed.

**Actual Results**
- “Page not found” is displayed. 
- The user is redirected to the incorrect url: https://accounts.firefox.com/https://www.mozilla.org/privacy/?client_id=a4907de5fa9d78fc&scope=profile&state=b163425f124f74a7062a6c7ed7e9d32734412f5c6a92acbffa8af00c9b0e6c7e%3AL2VuLVVTL2ZpcmVmb3gvI2xvZ2lu&action=signin
- https://accounts.firefox.com/ should be removed from the above link in order to display the correct page

**Notes**
- This issue also reproduces when trying to login on: Monitor, Pocket, Send, SUMO.

![issue8](https://user-images.githubusercontent.com/18114210/84254836-6cbc4a80-ab1a-11ea-96e5-01f27f2de9b5.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2085)
┆Issue Number: FXA-2085

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Is this still reproducible? I can't seem to reproduce it myself in any FXA environment. Wondering if maybe we somehow fixed it in a release since this issue was filed?

Tried opening the links in the same page and in a new tab. Either way, the links on the legal page seemed normal

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

Yes! The issue is still reproducible in Prod Train 1.176.0. Please note that the bug is encountered only when accessing the Privacy Notice (or Terms of Service) links from Firefox Services login/register pages. E.g:

  1. Access one of the following pages: Monitor ( https://accounts.firefox.com/oauth/?client_id=a4907de5fa9d78fc&scope=profile&state=1b1fd58f11c1aa51c46c1457f9da1b53f61f3ffbe0f0fe567f7159f9c0e52524%3AL2VuLVVTL2ZpcmVmb3gv&action=signin ), Addons ( https://accounts.firefox.com/oauth/?client_id=a4907de5fa9d78fc&scope=profile&state=1b1fd58f11c1aa51c46c1457f9da1b53f61f3ffbe0f0fe567f7159f9c0e52524%3AL2VuLVVTL2ZpcmVmb3gv&action=signin ), SUMO ( https://accounts.firefox.com/oauth/?scope=openid%2Bemail%2Bprofile&state=9BiMVJTZQfWjCrynxcDMGOIWbUMgCsHd&redirect_uri=https%3A%2F%2Fsupport.mozilla.org%2Ffxa%2Fcallback%2F&response_type=code&client_id=30b11ae57025e70b )
  2. Type an email address and click “Continue”
  3. Open the “Privacy Notice” page in the same tab
  4. Try to open any link from that page in the same tab

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Okay, I can reproduce in all environments, including local dev. Have a fix, but will have to ask around as to whether it's the correct fix

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Updating points - thought this would be quick but ended up requiring a lot of spelunking through content-server

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Prod [Train 1.179.0] using Windows 10 64-bit and Android 9. Privacy links are successfully displayed.

![issue3](https://user-images.githubusercontent.com/18114210/87425666-bd760600-c5e6-11ea-83a6-354aad0e37cd.gif)
