### ISSUE TITLE
SurveyGizmo skip header link not working properly

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#5841]
a11y severity: very minor

The SurveyGizmo iframe includes a “skip survey header, go to main survey” skip link and it’s a little awkward for a couple of reasons: when using a screenreader, it doesn’t actually skip to the survey content, and keyboard users need to tab one additional time than you’d think would be necessary to get to the main content.

Let's see if we can improve this functionality or at least verify that the IDs are correct and that it looks like it should work. The solution for this might be submitting an issue to SurveyGizmo or passing this on to [~jgruen@mozilla.com] to just remove the skip link in SurveyGizmo settings if possible because even if it did work, all it does is skip past a single sentence which is the header of the survey. It doesn't really save keyboard users any time by preventing tabbing through anything needlessly (the purpose of skiplinks).

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2225)
┆Issue Number: FXA-2225

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

[~lzugai@mozilla.com] I gave it a try using ChromeVox and was able to tab into the skip link, hit Enter, and then have it take me to the title of the survey. That works as expected IMO. Is that what you meant by "need to tab one additional time than you’d think would be necessary to get to the main content", or are you experiencing something different?

Even if that is expected functionality, I agree that it doesn't really provide much value. If we can turn it off I'd be in favor of that.

**Comment by LZoog** [comment]
By "need to tab one additional time than you’d think would be necessary to get to the main content", I meant for keyboard users and not screenreaders. If you tab into it, it's like "wait what did I just hit" because there's nothing visible you're interacting with and you must tab one more time to reach the survey. This might could be fixed by putting a `-1` tabindex on it, but I'm not sure how customizable that is in SurveyGizmo and we might need to ask John what's possible here. You do see this in the lower left-hand corner though while using a keyboard:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/13018240/86608186-d429b680-bf6f-11ea-9b4b-fac0096b3b7e.png">

Here's what I'm experiencing on FF / MacOS with VO:

![screenreader-survey](https://user-images.githubusercontent.com/13018240/86608831-a98c2d80-bf70-11ea-8fd6-835bd9a1dd19.gif)

When I click on the link, I would expect the next item read to me to be the survey radio buttons and "skip" the header but it doesn't appear to do anything.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Ah okay, fair point, and agree. Unassigning to let [~jgruen@mozilla.com] have a look because I can't reach that code and don't know if it can be disabled.

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

set `display: none;` on `.sg-skipnav-container`
