### ISSUE TITLE
enhance must-reset.js to accept a plain text list of email addresses

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#5894]
When using this script, I typically have a list of email addresses which I have to resolve to associated uid with a database lookup and format into the JSON that this script accepts. It would be better if https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/scripts/must-reset.js could also accept the original list of email addresses, do the lookups, including secondary/primary, and do the reset.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2250)
┆Issue Number: FXA-2250

**Comment by byrw** [comment]
can I work on it?

**Comment by byrw** [comment]
Hey @jrgm, about the tests. When I use `npm run test` and it gets to "Script tests", it just run a couple of tests and then skip the rest of it. Besides that, the test for the scripts seems to be failing. For example, I've had to increase the `setTimeOut` value to make `npm test -- test/scripts/must-reset.js` pass all the tests, otherwise all the tests will fail with timeout. Is this supposed to be happening?

**Comment by jrgm** [comment]
Hrm. I don't actually know much about the tests for must-reset.
