### ISSUE TITLE
“The image file size is too large to be uploaded.” error is displayed under the avatar pictogram

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#5975]
**Notes**
This is a follow-up issue for #5348

**Build**
Stage [Train 1.180.0]

**Affected platforms**
Windows 10 64-bit
Android 9
iOS 13.4.1

**Steps to reproduce**
1. Login using a Firefox account and navigate to the Manage account page.
2. Click "Add" button from the Account picture area.
3. Click Upload button and choose a picture that exceeds the limit size.

**Expected results**
“The image file size is too large to be uploaded.” error is displayed on top of the modal, above the avatar pictogram.

**Actual Results**
The error message is displayed under the avatar pictogram. 

![Screenshot_14](https://user-images.githubusercontent.com/18114210/87805693-6f6b3780-c85e-11ea-8431-79b9a8271b38.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2304)
┆Issue Number: FXA-2304

**Comment by LZoog** [comment]
@pwalm tagging you since you'd provided this text though unrelated to the this incorrect error location issue - I think it could be beneficial to tell the user what the max upload size _is_, if I saw this error message I'd want to know what I'd need to reduce my image file size to in order to upload. 🤔

**Comment by byrw** [comment]
This also happen with the error "A usable image was not found". 
To make the tooltip error appear on top:
On file avatar_change.mustache, move `<div class="error"></div>` to appear before  `<div class="main-avatar">`.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~pwalmsley@mozilla.com] any comment here?

**Comment by LZoog** [comment]
@pwalm we triaged #5976 right after this issue and we think the 1.35mb validation might occur after an image has been _cropped_ in which case an exact mb upload message limit won't make sense to users. @jodyheavener wants to get that issue done this sprint and this issue was added to the following sprint so I'll circle back to you when we know what's going on in #5976.

**Comment by data-sync-user** [comment]
➤ Philip Walmsley commented:

I would change the error string to show whatever the max mb is. So: "The image file size is too large to be uploaded. Please make sure your file size is less than [x]mb."

**Comment by jodyheavener** [comment]
The placement of the error message was addressed in this PR: #6011

To the point about updating the error message, I think we should leave it as is, because (from that PR):

> When you select an image for upload, or take an photo on your device camera, the image may be larger than the maximum-allowable file size set by the server. However, this is not the image being submitted to the server. When you select the image and resize/crop it, it is processed in the client by our cropper and typically always yields a file size much smaller than the original image. It is still possible to generate a file too large to be uploaded, but the likelihood is much less.

Therefore, telling the user to upload a smaller image is not guaranteed to yield a success. Please push back if there are strong opinions about this.
