### ISSUE TITLE
TOTP: the green message is not updated when downloading codes

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla/fxa#599]
Environment:
Stage Train 121, Production
Platform: Android, iOS, Win

Steps to reproduce:
1. Enable Two-step authentication for the account;
2. Tap on "Download" button.

Expected result: the success message gets updated from "Two-step authentication enabled" in "Codes downloaded".

Actual result: the message is not updated. 
Video: https://drive.google.com/open?id=1gvAGwPuI09dtXWlRU9BesQ3MFnxSiNdV

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-738)
┆Issue Number: FXA-738

**Comment by jodyheavener** [comment]
I am unsure if this flow has changed since this issue was initially opened, but clicking the "Download" button in the modal presents a green "Downloaded" banner (see screenshot). That seems suitable at this time.

![Screen Shot 2020-03-24 at 7 17 40 PM](https://user-images.githubusercontent.com/6392049/77485796-792ae400-6e04-11ea-92f1-666d48e12c91.png)
