### ISSUE TITLE
Target consistent node envs in travis across all repos

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa#60]
This came up in a recent Monday meeting - we should formalize the set of node environments we want to support/test on, and ensure that they're configured the same in .travis.yml across all repos.  I vaguely remember settling on the following config:

```
language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
```

@jrgm @dannycoates any objections or counter-proposals?

**Comment by pdehaan** [comment]
Related: https://github.com/mozilla/fxa/issues/41 (which I should really do something about since my dumb face is on the ticket).

Also, we should look at ignoring Node 4.x failures until we are confident that Node 4 works for our projects. Something like this pseudo code from [fxa-auth-db-server](https://github.com/mozilla/fxa-auth-db-server/blob/96ef8cc54dfa44f7ee5e50b15093aaf0403c91fa/.travis.yml#L33-L38):
```yaml
matrix:
  allow_failures:
    - node_js: 4
  fast_finish: true
```

**Comment by jrgm** [comment]
```
node_js:
  - "0.10"
  - "0.12"
  - "4"
```
I'm happy with that. And @pdehaan's suggestion is good, if it just doesn't compile on 4.0, then testing on 2.0 is better than just spinning travis-ci on a some dependency known to fail on 4.0 due to not being updated for NAN 2.0.

**Comment by shane-tomlinson** [comment]
Backlogged until all of our modules compile on node 4

**Comment by rfk** [comment]
> Backlogged until all of our modules compile on node 4

What are the known blockers?

**Comment by jrgm** [comment]
> What are the known blockers?

One is updating  for @dannycoates' scrypt-hash fix.

**Comment by rfk** [comment]
IIUC from a chat with Danny in IRC, scrypt-hash should be ready to go as of its latest release.

**Comment by rfk** [comment]
Which re-reading your comment, is probably what you meant by "@dannycoates' scrypt-hash fix", never mind me...

**Comment by vladikoff** [comment]
Pretty much fixed with the node 4 updates
