### ISSUE TITLE
Add download TOS link to the payment confirmation

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6005]
because we are now using a web-based ToS link in emails, we have to add a PDF to the payment confirmation page:

!image-2020-07-21-22-41-45-130.png|width=486,height=396!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2327)
┆Issue Number: FXA-2327
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/13680/image-2020-07-21-22-41-45-130.png">image-2020-07-21-22-41-45-130.png</a>

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx78.0.2 and Windows 10 (64-bit).

The "Download Terms" link was added to subscription page and confirm payment page.
Postfix screenshots below.

![image](https://user-images.githubusercontent.com/15685960/89005946-535f9f80-d30e-11ea-8a2d-ce1fe3069029.png)
![image](https://user-images.githubusercontent.com/15685960/89007078-b2261880-d310-11ea-9266-4904ad5c3857.png)
