### ISSUE TITLE
Remove stored procedures from mysql

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#6015]
The emerging consensus in #6006 is that we should do away with stored procedures in mysql.

So, let's replace stored procedures with regular queries 🎉

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2335)
┆Issue Number: FXA-2335

**Comment by data-sync-user** [comment]
➤ Benjamin Bangert commented:

Part of the goal in gql-api I discussed with [~dcoates@mozilla.com] was moving the regular queries from gql-api into fxa-shared, so as we move fxa-auth-server db lookups to using queries, the same query/logic would be available to gql-api so that more gql-api results could avoid having to hit fxa-auth-server and do the same query/logic. Good to have an issue to track this! (Will likely be an epic though?)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Mentioning FXA-616 for context, since I just saw that issue again.
