### ISSUE TITLE
3D Secure “Cancel” and “Fail” error messages are confusing

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6114]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.182.0;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an FxA account;

 #### Steps to reproduce:
1. Load https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/vpn page;
2. Click on the “Try Mozilla VPN” button;
3. Sign in with the account from prerequisites;
4. Change the URL by adding a “/v2” value after .net/
5. Fill all mandatory fields and click the “Pay Now” button;
6. Click the “Cancel”/”Fail” options from the 3D Secure popup;

#### Expected result:
- A clear message about your action is displayed.

#### Actual result:
- The “Hmm. There was a problem authorizing your payment. Try again or get in touch with your card issuer.” error message is displayed;

#### Notes:
- An unclear message is also displayed in the payment update page: “Something went wrong. Please try again later.”

![image](https://user-images.githubusercontent.com/15685960/89192509-3ac0e500-d5ad-11ea-8a36-9c151756289d.png)
![image](https://user-images.githubusercontent.com/15685960/89192534-43b1b680-d5ad-11ea-825c-12350b6f1189.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2376)
┆Issue Number: FXA-2376

**Comment by lmorchard** [comment]
Might be a product thing to look into...

If the first message is what happens with Cancel, that makes sense - there was a problem authorizing, but we don't get a specific message that the problem was from the user cancelling.

If the second message is what happens with Fail, that makes sense too - there was a service-level failure with APIs, and we use that same message in general whenever a service fails. Contacting a card issuer wouldn't make sense in this case - it's likely there's a network failure or one of our services is down

**Comment by ValentinaPC** [comment]
Just a clarification: the first message happens for both Cancel and Fail while in the subscription flow. and the second message happens for Cancel and Fail while in the payment update flow.

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

From mtg: [~jgruen@mozilla.com] what are your thoughts here?

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx79 and Windows 10 (64-bit).
Same message is displayed during subscription and payment update, while clicking on "Fail" or "Cancel" 3D secure popup option.
Postfix screenshot below.
![image](https://user-images.githubusercontent.com/15685960/90229868-4b7d2080-de21-11ea-845f-bd2003ec14c7.png)
