### ISSUE TITLE
Subscriptions are no longer possible while reusing an email associated with deleted FxA account with active subscriptions

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#6282]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.185.1;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have an FxA account with at least an active subscription;

 #### Steps to reproduce:
1. Load account settings page https://accounts.stage.mozaws.net/settings (of the account from prerequisites);
2. Go to “Delete account” section;
3. Click on “Delete” red button;
4. Check all boxes, re-enter account pass and click “Delete account” button;
5. Go to Mozilla VPN main page https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/
6. Click on “Try Mozilla VPN” button;
7. Create a new FxA account using the email address from the account deleted at step 4;
8. Finalize account creation;

#### Expected result:
- User is redirected to the subscription page;

#### Actual result:
- A 404 error page is loaded. The message “Problem loading customer. A backend service request failed.” is displayed.

#### Notes:
- Not reproducing for an account without subscriptions.

![image](https://user-images.githubusercontent.com/15685960/91045183-2a85ae00-e61f-11ea-9576-64e86c2301d9.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2471)
┆Issue Number: FXA-2471

**Comment by clouserw** [comment]
@ValentinaPC what is the email address associated with this bug?  Ping me on slack or wclouser@m.c if you'd prefer not to say it here

**Comment by lmorchard** [comment]
This *might* be the result of the customer not getting deleted in Stripe after deleting the FxA account. Or not getting deleted enough. 

We currently use email + UID to fetch customers and cache the data. If the email is used in a new account, the UID will be different - and [we have code that throws an error if a Stripe customer is found for a given email but the UID is a mismatch](https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/lib/payments/stripe.ts#L437).

FWIW, #6158 could end up related to a fix here, since we'd associate the stripe customer with FxA UID directly and no longer involve the email address.

**Comment by jackiemunroe** [comment]
I believe I've been able to locate the account used. It appears as though the customer metadata was successfully updated to flag for deletion, however the account still active within Stripe.

As Les mentioned above, #6158 would resolve the customer create issue. Separately, we would need to evaluate how we handle Customer deletion within Stripe to ensure we properly remove any existing subscriptions, since in this case, the Customer still exists and the associated Subscriptions are still active.

**Comment by jackiemunroe** [comment]
I will note here the reason this is currently done asynchronously:
* When a Customer is deleted in Stripe, we no longer are able to access what their Subscription status was at the time of deletion. To provide an email to the user with the proper termination of Subscriptions information, we have to keep the customer active in Stripe until the email is sent.

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx81 and Windows 10 (64-bit).
A new subscription can be made using a deleted email address while creating your account.
