### ISSUE TITLE
Updating refresh token last used at uses a surprising amount of database CPU

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#6446]
The oauth db is an r5.large currently using between 10-25% CPU over a weekday depending on traffic volume. The main contributor is the query `UPDATE refreshTokens SET lastUsedAt = ? WHERE token = ?`. Right now we update the lastUsedAt column [after 24 hours have passed since the last update](https://github.com/mozilla/fxa/blob/8ddc5515a9f4fbe592f0c0bfde9c4e9809ca772e/packages/fxa-auth-server/config/index.ts#L1092) .

Throwing out some ideas:
* Is this even a problem? The database is easily handling this for now
* Could we try increasing the `updateAfter` delay to 48 hours and see how that affects CPU utilization?
* What UI or APIs use the lastUsedAt column? Could we maybe do something like use the createdAt of the access token paired to the refresh token?
* Could we store lastUsedAt in redis? Could we store the entire refresh token in redis?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2535)
┆Issue Number: FXA-2535

**Comment by rfk** [comment]
> What UI or APIs use the lastUsedAt column?

It powers the "last sync" timestamp for OAuth devices in e.g. the "devices and apps" settings page.

> Could we maybe do something like use the createdAt of the access token paired to the refresh token?

I don't think we track the link from access tokens back to refresh tokens.

> Could we store lastUsedAt in redis?

I think this is worthwhile, and we could also consolidate it with how to track other metadata in redis for sessiontokens. For example, I think we do some geolocation tracking for sessiontokens that is not currently done for refreshtokens.

> Could we store the entire refresh token in redis?

This makes me nervous since in my head redis is for possibly-ephemeral data, and these are not ephemeral.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We discussed this in our triage and didn't see any obvious ways to improve this query.  If this isn't critical on the ops side I suggest we close this issue.  If it is critical, we should put parameters around our goals, eg. what CPU usage should we be aiming for?
