### ISSUE TITLE
Not tracking OS as Android for Fenix activity

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#6515]
We don't seem to be reporting any OS for `fxa - activity` events where `service = fenix`. See here:
[https://analytics.amplitude.com/mozilla-corp/chart/new/lyclkur](https://analytics.amplitude.com/mozilla-corp/chart/new/lyclkur)

Note that we are tracking the OS for individual events like registrations and logins. See here:
[https://analytics.amplitude.com/mozilla-corp/chart/new/nfqxn7z](https://analytics.amplitude.com/mozilla-corp/chart/new/nfqxn7z)

This problem was reported to me indirectly by Karlof who observed that the engagement rate of Android had declined:
[https://analytics.amplitude.com/mozilla-corp/chart/4464ayl](https://analytics.amplitude.com/mozilla-corp/chart/4464ayl)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2563)
┆Issue Number: FXA-2563

**Comment by rfk** [comment]
This seems likely to be due to Fenix using a weird user-agent string of `MozacFetch/X.Y.Z` rather than something that says "android" in it.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Is the bug here that Fenix is using a weird user-agent?  If we should start recording a new user-agent as Android, is there documentation for what the user agent is & will be?

**Comment by rfk** [comment]
Actually, it looks like an upcoming release may revert to using the default browser user-agent string, ref https://github.com/mozilla-mobile/android-components/issues/7719 (so that'll be something like "Mozilla/5.0 (Android 9; Mobile; rv:82.0) Gecko/82.0 Firefox 82.0" we our existing code should know how to handle correctly).

We could also look for any UA strings starting with "MozacFetch" and classify them as android in the meantime, while waiting for that to hit release.
