### ISSUE TITLE
Discuss improving the handling of avatar images that are too large

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#657]
child of https://github.com/mozilla/fxa-content-server/issues/6261

Currently when users upload an avatar image that is too large, >5 MB IIRC, we show this message.
<img width="231" alt="usable" src="https://user-images.githubusercontent.com/68213/29180988-89b04386-7dc7-11e7-9eda-036cc1189ab0.png">
Some of my iPhone SE photos are bigger than this, and most DSLRs would be excluded. Ideally we can bump it up to a much larger number. What other options are there?

**Comment by LZoog** [comment]
@ryanfeeley this issue is pretty old - it looks like at some point we did increase the file upload limit.

I just tried uploading a 200MB image to see what would happen, and I'm not quite sure what happened here...
<img width="437" alt="image" src="https://user-images.githubusercontent.com/13018240/66243535-84f5e300-e6ca-11e9-9332-8a7204909196.png">

I tried this twice with the same result. This might be a separate issue.

I also tried uploading an SVG to see what error it'd spit out, and instead of saying something like "invalid file type", it said my image needed to be at least 100x by 100x in size. What would you say the scope is for this issue - improve file upload error messaging for file type and file size? I can look into the large image upload issue here and create a new issue if it becomes a scope creep.

**Comment by LZoog** [comment]
Also @ryanfeeley, FWIW, when uploading this large image, I noticed we don't have a spinner going to show the user the image is uploading, and you can "clear" an avatar image with one click, without a confirmation check. Might be something worth addressing in the settings redesign.

**Comment by ryanfeeley** [comment]
Nice that this limit was increased at some point. Closing!
