### ISSUE TITLE
Investigate signout issue with proxy / FxA token TTL

### ISSUE THREAD

**Issue by johngruen** [mozilla/fxa#6641]
See https://github.com/mozilla-extensions/secure-proxy/issues/936

We believe this may be caused by a recent change to token TTLs in FxA. Specifically TTL was changed to 12 hours on Sept 22nd, this correlates to a drop in Proxy usage starting on sept 23-24. See bottom chart [here](https://datastudio.google.com/reporting/1vLgXYyi1uhcva4FIbrYq2hmW98z-EISX/page/W63bB)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2606)
┆Issue Number: FXA-2606

**Comment by jbuck** [comment]
I am deploying a change to increase the access token TTL back to 24 hrs. stage will be kept at 12 hrs for debugging purposes

**Comment by jbuck** [comment]
https://github.com/mozilla-services/cloudops-deployment/pull/4057

**Comment by 6a68** [comment]
The goal in lowering the default access token TTL was to improve resolution of sync device counts (#5143), but it didn't seem to fix the underlying bug (see #6578 and #6581).

I'm skeptical about continuing to attempt to lower this TTL, given that it doesn't directly serve FxA's needs for Q4. I'd be in favor of just moving stage back to 24hrs as well.

**Comment by jbuck** [comment]
This change is now running in production

**Comment by rfk** [comment]
@rlr spotted this in a slack conversation, surfacing here for context:

* the guardian website requests an explicit ttl on its access tokens, and [assumes the server will grant it tokens with the requested ttl](https://github.com/mozilla-services/guardian-website/blob/a9a68a542fd36c4b308720bb50bcb9106ac5be17/server/browser/utils.js#L163).
* The config value changes in FxA above is the [*max* ttl](https://github.com/mozilla/fxa/blob/1137d90904b0b1749781692204ed31e16310d147/packages/fxa-auth-server/lib/oauth/routes/token.js#L45) allowed on access tokens, as well as the [default value](https://github.com/mozilla/fxa/blob/1137d90904b0b1749781692204ed31e16310d147/packages/fxa-auth-server/lib/oauth/routes/token.js#L97).
* If a client requests a ttl larger than the max, FxA will [clamp it](https://github.com/mozilla/fxa/blob/1137d90904b0b1749781692204ed31e16310d147/packages/fxa-auth-server/lib/oauth/routes/token.js#L212) to the configured max.

So guardian ends up thinking its profile access tokens are valid for 24 hours, but the config change made then only valid for 12. This results in it failing to update the user's profile info from the server. I don't know what the implications of such failure are for the signed-in state of the user in FPN.

Short-term, [this code](https://github.com/mozilla-services/guardian-website/blob/a9a68a542fd36c4b308720bb50bcb9106ac5be17/server/browser/utils.js#L163) in guardian should use the `expires_in` field returned by the server, rather than assuming it equals the requested ttl.

Longer-term, we need to set better expectations about how RPs should deal with 401s that result from expired tokens. Ideally, if an RP attempts to use its access token and gets a 401, it should try to make a new access token using its refresh token. If the use of the refresh token *also* fails with a 401, then the user has disconnected the RP from their account.

**Comment by rlr** [comment]
On the VPN side of guardian we introspect the saved access token before using them https://github.com/mozilla-services/guardian-website/blob/master/server/lib/utils.ts#L446-L468

```
      // Refresh the access token if necessary.
      const accessTokenInfo = await FXA.introspectToken({
        token: user.fxa_access_token,
        token_type_hint: "access_token",
      });
      if (!accessTokenInfo || !accessTokenInfo.active) {
        // access_token is no good. Try refresh_token to renew.
        try {
          fxaTokens = await FXA.refreshTokens(user);
        } catch (e) {
          // Ref: https://github.com/mozilla/fxa-auth-server/blob/master/fxa-oauth-server/docs/api.md
          const body = typeof e.body === "string" ? JSON.parse(e.body) : e.body;
          if (body && body.code === 400 && body.errno === 108) {
            log.info("refresh-token-revoked", { user_id: user.id });
            await _handleRevokedAccess(user);
            return null;
          }
          throw e;
        }
      }
      const profile: FxaUserProfile = await FXA.getUserProfile(
        fxaTokens.accessToken
      );
```

That has worked out well although it's an extra call. I'll fix the FPN side of guardian.

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

Triage: Jared, can you file any fxa follow-up bugs and close this one?

**Comment by 6a68** [comment]
Filed #6911 to capture the documentation improvement suggestion. Otherwise, think we're good here. Closing.
