### ISSUE TITLE
Add content guidelines for FxA 

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa#67]
Should we include this here somewhere?

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Firefox_Accounts/UX_guidelines

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1218465

**Comment by seanmonstar** [comment]
Whats the ask here?

**Comment by rfk** [comment]
A more specific ask, from [1]:

"""
do you think that MDN is the right place for this? Since the target audience is probably the future and current FxA developers, I wonder if we should put this in https://github.com/mozilla/fxa. MDN is a little more externally facing.
"""

FWIW similar could be said about much of the other FxA stuff that's currently in MDN.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1218465#c2

**Comment by ckarlof** [comment]
I originally put the "other FxA stuff" in MDN. The motivation was to try to find a place where people would instinctively look for integration docs on FxA. I would say the results have mixed, and if we feel it's more valuable to move them to the fxa repo or rtd.org, that would be fine with that.
