### ISSUE TITLE
Trying to login on AMO with disabled 2FA ends up endless redirect loop

### ISSUE THREAD

**Issue by wagnerand** [mozilla/fxa#6762]
## Description

Trying to login on AMO with a mozilla.com account that had 2FA enabled previously but has it disabled now makes me stuck in an endless FxA redirect loop.

### Steps to reproduce

1. Have an account with a mozilla.com email.
2. Enable 2FA.
3. Login on addons.mozilla.org and make sure login worked currently. Then logout.
4. Disable 2FA.
5. Try to login on addons.mozilla.org again.

### Expected result

A prompt to enable 2FA.

### Actual result

Endless redirect loop.

### Environment

Firefox 83.0b4 on macOS 10.15.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2644)
┆Issue Number: FXA-2644

**Comment by diox** [comment]
> 1. Have an account with a mozilla.com email.

Step 1a. Give this account permissions or make it a developer account on AMO (submit an add-on with it) - otherwise AMO won't enforce 2FA.

**Comment by diox** [comment]
FWIW I've enabled 2FA enforcement for mozilla.com accounts on AMO dev (which uses FxA stage), https://addons-dev.allizom.org/ and reproduced the problem there.

**Comment by rbillings** [comment]
@vasilicatamas would you please try to repro this?

**Comment by vasilicatamas** [comment]
I was unable to reproduce this issue either on dev or production.
- On dev - the account was successfully logged to amo but the “Enable two-step authentication” was not displayed
- On production - the user was successfully logged to amo and the “Enable two step authentication” screen was displayed after a loading wheel appeared for a few seconds

**Comment by diox** [comment]
Add-ons QA and several add-ons team members have reproduced this using the STR above on both dev and production.

Could you share which accounts you used on each env ?

**Comment by vasilicatamas** [comment]
Tested again on amo-dev server and I constantly reproduce this issue following these steps:
1. Open a Firefox profile and navigate https://addons-dev.allizom.org/
2. Login using an account that has already submitted an add-on.
3. Enable the 2FA when the screen appears.
4. Logout from https://addons-dev.allizom.org/
5. Open a new tab and navigate to https://accounts.stage.mozaws.net 
6. Login using the account used at step 2.
7. Disable the 2FA - DO NOT LOGOUT.
8. Navigate to https://addons-dev.allizom.org/ and try to login.

- This issue is reproducible only when the user doesn’t signout from the FxA settings page at step 7.

![issue29](https://user-images.githubusercontent.com/18114210/97883543-a8f08180-1d2d-11eb-8aa1-657bbb4fe7c1.gif)

**Comment by muffinresearch** [comment]
@6a68 would you be able to give us an idea of when this might be fixed?

**Comment by 6a68** [comment]
@muffinresearch Hi, sadly I'm not sure. I'm hoping to get to this today or early next week, but I haven't yet had a chance to investigate. I'll keep you updated as I make progress.

**Comment by 6a68** [comment]
@vasilicatamas Hi, in your STR you mentioned users must not logout. Are you able to reproduce this issue if the user logs out and back in?

**Comment by 6a68** [comment]
One error I've spotted here is due to the `POST v1/oauth/authorization` endpoint not verifying that the requested acr value matches what's on the account. I don't know that this would explain the STR requiring the user to not log out after enabling, then disabling 2FA.

**Comment by muffinresearch** [comment]
> @muffinresearch Hi, sadly I'm not sure. I'm hoping to get to this today or early next week, but I haven't yet had a chance to investigate. I'll keep you updated as I make progress.

Thanks, it sounds like you're making some progress, I understand that you might not be able to give us a definitive idea of when this might be resolved, but afaik this is the only blocker to us being able to enable 2fa for developers. It would be really great if this can be unblocked sometime between now and EOY so that we can enable it early next year. Does that sound doable?

**Comment by 6a68** [comment]
@muffinresearch Hi! Yes, I wanted to be fairly sure I had a fix before getting back to you :-P

I am working on this issue in the current sprint and the fix will be deployed to staging when the sprint closes on 16 December. (We aren't planning to do another production release before EOY, but you should be able to verify the fix on staging).

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Pulling into the sprint. A fix is under review: https://github.com/mozilla/fxa/pull/7111

**Comment by diox** [comment]
@vasilicatamas was this retested by you or your team when the fix landed on FxA Stage ?

**Comment by vasilicatamas** [comment]
@diox The fix landed only today and the bug is on my to do list. I will post the results as soon as I will get it verified.

**Comment by ioanarusiczki** [comment]
@vasilicatamas Hello Ica, @diox asked me to do a quick check so I tested the steps you added [above](https://github.com/mozilla/fxa/issues/6762#issuecomment-720529247) on AMO dev with FF84(Win10) and I could not reproduce the issue. 
At the final step I am redirected again to enable 2FA again, which I was able to do and then I've been redirected back to AMO dev.

**Comment by ioanarusiczki** [comment]
As a double -check: 
The issue is reproducible with AMO stage - fxA prod env. but no longer reproducible on AMO dev - fxA stage. 
I'm marking it verified.
