### ISSUE TITLE
[FxA-Settings] Multiple secondary emails cannot be added

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6793]
**Build**
Stage [Train 1.192.0]

**Affected platforms**
Windows 10 64-bit
Android 9
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Add a secondary email.
3. Try to add a second one.

**Expected results**
“Add” button is displayed and multiple secondary emails are successfully added.

**Actual Results**
“Add” button is no longer displayed after adding the first secondary email and therefore there is no way to add more secondary emails from the same profile. 

![Screenshot_22](https://user-images.githubusercontent.com/18114210/97595890-d4f9c300-1a0c-11eb-8023-0f1dfbf54f5f.png)
![Screenshot_23](https://user-images.githubusercontent.com/18114210/97595894-d75c1d00-1a0c-11eb-8a9c-22cb94598582.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2658)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15128/Screen+Shot+2021-02-08+at+4.33.11+PM.png">Screen Shot 2021-02-08 at 4.33.11 PM.png</a>
┆Issue Number: FXA-2658

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

I don't see where the 'Add' button would go in the designs. I guess near the bottom of the list? [~pwalmsley@mozilla.com]

**Comment by jodyheavener** [comment]
We decided to forgo adding additional secondary emails at this stage (but should still support managing any currently-added multiple secondary emails). IIRC this was decided with Janice because we were already mid-design when multiple secondary email functionality was added to the current Settings and wanted to allow for a more thorough review of how it should look.

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

ima move this to v2

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Removed from V2 per [~adavis@mozilla.com] .

Product decided to remove from v2 Settings requirements due to less than 4% of firefox accounts usershaving 2+ emails. As this feature is not often utilized, and as this was not included in the UX for Settings Redesign, this work is not prioritized for engineering.

Current counts of number of emails per user below (per [~jbuckley@mozilla.com]): 

MySQL [fxa]> select c as number_of_emails, count(*) from (select hex(uid) as uid, count(*) as c from emails e group by 1) as d group by 1;
 -----------------------------+

numberofemailscount(*)+-------------------+----------+
11274487472204050632238841990+-------------------+----------+
4 rows in set (26 min 18.83 sec)

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

[~vtamas@mozilla.com] please note that adding multiple secondary emails is explicitly not in scope per Product in new settings. If a user has multiple secondary emails (as ~24,000 users do), they will be able to see and manage their third, fourth emails, etc,. but will not be able to add more than one primary and one secondary email. See screenshot attached to ticket for an example of what this looks like when multiple secondary emails exist. //cc: [~rbillings@mozilla.com]
