### ISSUE TITLE
[fxa-event-broker] Dispatch events to relier webhooks

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#686]
* Blocked by #683.
* Blocked by #684.

**Comment by shane-tomlinson** [comment]
I came across this IETF spec over the weekend for [Security Event Tokens](https://tools.ietf.org/html/rfc8417). The spec is fairly minimal as far as specs go, but does go into some detail on message format (JWT), with a minimum standardized set of claims, and nomenclature for a common set of event names from the [IETF System for Cross Domain Identity Management spec](https://tools.ietf.org/html/rfc7644) and [OIDC's RISC event types spec](https://openid.net/specs/openid-risc-event-types-1_0.html).

@philbooth and I had a brief chat in IRC where he mentioned sending messages with an HMAC over a few of the fields because there may be some fields we don't send to all RPs. The vision is that the event broker is a somewhat dumb pipe that takes a message in and forwards it on to RPs. This could be considered somewhat at odds with the spec because implementing the spec would require processing on the broker to create per-RP JWTs. I can see the spec and this vision working together because we already have to do some filtering on a per RP basis.

The broker could accept a message that contains all the claims. It then repackages the info on an RP by RP basis, creating a JWT for each RP containing only the claims necessary for that RP. The JWT is signed in its entirety providing full message integrity rather than only over a subset of the fields.

**Comment by bbangert** [comment]
Deprecated for #1269.
