### ISSUE TITLE
[FxA-Settings] Incomplete text displayed in 2FA Step 1 of 3 screen

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6888]
**Build**
Stage [Train 1.193.0]

**Affected platforms**
Windows 10 x64
Android 9
iOS 13.6 

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Add" button from "Two-step authentication" area.
3. Check the first phrase.

**Expected results**
“Scan this QR code using one of these authentication apps.” text is successfully displayed - see [figma](https://www.figma.com/file/Nj2WjMOXoJBiPoWvyJ946X/FxA---Manage-Settings-(Copy)?node-id=0%3A792)

**Actual Results**
“authentication” word is omitted from the text.

![Screenshot_42](https://user-images.githubusercontent.com/18114210/98705724-ad004d00-2386-11eb-82d7-4e3910dc752f.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2689)
┆Issue Number: FXA-2689

**Comment by vasilicatamas** [comment]
This issue was verified as fixed on Stage [Train 1.194.0] under Windows 10 64-bit, Android 9 and iOS 13.6. The "authentication" word is successfully displayed.

![Screenshot_10](https://user-images.githubusercontent.com/18114210/99994323-82b88180-2dc1-11eb-92c5-db7ec7c741b7.png)

**Comment by navap** [comment]
I'm on Windows v89.0.2 and I see a para symbol in this text. Not sure if it's related, but this issue was the only google result for this particular string.
![image](https://user-images.githubusercontent.com/54449/124302999-e6611500-db2f-11eb-9d8a-8cea1381cf0b.png)

This is from https://accounts.firefox.com/settings/two_step_authentication.
