### ISSUE TITLE
[FxA-Settings] “Can’t scan code” link is not displayed in 2FA Step 1 of 3 screen

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6890]
**Build**
Stage [Train 1.193.0]

**Affected platforms**
Windows 10 x64
Android 9
iOS 13.6 

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Click on the "Add" button from "Two-step authentication" area.
3. Check the page elements.

**Expected results**
“Can’t scan code?” link is successfully displayed. (it is not specified in figma mockups but this can be a really blocker for mobile users.)

**Actual Results**
“Can’t scan code?” link is not displayed - this can be a really blocker for mobile users.
![Screenshot_41](https://user-images.githubusercontent.com/18114210/98711192-5d714f80-238d-11eb-9796-5f107ffcdb4b.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2691)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/14600/cantscan.png">cantscan.png</a> | <a href="https://jira.mozilla.com/secure/attachment/14601/cantscan-step2.png">cantscan-step2.png</a> | <a href="https://jira.mozilla.com/secure/attachment/14602/Screen+Shot+2020-11-13+at+9.28.16+AM.png">Screen Shot 2020-11-13 at 9.28.16 AM.png</a>
┆Issue Number: FXA-2691

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

This wasn't included in the figma mockup

!cantscan.png!

This is what it looks like in after clicking in the current settings page.  !cantscan-step2.png!

We will need some product work to determine where we want to display this, as we don't want a modal on top of a modal. Im guessing we will need to add another "step" inside of the current modal which will show something similar. Additionally, we will need to make sure we can generate that code and have this functionality hooked up and working correctly, so this is a more involved fix than just adding the link.

**Comment by data-sync-user** [comment]
➤ Dave Justice commented:

Assigned to [~pwalmsley@mozilla.com] for some guidance on how we want to handle this. 

cc/ [~jhirsch@mozilla.com] I believe you worked on the two step auth flow. Do you know if we have the ability to generate this code?

We can probably move this into v2, should not hold up v1 launch.

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

[~djustice@mozilla.com] Yeah, I ran into this issue in the inline 2FA setup flow, since we were in a modal and couldn't render another modal on top of it. The answer we came up with there was to flip to a second screen in the same modal. See the screenshots here: https://github.com/mozilla/fxa/issues/5089#issuecomment-619297409 ( https://github.com/mozilla/fxa/issues/5089#issuecomment-619297409 )

The auth-server generates all the TOTP stuff at once, so you can get the secret and the image by calling the auth-client `createTotpClient` method, and it looks like this method is already proxied by graphql. I think this should be pretty straightforward.

Definitely let me know if you have any other questions 👍

**Comment by data-sync-user** [comment]
➤ Philip Walmsley commented:

Added a link for "Can't scan code?" under the QR code. Screenshot attached.

**Comment by vasilicatamas** [comment]
This issue was verified as fixed on Stage [Train 1.194.0] under Windows 10 54-bit, Android 9 and iOS 13.6. "Can't scan code" option is successfully displayed.
![Screenshot_13](https://user-images.githubusercontent.com/18114210/99996499-84d00f80-2dc4-11eb-8164-749c6061bda8.png)
