### ISSUE TITLE
[FxA-Settings] Connected Services missing icon

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#6975]
## Description
No icon next my instance of Firefox.

![Screenshot_2020-11-19 Firefox Accounts(1)](https://user-images.githubusercontent.com/6219141/99707263-33ddb580-2a6a-11eb-89ad-d514ba045a27.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2843)
┆Issue Number: FXA-2843

**Comment by jodyheavener** [comment]
No icons show up for me: 

<img width="500" alt="Screen Shot 2020-12-10 at 6 40 27 PM" src="https://user-images.githubusercontent.com/6392049/101843328-f70c5800-3b17-11eb-8740-5cefc2236597.png">

**Comment by meandavejustice** [comment]
Found a fix for this

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on FxA Stage [Train 1.197.0] under Windows 10 64-bit, Android 11 and iOS 13.6. Connected services icons are successfully displayed in the new Settings page.

![Screenshot_21](https://user-images.githubusercontent.com/18114210/103885808-3dd67900-50e9-11eb-95d8-3ae1a5f404e6.png)
