### ISSUE TITLE
[FxA-Settings] Help icon does not have hover effect

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7006]
**Build**
Prod [Train 1.194.0]

**Affected platforms**
Windows 10 x64

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Hover using the mouse cursor over the "?" icon displayed in the header.

**Expected results**
The “Help” icon successfully displayed a hover effect.

**Actual Results**
“Help” icon does not have a hover effect.

![issue49](https://user-images.githubusercontent.com/18114210/100236587-891c3a00-2f36-11eb-9676-1e5236ad9901.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2735)
┆Issue Number: FXA-2735

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~pwalmsley@mozilla.com] Is this correct with no hover effect or should it have one?  If it should have one, what should it be?  Thanks

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Lets use the same gray as the bento menu uses

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage [Train 1.200.0] under Windows 10 64-bit, macOS 10.14.6, Android 9 and iOS 13.6. Confirm that "Help" icon successfully displays a hover effect, (During this testing an issue was encountered on mobile devices and filed a separate bug for it FXA-3048)
