### ISSUE TITLE
[Epic] Implement FxA Event Broker

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#701]
This is **2.5.1 FxA Event Distribution Service** in the spec, a small stand-alone service that is configured to listen to an SQS queue that FxA Auth Server’s Account Notification SNS publishes to.

Development Plan: https://docs.google.com/document/d/1W_BFB7N5eq-HSpUmF60BCkEo0nYDAipVf5uvv3s5Htc/edit#

Requirement Sign-Offs
- [ ] I 1.2 FxA should let services know if a user is subscribed

**Comment by philbooth** [comment]
Issues: https://github.com/mozilla/fxa/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%5Bfxa-event-broker%5D

I mentioned this to @bbangert already in Slack, but I'm proposing we call this fxa-event-broker, just because it's less to type in all the places (directory names, dependencies, commit messages, issues). Mentioning in case we want to rename the epic for consistency, @clouserw.
