### ISSUE TITLE
[Support] Handle authentication failures cases

### ISSUE THREAD

**Issue by ianb** [mozilla/fxa#703]
We should ensure that some authentication failures are comprehensible by the support staff:

- [ ] Not logged in (including in the iframe context)
- [ ] Not on VPN
- [ ] Not in correct group

The first one should either do a login in the iframe, or if that is not possible (I'm not sure how navigable the iframe will be) then it should include instructions or a link (`target=_blank`) to help facilitate the login.

The second two are hard failures, but we can include some instructions.

**Comment by bbangert** [comment]
@ianb I'm not under the impression we have programmatic control over this in support-panel. The VPN doesn't give us a way to show an error page, and since the auth will be done in nginx, we're at the mercy of its '401 Auth Denied' page.

Or was this meant to track some sort of handling in Zendesk of the iframe not loading right?

**Comment by clouserw** [comment]
We won't do this for an MVP
