### ISSUE TITLE
Replace "Newsletters" text with "Email Communications"

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7205]
In the Settings Beta menu we use the word "Newsletters" -- we'd like to change this back to "Email Communications" to be more technically correct: the best kind of correct.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2868)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15012/Mozilla+Mail+-+Firefox+Accounts+Settings+-+Newsletters+Question.pdf">Mozilla Mail - Firefox Accounts Settings - Newsletters Question.pdf</a> | <a href="https://jira.mozilla.com/secure/attachment/15011/Mozilla+Mail+-+Firefox+Accounts+Settings+-+Newsletters+Question+1.pdf">Mozilla Mail - Firefox Accounts Settings - Newsletters Question 1.pdf</a>
┆Issue Number: FXA-2868

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

Attached two PDFs with confirmations from Marketing of Email Communications needs, including some inspect elements with the new text 😮

**Comment by vasilicatamas** [comment]
This issue is verified as fixed on Stage [Train 1.197.1] under Windows 10 64-bit, Android 11 and iOS 13.6. "Email Communications" is successfully displayed instead of "Newsletters" in navigation menu.

![Screenshot_29](https://user-images.githubusercontent.com/18114210/104039539-2f6a8900-51df-11eb-81ce-7efcdb990ee2.png)
