### ISSUE TITLE
[prod] No billing details in Subscriptions page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#7222]
#### Affected versions:
- All Firefox;

#### Affected FxA prod version:
- 1.195.4;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- Have a FxA account with active subscription and be logged in;

#### Steps to reproduce:
1. Load Subscriptions page: https://subscriptions.firefox.com/subscriptions 
3. Observe “Billing information” section;

#### Expected result:
- Card ending digits and expiration date are listed.

#### Actual result:
- Billing information is not displayed.

#### Notes:
- Not reproducing on stage.
![image](https://user-images.githubusercontent.com/15685960/103874687-29d74b00-50da-11eb-818b-f46d6cc91868.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2874)
┆Issue Number: FXA-2874

**Comment by chrismore** [comment]
I have tested this with my Mozilla VPN production subscription and I am able to see the last 4 of the credit card and the expiration date. I am not able to replicate it as the screen is not blank.

I believe this is the case, because the account you are using is a trial account I created that doesn't have a credit card associated.

**Comment by ValentinaPC** [comment]
Verified this and the case is exactly like @chrismore mentioned above.
Based on this and the fact that this could not happen for real users, we can close this.
