### ISSUE TITLE
[FxA-Settings] “Delete account” button from Step 2 Delete account page enabling issue

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7419]
**Build**
Stage [Train 1.199.0]

**Affected platforms**
Windows 10 x64
Android 11
iOS 13.6

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Scroll down at the bottom of the page.
3. Click on the "Delete account" button.
4. Check all 4 available options and click on the "Continue" button.
5. Type a password shorter than 8 chars and check the "Delete account" button.

**Expected results**
"Delete account" button is disabled and becomes enabled only for a password composed from at least 8 chars. (same as the “Continue” button from the Recovery key Step 1 of 2 screen)

**Actual Results**
“Delete account” button becomes enabled after typing 1 character.

![Screenshot_26](https://user-images.githubusercontent.com/18114210/106774629-ff31d100-664a-11eb-8241-1195ec9c15a0.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2975)
┆Issue Number: FXA-2975

**Comment by LZoog** [comment]
We should leave the button disabled until the password is at least 8 characters long.

The URL is `/settings` and not `/beta/settings`; click on "Delete account" at the bottom to reach this. It would be nice if a test could be written for this issue too.

**Comment by Jane-Kotovich** [comment]
@LZoog hmm I think I would looove to work on this if this possible. This one would be some form validation, isn't it? Thanks

**Comment by LZoog** [comment]
Hey @Jane-Kotovich, since we're trying to spread out these good first issues, I can assign you once you've got a PR up for #7676 (it's OK if it's not merged yet)! Otherwise, I'll leave it unassigned for now.

For this issue though, I'd recommend checking what we're doing for the password input in other flows. In the recovery key flow for example, the "Continue" button remains disabled until we're at 8 characters:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/13018240/113790882-012a1600-9708-11eb-8b56-931c82b5441b.png">

**Comment by Jane-Kotovich** [comment]
@LZoog Thanks for that, I honestly already started working on this one due to @jodyheavener msg - he mentioned regarding #7676  "this might be a localization issue (the english locale), which I don't think we handle on our end".  
While waiting the answer I didn't want stay without any jobs so decided to work on couple of issues which I knew how to resolve. Hope it's not too much!

**Comment by Yogita98** [comment]
Hey @LZoog since I'm not having anything assigned on me, can I pick this up?

**Comment by Yogita98** [comment]
Hey @LZoog 
Since you mentioned above that you want a test to be written for this fix, I wanted to confirm if [this](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/delete_account.js)  is the right place to add the test for the same?

**Comment by Cronus1007** [comment]
Hey @Yogita98 Yes you are referring to the correct file.

**Comment by Yogita98** [comment]
Alright, thanks @Cronus1007

**Comment by Yogita98** [comment]
@LZoog I'm quite confused what exactly do we need to test?
Do we need to check if the password typed is 8 characters long or we need to test if the continue button is getting enabled after the password is that long? Because I guess I checked the test for `recovery key` section and couldn't find any similar tests there 😅

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue was verified as fixed on Stage  [Train 1.205.0] under Windows 10 64-bit and Android 9. I confirm that the "Continue" button remains disabled until  the field contains at least 8 characters.
