### ISSUE TITLE
UnitRowWithAvatar should use UnitRow

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/fxa#7626]
Right now, UnitRowWithAvatar duplicates the basic layout of the UnitRow, but to match the other rows, it should be rendered by passing specific props to UnitRow.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3091)
┆Issue Number: FXA-3091

**Comment by LZoog** [comment]
For context, I originally created a separate component because I didn't want _too_ many conditionals in `UnitRow` that would make it confusing and thought it was better to separate it at the time since it displayed an image which was different than other rows and wasn't sure how many additional conditionals we'd need by the time the Settings Redesign project finished. If it doesn't make `UnitRow` much hairier, SGTM.

**Comment by flozender** [comment]
Can I please take this up? Thanks!

**Comment by LZoog** [comment]
@flozender since both of your issues have a PR open now, I'll assign this one to you. Thanks!
