### ISSUE TITLE
[FXA-Settings] Menu Category in active state needs background

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#7757]
## Description

When menu category is active, blue category text should have grayscale background. Currently missing.

### Steps to reproduce

<img width="200" alt="Untitled 5" src="https://user-images.githubusercontent.com/6219141/110507292-ded3b700-80cd-11eb-97b7-775d95299cac.png">

### Expected result
 
<img width="186" alt="Untitled 4" src="https://user-images.githubusercontent.com/6219141/110507411-ff037600-80cd-11eb-97b1-3df81c7b5991.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3156)
┆Issue Number: FXA-3156

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This is a good first issue, but we need to specify the color/padding.  It should be in the spec.

**Comment by LZoog** [comment]
The padding is 4px tall by 8px wide and the BG color is #F0F0F4. We should use whatever color is closest that's included in our Tailwind config file and use those generated classes for both the BG color and padding.

**Comment by karinabk** [comment]
I am an Outreachy applicant. Would be happy to fix this ;) @LZoog

**Comment by LZoog** [comment]
Thanks @karinabk, I'll assign this to you! 🙂

**Comment by karinabk** [comment]
@janiceahn @LZoog Do you know how I can render this component? or I need to be registered in the database to get to this page? So far I am on the login page
![Screenshot from 2021-03-30 23-42-17](https://user-images.githubusercontent.com/35498147/113089229-0c151000-9209-11eb-80cf-ed481b12a8e7.png)

**Comment by karinabk** [comment]
I managed to create a user and login to Firefox Accounts.

1. When I followed [README](https://github.com/mozilla/fxa/tree/main/packages/fxa-auth-server), it leads to the script `start-mysql`, but I suspect that this part of the readme is deprecated and this script doesn't exist. 
2. Actually while trying to create a fake account for testing purposes, I came across useful scripts that I can use to generate the user (`dump-users.js` specifically). I couldn't find anything related to the scripts on the README page, therefore I started experimenting in order to make everything work. But unfortunately, they cannot be run using the `node` command, and I have fixed this problem by setting the `NODE_ENV=env` (think this is straightforward) and following the solution proposed by @jodyheavener in the old [issue #5261](https://github.com/mozilla/fxa/issues/5261) and run it using `ts-node`.
3. At this stage I could not login since I could not send a verification code to my email (I suppose this is not possible in the development mode). I modified `db.js` file and set all users to be "isValidated = True" as a temporary solution and run the `dump-users.js` again. Finally, I could enter the Firefox Accounts page!

Based on this long and unobvious way to reach this point, I propose the following things:
1. Maybe we should add a readme explaining what each script does and how to use them (If they exist, I could find them)? Especially mentioning that we should use not `node` to run them, but `ts-node`. 
2. Maybe we should add a way how we can visually test our changes in the docs so that it will clarify how we can inject the user to the local database and test it out. 

Since I'm a new developer for this project, I might miss the easier way to solve this issue.

**Comment by jodyheavener** [comment]
Just popping in here.

> Is there any way that I can render this component separately?

Sure can! If you cd into the fxa-settings package and run `yarn storybook` a browser window will open up and you can preview most of the components. It will live update as you make changes as well.

> When I followed README, it leads to the script start-mysql

Yeah, I agree that this looks out of date. With the vast amount of documentation we have across the repo it's easy for things to fall behind. Issues or Pull Requests are always welcomed for these cases.

> At this stage I could not login since I could not send a verification code to my email

Clever solution you found! There are some other ways to do this:

1. Set up [MailDev](https://github.com/mozilla/fxa#running-with-maildev) so that you can receive emails locally
2. [My preferred approach] With the `inbox` PM2 process running, run the command `./pm2 logs inbox` and then when you submit the signup page the verification code should print out to your terminal window.

> Maybe we should add a readme explaining what each script does and how to use them

I love this idea, documentation is always great to have. We do actually have [little](https://github.com/mozilla/fxa#documentation-for-scripts) [bits](https://github.com/mozilla/fxa/tree/main/packages/fxa-auth-server#email-config) of script-specific documentation scattered around, but a central place for everything could be a good idea.

**Comment by karinabk** [comment]
@LZoog Could you please review my PR?

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

This issue is verified as fixed on Stage  [Train 1.204.3] under Windows 10 64-bit, Android 9 and iOS 14.4. I confirm that the blue category text has a grayscale background.
