### ISSUE TITLE
latest server test failures, #get /__version__, #get /ver.json

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#783]
<img width="889" alt="Screenshot 2019-04-09 at 18 23 36" src="https://user-images.githubusercontent.com/848085/55821147-ad729b00-5af4-11e9-888d-dadb3e12534e.png">

```
AssertionError: expected [ Array(4) ] to deeply equal [ Array(5) ] [ "commit", "version", "l10n", E "tosPp", "source" ] at <tests/server/ver.json.js:25:16>
```

**Comment by philbooth** [comment]
Fwiw, I also see this when I run them locally (so I don't even get to see the #787 failure yet).

**Comment by philbooth** [comment]
So the `getTosPpVersion` function that fetches this value reads it from properties in `node_modules/legal-docs/package.json`. First it looks for the `gitHead` property and then it looks for the `_resolved` proprety.

In my local repo at least, `gitHead` is missing and `_resolved` is the empty string.

First thing that occurs to me is whether the fact that we now have a top-level `package-lock.json` instead of a top-level `npm-shrinkwrap.json` has affected what these properties look like. I confess I'm not sufficiently familiar with the depths of npm to know whether that's likely or what the differences should be.

**Comment by philbooth** [comment]
There is a git hash available for `legal-docs` in the content server's `npm-shrinkwrap.json`. Would it be acceptable to rewrite `getTosPpVersion` so it uses that instead? In lieu of any better suggestions, that's what I'll probably do...

**Comment by philbooth** [comment]
> Would it be acceptable to rewrite `getTosPpVersion` so it uses that instead? In lieu of any better suggestions, that's what I'll probably do...

Correction, I'm adding it as a fallback condition rather than rewriting...
