### ISSUE TITLE
Add a sequence identifier to notification events

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#826]
Coming out of the RRA for the event broker was a concern that relying services had no way of knowing whether they'd missed any events. This could be addressed by maintaining a per-user notification sequence number, stored in either Redis or MySQL. (it needs to be per-user because services would only receive events for subscribed uids)

**Comment by bbangert** [comment]
Since these messages are going in/out of queues multiple times which are *at least once* delivery, I can't see any sane way to number them such that a receiver could verify it hadn't missed one. We are quite likely to deliver repeats, and in the event a message somehow gets lost we should have other systems toe reconcile differences occasionally in addition to the self-healing approach that when a user logs into an RP, the RP does a refresh of the users subscription status.
