### ISSUE TITLE
Storybook for `fxa-settings` is totally broken, 'test' is undefined in storybooks.js

### ISSUE THREAD

**Issue by LZoog** [mozilla/fxa#8391]
## Description

Check out the latest push from `main` (https://storage.googleapis.com/mozilla-storybooks-fxa/commits/28cdc9ce5531407218350523fc10456c65378068/fxa-settings/index.html?path=/story/* at the time of writing).

Try running `yarn storybook` in `fxa-settings` from latest `main`:

![image](https://user-images.githubusercontent.com/13018240/116132105-c4ac6300-a692-11eb-87e1-90b5fb1983a6.png)

Seems to work fine in at least `fxa-react`.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3419)
┆Issue Number: FXA-3419

**Comment by lmorchard** [comment]
Last time this happened, it was because of a Storybook v6 upgrade per dependabot. These custom configs are not ready for v6. Looks like that's the culprit again:

https://github.com/mozilla/fxa/commit/72ac7648b28e16ebc79189f34d762426d7f547d1

**Comment by lmorchard** [comment]
I *thought* I'd told dependabot to hold back that particular package from upgrades, but maybe I didn't? We probably want to do that along with reverting the upgrade

**Comment by lmorchard** [comment]
Oh, I see: This wasn't an upgrade to @storybook/react, this was an upgrade to @storybook/addons.

I guess the basic thing is that until #7995 is closed, any storybook-related dependabot upgrades need to be skipped. That, or manually verified by looking at storybook because errors there don't cause CI failures. I think we might have made that partly intentional because storybook is less-essential than the rest of the test suite
