### ISSUE TITLE
Audit domains that we're using in emails and ensure they are all consistent

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#8574]
Some of our emails send links or include images from multiple domains.  That will increase our spam score which will lower our deliverability.  All images (and preferably links) should go to the same domains.  Lets audit the emails and double check!

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3490)
┆Issue Number: FXA-3490

**Comment by clouserw** [comment]
@Yogita98

**Comment by Yogita98** [comment]
Thanks for the mention @clouserw. I'll update with a PR soon!

**Comment by Yogita98** [comment]
I audited a few emails and observed that in `fxa.html` layout, the logo image is coming from a hosted library as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/37609519/118398446-50078b80-b676-11eb-9159-df2451161f46.png)

Whereas, the logo in the `subscription.html` layout is coming from a cdn link as shown:
![image](https://user-images.githubusercontent.com/37609519/118398465-70cfe100-b676-11eb-9f96-46356039acb2.png)

And both the images are different since the one coming from cdn link also contains text. As per Vijay's [comment](https://github.com/mozilla/fxa/issues/7971#issuecomment-837162739), we want to keep images hosted at the cdn server, but I cannot access that link in order to change the img src URL. So can you please share with me the URL to the exact image we want to show in the `fxa.html` layout?
