### ISSUE TITLE
/recovery_email/status is fetched 5 times when loading /settings

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#862]
<img width="890" alt="Screenshot 2019-04-17 at 15 19 21" src="https://user-images.githubusercontent.com/848085/56295198-4ec8a500-6124-11e9-9d84-6c71b29ca104.png">

That surely must slow down the page load time.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-813)
┆Issue Number: FXA-813

**Comment by vbudhram** [comment]
I believe this is caused by our current panel gating [logic](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/views/mixins/upgrade-session-mixin.js#L114). It attempts to fetch the session status to see if a user needs to `Upgrade session` or if it can render the regular panel.
