### ISSUE TITLE
Ensure auth-errors.js in content server is in synch with auth server

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#885]
@shane-tomlinson [notes](https://github.com/mozilla/fxa/pull/819#discussion_r276167889):

>  It looks like there are a lot of errors that need to be added

In a nutshell, [there are errors defined in the auth-server](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/error.js).

There is [a corresponding list of those errors in the content server](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/app/scripts/lib/auth-errors.js#L239). 

These two lists should be in synch. The content server list seems to be missing some things and we should fix it.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-816)
┆Issue Number: FXA-816

**Comment by shane-tomlinson** [comment]
Yeah, I wonder if we can generate these from a central list. Or just have a central list that contains all the stuff we need.

**Comment by smishra2903** [comment]
Hello, if no one is working on this issue, can I work on this?

**Comment by vladikoff** [comment]
@smishra2903 Yeap!

**Comment by LZoog** [comment]
The profile server also has its own list of errors and error codes. We also have errors sprinkled around `fxa-settings`.

It could be ideal to have a shared error list in `fxa-shared`. I'm going to take off the "good first issue" label because this will touch a lot of files and several packages, but @smishra2903, if you're still interested in taking a stab here, please feel free. Thank you! :)
