### ISSUE TITLE
content-server Loading "remarkable.coffee" tasks...ERROR

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9090]
The following error occurs when building the content server. Is it possible to ignore it? Everything seems to work.

Loading "remarkable.coffee" tasks...ERROR
Error: Grunt attempted to load a .coffee file but CoffeeScript was not installed.
Please run `npm install --dev coffeescript` to enable loading CoffeeScript.

thanks...

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2960)

**Comment by pdehaan** [comment]
I was going to report the same thing.
Looks like running <kbd>yarn add coffeescript</kbd> fixed the error.

Not sure _why_, since https://github.com/rwky/grunt-remarkable includes both a .coffee file and .js file.

I found a few other grunt Markdown plugins, but they all seem to be 5-7 years old, or are using outdated version of **marked** (which I think is why we [chose this plugin](https://github.com/mozilla/fxa/commit/9a7327e9c730857adc8105a78c51781801c3147c) back in the day). There is also https://github.com/thezimmee/grunt-markdown-it which might be an option (if we don't want to include **coffeescript** as a dependency).

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
