### ISSUE TITLE
fxa-email-service - run cargo-audit in CI

### ISSUE THREAD

**Issue by psiinon** [mozilla/fxa#921]
This project does not appear to be using cargo-audit (https://github.com/RustSec/cargo-audit) - that's strongly recommended in order to be warned about dependencies with security vulnerabilities.

**Comment by philbooth** [comment]
Hmm, tried doing this locally first but I get errors installing `cargo-audit`:

```
~/c/f/p/fxa-email-service (pb/921-cargo-audit) $ cargo install cargo-audit
    Updating crates.io index
  Installing cargo-audit v0.6.1
error: failed to compile `cargo-audit v0.6.1`, intermediate artifacts can be found at `/var/folders/dl/6944kw9j7zgbnsqt420nh6br0000gn/T/cargo-installsZhwuR`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/philbooth/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-demangle-0.1.14/Cargo.toml`

Caused by:
  feature `rename-dependency` is required

consider adding `cargo-features = ["rename-dependency"]` to the manifest
```

I wasn't sure if that meant adding `cargo-features = ["rename-dependency"]` to our own `Cargo.toml` so I tried that but it makes no difference.

**Comment by psiinon** [comment]
I've just tried this and for me it failed with:

```
error: failed to run custom build command for `openssl-sys v0.9.43`
process didn't exit successfully: `/tmp/cargo-installsgrWxS/release/build/openssl-sys-c7a18ee0e692d03d/build-script-main` (exit code: 101)
```
(plus a load more error logging) :(
Why cant these things ever be easy??
I'll keep playing with this...

**Comment by psiinon** [comment]
FYI installing openssl-devel fixed my problem.

**Comment by philbooth** [comment]
Currently this repo is pinned to an old version of Rust, which is not compatible with `cargo-audit` (the actual conflict is in a dependency, ref: alexcrichton/rustc-demangle#25). That's the cause of the error I pasted above.

Updating Rust on its own doesn't work, because our pinned dependencies are ancient too and some of them don't compile with latest nightly. But updating them requires knock-on changes code where they've made interface-breaking changes, in particular`emailmessage`, `rocket` and `sendgrid`. I'm still working through those changes but once they're done the audit should be able to complete.

**Comment by philbooth** [comment]
(although a quicker fix of course would be to just spin up a separate container just for `cargo audit`, separately to the container that we run the tests)

**Comment by philbooth** [comment]
Parking this for a bit to work on higher priorities, so leaving some notes for future me.

I have two in-progress branches, `pb/921-cargo-audit` and `pb/921-cargo-audit-hack`.

* `pb/921-cargo-audit` takes the aggressive approach of updating Rust to current nightly, then working through all the knock-on dependency updates that requires. There are a lot of compiler errors to work through. When I left it I was stuck on updating `emailmessage` and was even considering ditching that for something else, partly because I'm struggling to understand some of the interface changes and partly because there are clashes with its version of `hyperx` that I'm also banging my head against.

* `pb/921-cargo-audit-hack` short-circuits much of that work by spinning up a fresh container just for `cargo audit` that uses current nightly. That lets us continue using an older Rust version for the tests and in prod, which means we don't have to update so many dependencies. The only one we have to update to fix the audit warnings is Rocket. I udpated that and fixed our code to work with the breaking changes, but was still left with one compiler error preventing the build from succeeding:

  ```
  error[E0658]: use of unstable library feature 'proc_macro_def_site' (see issue #54724)
     --> /Users/philbooth/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/unstable.rs:347:27
      |
  347 |             Span::Nightly(proc_macro::Span::def_site())
      |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = help: add #![feature(proc_macro_def_site)] to the crate attributes to enable

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0658`.
  error: Could not compile `proc-macro2`.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
  ```
