### ISSUE TITLE
firefox.com/pair throws 500 error when account unverified

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa#923]
When unverified users visit firefox.com/pair it throws 500 error.

EXPECTED RESULTS
It shows the verify your account screen instead of a 500 error.

![Screen Shot 2019-04-24 at 1 27 13 PM](https://user-images.githubusercontent.com/68213/56680203-d0748180-6694-11e9-8005-5586e1775964.png)

**Comment by vladikoff** [comment]
![IMG_20190424_132902](https://user-images.githubusercontent.com/128755/56680848-0f570700-6696-11e9-8862-7f0a7c66dc4f.jpg)

**Comment by shane-tomlinson** [comment]
I see the 500, but with an "Unverified session" error instead of "Missing sessionToken":

<img width="397" alt="Screenshot 2019-04-26 at 17 15 49" src="https://user-images.githubusercontent.com/848085/56821709-fccfff80-6846-11e9-919d-401bbb207dc8.png">

Is it possible to get to the pairing page from Firefox UI w/ an unverified session? I didn't think it was. 

If not, is it worth stressing too much about?

**Comment by vladikoff** [comment]
![](http://v14d.com/i/7ea9d91c43980009f66a0a6401ca2296c53943930cfaa262aa28f546f307d389.png)
