### ISSUE TITLE
[emails M1] Set up CSS solution

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#9247]
FXA-3503 / #8600 decided what CSS solution we should use.

We need to enable this CSS solution in the templating system added in FXA-3504 / #8601. Be sure that the styles load properly in whatever previewing solution was chosen and that when building the template, the styles are inline.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3506)

**Comment by LZoog** [comment]
In #8765, we chose to use MJML and the kind of styling that it provides.

Some questions I have, after #9704 is merged:
* Can we use `.css` files instead of TS files that use stringified CSS?
* If we can use `.css`, can we actually use `.scss` files? SCSS would be awesome for SCSS variables.
* We may want to standardize some values for consistency (margin/padding, font-sizes) and maybe look at the FxA Settings design guide, [see discussion](https://github.com/mozilla/fxa/pull/9704#discussion_r657562561). @Yogita98 I'd say leave this 3rd point for when @jodyheavener and I return. If we can use SCSS, that'd make this easier to do.
