### ISSUE TITLE
Standardise a mechanism for cross-package dependencies

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#941]
I thought we already had an issue for this, but couldn't find one. Close as a dup if I missed it.

Currently there are two mechanisms in play for cross-repo dependencies:

* The historical approach of adding them as dependencies at the npm level, in `package.json`.

* The [ad hoc approach](https://github.com/mozilla/fxa/pull/796) we rushed through for the auth db, where a dependency is copied into consuming packages by scripting.

The disadvantage of using npm is that it enforces a multi-step approach, where changes must be published before they can be used in-tree. It's also node-specific.

The disadvantage of the ad hoc approach is that it requires scripting to run for the dependency to be present. I think I caught most of the cases in that PR but still, it's kind of messy and wastes disk space (which would be more of a concern if we were to adopt it as a standard mechanism for all the deps).

In an ideal world, if we get #694 done we might find that the repo size including dependencies is small enough that we could use a single Docker image for all packages that includes the entire repo. Then we could just `../` up the tree willy-nilly. That seems like it would be the simplest approach, but is weighed down by the fact that #694 is not a priority and will likely hang around for a few months yet.

Maybe we could introduce a generalised version of the copy approach in our scripting as an interim measure, e.g. where we look for certain dependencies in `package.json` then do the copying for all of those in the same places that we did it for the auth db stuff. That would mean adding a `package.json` to the email service, which is written in Rust, but I don't have a problem with that.

Plus there's probably other possibilities I haven't considered here, @mozilla/fxa-devs feel free to weigh in with suggestions or whatever.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-827)
┆Issue Number: FXA-827

**Comment by lmorchard** [comment]
Can [lerna](https://github.com/lerna/lerna) help us out more here? I haven't played with it a bunch yet. I see lots of mentions in the docs about linking inter-dependent packages from the project itself, but scratching my head at whether it helps keep external dependencies in sync between local packages.

**Comment by philbooth** [comment]
@mozilla/fxa-devs, this keeps coming up, I think we should try to come to a decision one way or the other fairly soon.

**Comment by bbangert** [comment]
Based on [Node search paths](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders), we could rename `fxa-shared` to `node_modules`, and Node should then locate them automatically rather than having to publish `fxa-shared` each time a change is made. We could also [use global folders with `NODE_PATH` ](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders) and specify `fxa-shared` in the path to make them available.

Both of these approaches would avoid having to publish the `fxa-shared` directory, and probably make it easier to use changes in `fxa-shared` immediately as they're added.

TypeScript additionally lets one [configure rootDirs ](https://www.typescriptlang.org/docs/handbook/module-resolution.html#virtual-directories-with-rootdirs)to add paths to module resolution, or [project references](https://www.typescriptlang.org/docs/handbook/project-references.html). It also does the standard Node module resolution so any of the above approaches also work.

All of these will require additional Dockerfile changes to bring in the other path during build.

**Comment by philbooth** [comment]
> we could rename `fxa-shared` to `node_modules`

Hmm, my initial reaction to this is :-1:, for a few reasons:

* `fxa-shared` is not the only dependency we have to consider here. There are also cross-package dependencies on files from the auth server (#1603), the content server (#1609), the auth db (#793) and likely others I haven't thought of too.

* We want a solution that works for Rust projects too, so that e.g. the email service tests can start a local auth db instance.

* Maintaining source code inside a `node_modules` directory feels like it would violate the principle of least astonishment.

**Comment by bbangert** [comment]
> We want a solution that works for Rust projects too, so that e.g. the email service tests can start a local auth db instance.

This feels like a separate issue. Starting a local auth db instance is a bit different from Node projects having a way to share common code without having to publish `fxa-shared`. Using the copy approach with `NODE_PATH` seems like it might address both situations though.

**Comment by philbooth** [comment]
> This feels like a separate issue.

It depends on your perspective I guess. To me the issue is that we can't `../` past package boundaries inside Docker containers, which is not an unreasonable assumption to make in a monorepo. It manifests itself in a bunch of different ways, but if we fix that it fixes all the problems.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

We're going to consider this fixed with our use of `yarn`.
