### ISSUE TITLE
Consider allowing get-metrics-flow to log other events besides form views, and to take a uid.

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa#963]
right now we allow reliers to hit our metrics endpoint for the purposes of logging a top-of-funnel `flow.enter-email.view` flow event (which gets translated to `fxa_email_first - view` for amplitude)

https://github.com/mozilla/fxa/blob/cf9ccbb2150f12b6173be8e787023ef0f0ddb236/packages/fxa-content-server/server/lib/routes/get-metrics-flow.js#L31

we may want to expand this so that other events can be logged via this mechanism. examples:

1. a relier has a "sign up for fxa" button on their site, but no email form. if we want to track top-of-funnel for these cases, `flow.enter-email.view` isn't really the right event. however I believe we are logging this in the case of some singin buttons now e.g. send and monitor (we would also need to make a `button.view` event or similar.)

2. monitor also has the following use case. they want clicks on monitor emails (that are only sent to FxA subscribers) to count towards FxA MAU. one way to do this would be to (1) allow `get-metrics-flow` to accept FxA uids and (2) allow it to log an email click event. monitor would then append the user's FxA uid as a query parameter in their email link, and when the user arrives at the monitor site, ping our metrics endpoint with the uid attached. we then log an email click event. 

CC @sandysage @davismtl

**Comment by vbudhram** [comment]
This is to help our reliers, but could be worked on post trailhead.

**Comment by hoosteeno** [comment]
We just discovered that we are unable to accurately measure the top of funnel on www.mozilla.org Whatsnew pages, including Trailhead (67.0.1) and 68, because we haven't instrumented the Monitor sign up button that signed-in-to-sync users get on that page. 

![Screen Shot 2019-08-05 at 5 09 36 PM](https://user-images.githubusercontent.com/94519/62500465-d275d280-b7a3-11e9-96b2-778968d9b4b5.png)

We didn't instrument it in part because there isn't a form_type to associate with this button. It's not an email-first form; it's a different thing. 

On the Fx69 Whatsnew page, we'll show Monitor buttons to all users. If we can't measure the top of the funnel, we won't be able to do good analyses of the performance of that page in acquiring new FxA and activating existing FxA; we won't be able to differentiate the two. And that will carry over into 70. We should fix this.

In preparation for Fx69 and Skyline, we need a new form type to associate with Monitor buttons like the one in the attached screenshot. cc @davismtl @amychurchwell

**Comment by davismtl** [comment]
I put this for the next train since it will be a short train and little is planned for it now.

I'm hoping we can help @hoosteeno measure the impact of /whatsnew in 69 and 70, now that they're using a button.

**Comment by hoosteeno** [comment]
@davismtl can you tell us what the parameter should be when it is ready? And do you expect this to be ready by 9/3/19? We're finalizing WNP69 right now.

**Comment by irrationalagent** [comment]
fwiw, what needs to be done here as i understand it:

- allow RP to pass `button` for `form_type`
- create a new amplitude event like `fxa_button - view` or maybe `fxa_rp_button - view` and log that instead of `fxa_email_first - view` when we see form_type = button.

**Comment by davismtl** [comment]
@irrationalagent @clouserw 
Do you think we could get that to on time for @hoosteeno ? 

The trains don't seem to line up with the next Fx release but I know that this new event would help mozilla.org and marketing better measure performance of the new /whatsnew page that'll open for all users with the next release.

@irrationalagent Your proposed events make sense. I'm starting to think we may soon need to add to amplitude an equivalient of flow_begin given we now have a few events that can be top of funnel.

**Comment by johngruen** [comment]
We need this for firefox private network

**Comment by johngruen** [comment]
gonna pick this up to learn more about metrics!

**Comment by philbooth** [comment]
> ok you should be good to go on submitting form_type=button for requests to this endpoint now. when you do this we will now log a `fxa_rp_button - view` event in amplitude

Although, just to be clear, currently this is not scheduled to go out until train 145 so it won't work in prod for a couple of weeks. If it's needed there sooner, we can tag a point release for train 144 too though, no dramas.

**Comment by philbooth** [comment]
No probs, I am on the case!

**Comment by philbooth** [comment]
Closing, this landed in train 144.
