### ISSUE TITLE
Refresh device list after disconnecting a device from device manager (now called connected services)

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#9899]
I've recently had to reinstall a few devices and had to pleasure of using the new FxA device manager (now called connected services) in fxa settings.

I encountered one small UX problem that made it feel like the device manager was broken.

Expected experience
When I sign out/ disconnect a device, it disappears from the list so that Iknow it worked.

Actual result
If I disconnect a device, it remains in the device list. I can try to disconnect it 2 or 3 times and it just remains there. For the old device to go away, I have to click the little refresh wheel at the top right of the device manager. This should happen automatically after a device has been removed so that users know that the action worked.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3765)

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Thanks for filing this.  We're thinking these are remaining in the list because the devices are logged in multiple times and have pulled multiple keys (like, a browser logged in to sync and the web site).  When you click 'disconnect' it removes one key but leaves the other.

This doesn't explain why it wouldn't remove it on the 2nd or 3rd try, or why hitting refresh would make it disappear, but it's what we're thinking right now.

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
