### ISSUE TITLE
Ensure we're monitoring client-side performance data for new Subscriptions pages

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#996]
We can use re:dash for this since that is where our other performance data is going.  I just want to make sure the new pages are instrumented and we can see any performance concerns.

**Comment by philbooth** [comment]
Specifically, the implementer should tweak this bit of code in the content server, so that the new views get their own performance category instead of being lumped in with `other`:

https://github.com/mozilla/fxa/blob/dcf8db2529513409bfa767840ef56b281f9f1b18/packages/fxa-content-server/server/lib/flow-event.js#L94

The `other` category has pretty bad performance due to the `/settings` view, which we know to be slow. It would make sense to analyse these numbers without being dragged down by that.

**Comment by philbooth** [comment]
> Specifically, the implementer should tweak this bit of code in the content server...

Ignore me, just remembered that these aren't going to be hosted in the content server.

**Comment by chenba** [comment]
I can think of three new pages: support form, payments forms, and subscription management.

Support form is on the content server, and the others are on the payments server.

**Comment by chenba** [comment]
Since https://github.com/mozilla/fxa/pull/2481 added the flow event mixin to the support form view, performance metrics should just show up in Redshift once the Support Form is in prod.  Although I think they'd go into the `flow.performance.other*` types.

**Comment by chenba** [comment]
hahah never you literally answered my question above already!!  sorry!

**Comment by chenba** [comment]
https://github.com/mozilla/fxa/pull/2574 removed the auth/other categories. 🎉
