### ISSUE TITLE
Login Error on Monitor

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa#999]
![image.png](https://images.zenhubusercontent.com/5ca2448cb4170956617cd475/74c3f129-11bd-464f-adcc-df8d02dde5bb)

Conditions:
- Nightly 68.0a1 (2019-04-29) (64-bit)
- Mac
- Signed in to sync in the browser

Steps to reproduce:
- Go to monitor.firefox.com
- Click Sign in top right of page
- On account.firefox.com (your email should already be displayed), click Sign In

Result:
- Unexpected Error (See screenshot)

Expected:
- Successful login

Console log:
![image.png](https://images.zenhubusercontent.com/5ca2448cb4170956617cd475/74001581-50ed-47a2-bb5a-2f86a8746195)

**Comment by davismtl** [comment]
Filed from Slack conversation:
https://mozilla.slack.com/archives/C93K0MBM5/p1556570277037900

Betsy Mikel also experienced this.

I'm unable to reproduce on Beta.

**Comment by davismtl** [comment]
I also confirm that I am properly signed into my browser and that I can access my preferences at accounts.firefox.com

**Comment by rfk** [comment]
Michael Feldman also experienced this, so I imagine it's fairly widespread.  I wasn't able to reproduce with a fresh signin to sync, but it could be specific to particular settings in the browser.

**Comment by rfk** [comment]
From network logs, this is a 401 on `/certificate/sign`, which explains the initial "invalid token".

**Comment by rfk** [comment]
Response body: `{“code”:401,“errno”:110,“error”:“Unauthorized”,“message”:“Invalid authentication token: Missing authentication”,“info”:“https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format“}`

**Comment by rfk** [comment]
The error string "Missing authentication" is very unusual here - it come from the hapi auth machinery, and AFAICT it means that hapi did not find an appropriate authentication strategy to use for the request. Which suggests maybe a corrupted authorization header rather than a problem with the sessionToken.

**Comment by rfk** [comment]
I wasn't able to reproduce this yesterday, but tried it again today and I'm getting the same error (and same tracebacks). One odd thing I noticed is that my state in `localStorage` seems to have a `sessionTokenContext` but no `sessionToken`:

![Capture](https://user-images.githubusercontent.com/34695/57106258-3daca480-6d70-11e9-87a8-90e20b1be020.PNG)

Is this expected? I wonder if some issue with the fxa_status handshake in nightly is corrupting the state here.

**Comment by vladikoff** [comment]
@rfk sessionToken seem to go missing in https://github.com/mozilla/fxa/issues/923#issuecomment-486346754 as well.

**Comment by rfk** [comment]
The flow I see is also slightly weird end-to-end.

1) I'm signed in to sync in my browser.
2) I go to monitor.firefox.com and click the "sign in" button
3) I see the email-first screen asking me to enter my email
4) I enter the same email as the account signed in to the browser, and click "continue"
5) It transitions to the "passwordless signin" page, I guess trying to use the sessionToken with which I'm signed in to sync.
  * This page tries to load my profile picture, fails, and logs "invalid token" traceback to the web console
6) I click "sign in" to continue the flow.
7) This throws an "unexpected error", which gives the red error bar and logs traceback to dev console

It seems odd that I see the email-first screen in (3) and then the passwordless-signin screen in (5), since (5) suggests that the page already knew who I was.

If I try to same thing on AMO, I get a different flow:

1) I'm signed in to sync in my browser.
2) I go to addons.firefox.com and click the "register or in" button
3) I see the blank signin form prompting me for username and password
  * Interestingly, this page also attempts to load my profile picture, despite not appearing to know we I am?  The debugger shows it triggering the same "invalid token" error as in the flow above, although it gets swallowed and is not logged to the web console
4) I enter my username and password, which is accepted and I transition to the TOTP prompt
5) I enter a TOTP code and am successfully signed in, transitioning back to AMO

After doing that successfully on AMO, I am no longer able to reproduce the bug with monitor.  Clicking "sign in" on monitor takes we directly to the "passwordless login" screen, where I can just click "sign in" and proceed to monitor.

My `localStorage` state now contains a `sessionToken`.  It's a new one, different to the one that is held by the browser and being used for sync.  But I still have `sessionTokenContext=fx_desktop_v1`, which seems wrong.

In fact, even after signing *out* of sync in the browser, I'm still signed in to FxA on the web and I still get the "passwordless login" experience when connecting to OAuth reliers.  Visiting accounts.firefox.com/settings shows me signed in and does not give me an option to sign out.  I...appear to be stuck signed in to this account on the web with no obvious way to sign out of it.

I feel like this is some sort of bad interaction between the email-first flow and fxa_status, but I haven't put my finger on what yet.  Either way, something is very wrong here.

**Comment by rfk** [comment]
(I meant to say, the only difference I could observe between AMO and Monitor is that AMO uses `action=signin` and Monitor uses `action=email`; if I can get back to a state where I can repro this bug, I'll test whether changing AMO to use `action=email` causes the same issue).

**Comment by rfk** [comment]
> One odd thing I noticed is that my state in localStorage seems to have a sessionTokenContext but no sessionToken

If I manually modify my `localStorage` to delete the sessionToken:

```
>>> data = JSON.parse(localStorage['__fxa_storage.accounts'])
>>> delete data["afac2..."]["sessionToken"]
>>> localStorage['__fxa_storage.accounts'] = JSON.stringify(data)
```

Then attempt to sign in to monitor again, I am able to reliably reproduce this issue.

So I'm wondering if some bug in Nightly has lead to weird corruption of `localStorage` state, and in turn uncovered some incorrectly-handled error condition in the email-first flow.

**Comment by rfk** [comment]
I do see two places in the Account model where is clears the `sessionToken` but leaves `sessionTokenContext` alone:

* https://github.com/mozilla/fxa/blob/0f78f956c8e5afaf8f7626149be04343ac3fcc2e/packages/fxa-content-server/app/scripts/models/account.js#L289
* https://github.com/mozilla/fxa/blob/0f78f956c8e5afaf8f7626149be04343ac3fcc2e/packages/fxa-content-server/app/scripts/models/account.js#L326

ISTM these should be using the `discardSessionToken` helper rather than directly calling `unset`. But it's not clear yet whether I might have triggered either of these cases and caused this issue.

**Comment by rfk** [comment]
It would also be possible to end up in this state, if the browser somehow sent an `fxa_status` response that did not contain a sessionToken, via codepath here:

  https://github.com/mozilla/fxa/blob/0f78f956c8e5afaf8f7626149be04343ac3fcc2e/packages/fxa-content-server/app/scripts/models/user.js#L740

**Comment by rfk** [comment]
> I wasn't able to reproduce this yesterday, but tried it again today and I'm getting the same error
> (and same tracebacks). 

I should add, what I was *not* seeing was the 401 in the network logs mentioned in https://github.com/mozilla/fxa/issues/999#issuecomment-488430413; in my case no request was being attempted at all, I suppose because the sessionToken was completely missing.

**Comment by shane-tomlinson** [comment]
> I should add, what I was not seeing was the 401 in the network logs mentioned in #999 (comment); in my case no request was being attempted at all, I suppose because the sessionToken was completely missing.

This makes sense, in the fxa-js-client, [if no sessionToken is present an error is returned w/o a network request being made](https://github.com/mozilla/fxa/blob/42c6a84b306710d25cbe9d223d06192de59d5abc/packages/fxa-js-client/client/FxAccountClient.js#L375).

Could this be related to OAuth token pruning we were discussing yesterday?

**Comment by shane-tomlinson** [comment]
I figured a 100% reproducible way of making this happen:

1. In browser A, sign in to Sync.
2. In browser A, open the settings page directly.
3. In browser B, disconnect browser A.
4. Focus the settings page on browser A, you will be signed out.
5. Open up the network console, check localStorage. An account entry is there w/ a sessionTokenContext and no sessionToken.
6. Open up `/?action=email&email=<email from step 1>`
7. Try to sign in. Wah wah.

Here's a video:

![bunk-session](https://user-images.githubusercontent.com/848085/57132452-92174a80-6d97-11e9-8fe1-227588bbc58f.gif)

**Comment by shane-tomlinson** [comment]
In this case, this is indeed caused by calling [this.unset('sessionToken')](https://github.com/mozilla/fxa/blob/42c6a84b306710d25cbe9d223d06192de59d5abc/packages/fxa-content-server/app/scripts/models/account.js#L289) instead of [discardSessionToken](https://github.com/mozilla/fxa/blob/42c6a84b306710d25cbe9d223d06192de59d5abc/packages/fxa-content-server/app/scripts/models/account.js#L151). It looks like this could also happen because of [sessionVerificationStatus](https://github.com/mozilla/fxa/blob/42c6a84b306710d25cbe9d223d06192de59d5abc/packages/fxa-content-server/app/scripts/models/account.js#L326) which is used by the settings page to gate panels that require a "fully verified session".

**Comment by shane-tomlinson** [comment]
Re-opening, there was just a report of this in Slack.

Holly's STRs:

1. Sign into Sync
2. Open a "Personal" tab container
3. Go to https://monitor.firefox.com, click "Sign in"
4. The default profile photo is displayed.
5. When clicking "Sign in", "Unexpected error" is displayed.

Holly said in the console there was an "Invalid token" error.

Sentry is reporting an increase in these errors with train-141: https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/6052819/?query=is:unresolved%20invalid%20token

They seem to be coming from https://github.com/mozilla/fxa/blob/cefa7128cfb5a1d1391424c0f4d6c462b6380e5c/packages/fxa-content-server/app/scripts/models/account.js#L155.
